### ISSUE TITLE
Paste as link with no selection

### ISSUE THREAD

**Issue by charlesroper** [SublimeText-Markdown/MarkdownEditing#107]
I've just spent about 15 minutes trying to work out why the paste as link command doesn't work. Turns out it does work, but it requires a selection. Ideally it should work with no selection and inject tab-stops in appropriate places (i.e., between [] and at the end)

**Comment by felixhao28** [comment]
Pasting as link does not require a selection anymore, so I close this for now. But the discussion can continue. Feel free to reopen it if you have something to say about it.

**Comment by maliayas** [comment]
Felix, I think it would be good to add these to the command palette. I'm pasting from keybindings table:

* Pastes the contents of the clipboard as an inline link on selected text.
* Inserts a standard inline link.
* Inserts an inline image.
* Inserts a footnote and jump to its definition. If your cursor is in a definition, it will jump back to the marker.
* Locates footnote markers without definitions and inserts their markers for the definition.

**Comment by felixhao28** [comment]
Then how about we open a separate issue for these enhancements? So it is easier to track down.

**Comment by maliayas** [comment]
Sure.

**Comment by felixhao28** [comment]
These enhancement requests have been moved to #256
