### ISSUE TITLE
Bold shortcut conflicts with Mac OS backward key binding

### ISSUE THREAD

**Issue by zaopuppy** [SublimeText-Markdown/MarkdownEditing#116]
In Max OS, ctrl-b is a global key binding for moving cursor backward. Is it possible to change it to other key combination?

**Comment by felixhao28** [comment]
This issue is already fixed in 7e28ad2fb777692f28e20197595e7479a53fd011, right?

**Comment by maliayas** [comment]
Keymap conflict is fixed. But @zaopuppy  was saying the functionality wasn't working for him. Not sure if that's fixed.

**Comment by ruvido** [comment]
same here using ST3 cannot have Ctrl-B or Ctrl-I to work ...

**Comment by zaopuppy** [comment]
Hi.

  I haven't seem this issue after one update (I can't remember which one).

  I'll close this issue if there's no more feedback.
