### ISSUE TITLE
Command Palette: Generate TOC (GFM)

### ISSUE THREAD

**Issue by maliayas** [SublimeText-Markdown/MarkdownEditing#120]
GitHub flavored markdown creates HTML anchors for headers and this makes a TOC possible. With this command, users will be able to create a TOC automatically. It will be inserted where the cursor is.

When generating anchor name, GitHub uses header's text and sanitizes it in some way. We have to find out the details of that sanitization in order to make the feature robust.

**Comment by felixhao28** [comment]
Use [MarkdownTOC](https://github.com/naokazuterada/MarkdownTOC) for this task. Closing this issue for now.
