### ISSUE TITLE
Disable option for some keybindings

### ISSUE THREAD

**Issue by maliayas** [SublimeText-Markdown/MarkdownEditing#121]
Pressing `*` generates `*|*`. Such features may drive some users crazy. ST setting `auto_match_enabled` controls some of these but it would be better to have a plugin wide control.

Suggestions are welcome during the development on this issue. E.g. "Feature X must have a turn off setting".

**Comment by felixhao28** [comment]
Footnote commands are finally fixed after more than one year of hard working.

Related commit: 6ce2feed082ec3d3bdbdddada5924f16a0882e55
