### ISSUE TITLE
Code block in lists not highlighted

### ISSUE THREAD

**Issue by maliayas** [SublimeText-Markdown/MarkdownEditing#122]
Screen shot:

![ekran grnts 2013 12 11 15_33_40](https://f.cloud.github.com/assets/844008/1724366/9594b8da-626e-11e3-8afd-95fe0256eac0.png)

Text:

```
* Lorem ipsum

        This is a code block.
```

**Comment by johanngerell** [comment]
+1 for this. Surprised this hasn't bee naddressed after so long time. Although the rest of this plugin seems to match my needs, my writing needs depend heavily on having code snippets in lists, so this is a deal breaker to me.

**Comment by maliayas** [comment]
I opened the bug for reference; however probably implementing this is not possible with the current ST API. It is regex based and this task is a little complex for regex.

/cc @felixhao28

**Comment by johanngerell** [comment]
> this task is a little complex for regex

Why is that?

**Comment by felixhao28** [comment]
@johanngerell As a workaround for now, you can use

```markdown
* Lorem ipsum

    `Your code here`
```

This produces expected html output and is highlighted by MDE correctly.


* Lorem ipsum

    `Your code here`

Reading those regex expressions in the tmLanguage files makes my head blow up every time.

**Comment by maliayas** [comment]
> Reading those regex expressions in the tmLanguage files makes my head blow up every time.

Same here. There is an ASCII mountain there :P
