### ISSUE TITLE
Continue blockquote when pressing Enter for new line

### ISSUE THREAD

**Issue by LeEnno** [SublimeText-Markdown/MarkdownEditing#132]
When typing something like `> Start of a quote` and pressing Enter, the new line should start with a "<" and a space. Basically it's the same behavior as seen with lists.

**Comment by reagle** [comment]
Is there a way to disable this? All my block quotes are copy/paste and it's a nuisance to get out of the blockquote and continue writing.

**Comment by felixhao28** [comment]
Block quotes used to behave like lists (double enter exit), but it is changed in 9e0f903c07585c380505f7f25775d2bf34539cb7. So I guess it is a designed experience.

**Comment by maliayas** [comment]
Yes, that is intended behaviour. You may want to have empty lines inside a blockquote. So I removed the "clear on double-enter" feature. However this is not true for lists, so lists can have this feature.

**Comment by reagle** [comment]
Yes, but is there a way to configure (i.e., disable) it? This behavior still bugs me.

**Comment by maliayas** [comment]
I don't think that's a common need. Sorry for that. But you can modify your ST keymap file and copy & adapt [these lines](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/2e93d23f20a99d14c69fa4f3f605a566310ad877/Default%20(Windows).sublime-keymap#L356-L365) for blockquotes.

**Comment by reagle** [comment]
It looks like shift+enter will exit blockquote mode, so I'll have to train my muscle memory and hope others weigh in favor of consistency 😬 

Thanks for responding though!
