### ISSUE TITLE
Push to Marked

### ISSUE THREAD

**Issue by jdkram** [SublimeText-Markdown/MarkdownEditing#143]
To preview what my files will look like on my website I use [Marked](http://marked2app.com/), an app you might just be familiar with ;). Would you consider adding push to Marked or Marked 2? 

Could be a build system (but then the default ⌘-B for bold would fail, so you'd have to switch to the backup ⌘-⌥-B.

I tried [Markdown Preview](https://github.com/revolunet/sublimetext-markdown-preview) but it's not as feature rich and creates html files in places I don't want them.

**Comment by anatomatic** [comment]
I believe the package Brett mentioned [Marked App Menu](https://packagecontrol.io/packages/Marked%20App%20Menu) does exactly what @jdkram is asking — this issue can be closed.
