### ISSUE TITLE
Vertical centering not working?

### ISSUE THREAD

**Issue by charlesroper** [SublimeText-Markdown/MarkdownEditing#148]
I can't seem to get the vertical centering feature to work. I've got `"mde.keep_centered": true` enabled. I'm on build 3061. I've ensured the setting is in the correct user settings file. Not sure if I'm doing something wrong or not. Any ideas?

**Comment by deathaxe** [comment]
ST4 allows to specify `"context_lines"` which is the amount of lines below/before the caret which cause the view to scroll.
