### ISSUE TITLE
 Footnotes keyboard shortcut not working on OS X

### ISSUE THREAD

**Issue by robotsandcake** [SublimeText-Markdown/MarkdownEditing#153]
Hello,

I've Just come across a really strange problem, I tried to add a footnote as I normally would using the keyboard shortcut <kbd>⌘</kbd><kbd>⇧</kbd><kbd>6</kbd>  but nothing happened.  The cursor just sat there doing nothing, silently mocking me!

I've been using this package daily for months and months without any problems, and as far as I'm aware[^1] nothing has changed on my machine that could cause this problem.  It really is quite strange having a little hole poked in my writing workflow, very destabilising indeed.  ;-)

I'm not a programmer so my ability to chase down this problem is somewhat limited, as in I went to change the key binding assuming that a conflict had cropped up some were but I was unable to find where to change it!

Will somebody please take pity on me and point me in the direction of a solution?

Many thanks

Some potentially useful information:

Sublime Text 3
OS X 10.9
[A Puma 6 Wheelchair](http://www.handicare.co.uk/1/Products/Power-wheelchairs/1/Puma-40/)

[^1]: For a given value of aware!

**Comment by maliayas** [comment]
FYI Fixed in 2.1.1
