### ISSUE TITLE
Better integration with Critic?

### ISSUE THREAD

**Issue by jgclark** [SublimeText-Markdown/MarkdownEditing#165]
The [Critic Markup](www.criticmarkup.com) extension to Markdown is very helpful for some use cases. The team have provided a [plugin for ST](http://criticmarkup.com/sublime-text.php) which nicely colours the comments and changes. But it deliberately makes all other markup just shades of grey.

I'd love some integration between MarkdownEditing and Critic colouring, so that we can have the colouring and font effects from both. I know just enough about ST plugins to know this is probably not a trivial request, so for now I'll just see how possible it is in theory.

**Comment by felixhao28** [comment]
related to #144
