### ISSUE TITLE
Blackboard theme

### ISSUE THREAD

**Issue by mdesantis** [SublimeText-Markdown/MarkdownEditing#173]
Hello,

since I'm addicted to Blackboard theme I would like to add a Blackboard theme to this package. 

I [started working on it](https://github.com/mdesantis/MarkdownEditing/tree/blackboard-theme); but I'm a noob at Sublime Text plugins, so I ask you for suggestions.

At the moment I created a [Blackboard.tmTheme](https://github.com/mdesantis/MarkdownEditing/blob/blackboard-theme/MarkdownEditor-Blackboard.tmTheme), duplicating the Dark theme and merging with the [Colorsublime's Blackboard theme](https://github.com/Colorsublime/Colorsublime-Themes/blob/master/themes/Blackboard.tmTheme); but now I'm unsure about how to proceed: f.e., how to check display some of the colours in order to check if they are good, f.e. `settings -> inactiveSelection`?

Am I in the right direction? Do you have any suggestions?

**Comment by felixhao28** [comment]
@mdesantis  Are you still working on that? If not, maybe we can close the issue.

**Comment by mdesantis** [comment]
If anyone could support me I would like to work on it; otherwise you can close

**Comment by felixhao28** [comment]
Sorry but I still don't understand what kind of support you need. Your theme works just fine for me.

![image](https://cloud.githubusercontent.com/assets/2417391/6408704/7ea4ad1e-be94-11e4-8478-bdf57d3caf39.png)

**Comment by pierresh** [comment]
Best theme ever, thanks a lot @mdesantis :)

**Comment by pierresh** [comment]
Best theme ever, thanks a lot @mdesantis :)
