### ISSUE TITLE
Need Scheme Syntax Highlighting Support

### ISSUE THREAD

**Issue by aftertommy** [SublimeText-Markdown/MarkdownEditing#174]
It would be nice to have support for ```scheme blocks with syntax highlighting.

**Comment by felixhao28** [comment]
@maliayas Yes, there is an error raised in the console if the syntax file is missing. But unless you open the console with ``ctrl+```, the error is silent. As far as I see it, missing included syntax file does not affect the main markdown syntax or other included external syntax. I think it is safe enough to include non-vanilla syntax support for fenced code blocks.

Since github highlights scheme properly, I think our GFM should do the same.

Before installing `sublime-scheme-syntax`:

![image](https://cloud.githubusercontent.com/assets/2417391/8199074/4a875ee2-14e2-11e5-82fc-6f80a2132700.png)

After installing `sublime-scheme-syntax`:

![image](https://cloud.githubusercontent.com/assets/2417391/8199071/37d3f1ca-14e2-11e5-93d9-96521173b997.png)

I am working on adding external syntax support for scheme and swift. So we can close [this]() and #275.

**Comment by maliayas** [comment]
Alright, I agree. Thanks.
