### ISSUE TITLE
Increasing delay using Tab in long document

### ISSUE THREAD

**Issue by vongoh** [SublimeText-Markdown/MarkdownEditing#176]
I've recently been having an issue editing a long `.md` document in Sublime Text 3 Windows whenever I use the Tab key - and I am using Mardown Editing for all of my markdown work.

There is a long delay between pressing Tab and the result:  I press Tab, there is no response on the screen and the Sublime interface locks up.   Continuing to click on the document forces a blue 'waiting' indicator to show.

I don't have this issue with any other type of document - including documents of other types in the same project (ie.  `.html` and `.css` documents do not show this issue.)

The other feature to this is that the further down I am in the document - the longer the delay and lockup.  Near the top of the `.md` doc there is almost no delay.  But the delay gets progressively longer.

At line 500 it is negligible.  At line 1000 it is 2 secs.   At line 1500 it is 5 secs.   At line 2000, 9sec.  Line 2500, 13 secs .. and so on.

**Comment by guerrero** [comment]
Same problem here.
I'm editing a markdown file with about 750 lines and every time I press tab it takes around 1s to run. I'm using ST3 in Yosemite OSX and I'm sure that the bug is related to this package because when I disable it everything works as expected.

PS: As a workaround I type four consecutive spaces and then I search and replace them with a tab

**Comment by maliayas** [comment]
Where exactly the cursor is on when you press tab? For example, inside a list definition?

I still can't reproduce this. I'm testing with 35k lines document and it acts reasonable.

If you could link to a public markdown document that I can see the bug, it would help.

**Comment by guerrero** [comment]
It fails in every situation I've tested (inside code, nested lists...), sorry for being annoying but you should try it in the last lines of your file. If your are using a 4k file test it in the line 3500 for example. I've created a [gist][1] with a file to test the bug.

And [here][2] is a gif that shows the problem. The delay time in the gif is real, it takes too long to work. So please be patient and don't close the page until the gif ends to see the operation with MarkdownEditing enabled and disabled.

[1]: https://gist.github.com/guerrero/0c3d945b23e892ae54e4/download
[2]: http://imgur.com/hi9x6Fy

Thanks for the support :)

**Comment by StefanoRausch** [comment]
Works fine on my side, no lags at all. What other plugins do you have installed?

**Comment by guerrero** [comment]
I've been researching and the problem appears to be related with Emmet package.

**Comment by StefanoRausch** [comment]
Strange, I have Emmet installed too. Must be another one.

**Comment by guerrero** [comment]
I've removed my Sublime Text settings from `Application Support` and reinstalled only Package Control and MarkdownEditing and it works but then I've installed Emmet package and it doesn't works. Finally I've disabled Emmet and everything is back to work.

Here's my environment:
Yosemite 10.10.1
Sublime Text 3 beta 3065
MarkdownEditing 2.0.9
Emmet 2015.01.07.20.42.22

**Comment by maliayas** [comment]
@guerrero Are you able to try the v2.1.0 branch? I haven't made new commits but it has some changes compared to the master branch.

**Comment by StefanoRausch** [comment]
Ok, I am still on ST 2 — same OS / plugins' versions though.

**Comment by guerrero** [comment]
@maliayas v2.1.0 doesn't work either :(. Maybe the bug is in the Emmet package. Meanwhile I will disable Emmet. Does anyone know if I can disable certain packages for a specific filetype?

**Comment by vongoh** [comment]
@guerro  thanks for the tip!   On both the spaces / replace tip and discovering Emmet as the culprit.

I uninstalled Emmet and the issue disappeared here.  ST3 Build 3065 on Win 8.1
