### ISSUE TITLE
[ENH] tabstop in bullet lists

### ISSUE THREAD

**Issue by CircleCode** [SublimeText-Markdown/MarkdownEditing#177]
when writing bullet lists, the first use of <tab> shoud move the cursor to the next tabstop and then the next use would decrease the bullet level.

say, for example, I have (`|` represents the cursor)

``` md
- |
```

after first tab, I want

``` md
-   |
```

and after next tab

``` md
    +   |
```

---

the current behavior is
say, for example, I have (`|` represents the cursor)

``` md
- |
```

after first tab, I have

``` md
    + |
```

**Comment by felixhao28** [comment]
@CircleCode What's wrong with the current behavior?

**Comment by CircleCode** [comment]
@felixhao28 I will explain with my use case, which is pretty common I think.
I want text to start at column 0, 4, 8… so that a multi line block is homogeneous.
this gives:
```md
-   first line
    second line of same block
```
With current behavior, I can't use `tab` to start first line at column 4 becaus it would move the bullet char rather that the cursor, s I have to use `space` several time to align text, which is neither convenient nor semantically correct (even if the result is the same).
I'd expect ME to support something like tab stops.

**Comment by felixhao28** [comment]
But you only need to adjust the spaces once per list, the indent is kept when you press `Enter` or `Shift+Enter`. Are you saying indenting the first line is tedious?

**Comment by deathaxe** [comment]
The solution in 3.0.0 looks as follows:

Hitting `tab` key after bullet was typed, automatically inserts enough spaces to place caret to next tab level.

1. Enter `*`

   ```
   *|*
   ```

2. Enter `tab`

   ```
   *   |
   ```

3. Enter `tab` again

   ```
       +   |
   ```
