### ISSUE TITLE
Cmd-R - lines that contain an id XML attribute appear in Cmd-R list as H1

### ISSUE THREAD

**Issue by jonathanmorgan** [SublimeText-Markdown/MarkdownEditing#184]
Hi,

I am on a Mac, OS X 10.9.2, using Sublime Text 3 Build 3059, MarkdownEditing 2.0.8. When I hit Cmd-R, Sublime outputs a list of the headers in my document, indented based on the number of pound signs to show hierarchy.  All is well, except for one thing: lines that contain an XML id attribute are output as 1st level headers (I call this H1 in the title, for brevity).  Is this an expected behavior?  A markdown sample that evidences this behavior in my install on OS X and on Ubuntu 14.04, same versions of sublime and markdownediting, is inline below since you can't upload a markdown file.

It is a little thing, but figured I'd submit it.  Overall, Cmd-R 

works well.

Thanks,

Jonathan Morgan

==============================

    ### models aren't configured to match database?

    - foreign key constraints missing from spec?  Check domain files to see if these FKs are specified in models.
    - foreign keys in database:

            <changeSet author="jonathanmorgan (generated)" id="1392411774169-11">
                <addForeignKeyConstraint baseColumnNames="TASK_ID" baseTableName="TASK_PROPERTIES" baseTableSchemaName="PUBLIC" constraintName="TP_FK_1" deferrable="false" initiallyDeferred="false" onDelete="RESTRICT" onUpdate="RESTRICT" referencedColumnNames="ID" referencedTableName="TASKS" referencedTableSchemaName="PUBLIC" referencesUniqueColumn="false"/>
            </changeSet>
            <changeSet author="jonathanmorgan (generated)" id="1392411774169-12">
                <addForeignKeyConstraint baseColumnNames="TASK_TYPE_ID" baseTableName="TASK_TYPE_PROPERTIES" baseTableSchemaName="PUBLIC" constraintName="TTP_FK_1" deferrable="false" initiallyDeferred="false" onDelete="RESTRICT" onUpdate="RESTRICT" referencedColumnNames="ID" referencedTableName="TASK_TYPES" referencedTableSchemaName="PUBLIC" referencesUniqueColumn="false"/>
            </changeSet>
            <changeSet author="jonathanmorgan (generated)" id="1392411774169-13">
                <addForeignKeyConstraint baseColumnNames="PROCEDURE_ID" baseTableName="TASKS" baseTableSchemaName="PUBLIC" constraintName="T_FK_1" deferrable="false" initiallyDeferred="false" onDelete="RESTRICT" onUpdate="RESTRICT" referencedColumnNames="ID" referencedTableName="PROCEDURES" referencedTableSchemaName="PUBLIC" referencesUniqueColumn="false"/>
            </changeSet>
            <changeSet author="jonathanmorgan (generated)" id="1392411774169-14">
                <addForeignKeyConstraint baseColumnNames="ROLE_ID" baseTableName="USERS_ROLES" baseTableSchemaName="PUBLIC" constraintName="UR_FK_2" deferrable="false" initiallyDeferred="false" onDelete="RESTRICT" onUpdate="RESTRICT" referencedColumnNames="ID" referencedTableName="ROLES" referencedTableSchemaName="PUBLIC" referencesUniqueColumn="false"/>
            </changeSet>
            <changeSet author="jonathanmorgan (generated)" id="1392411774169-15">
                <addForeignKeyConstraint baseColumnNames="USER_ID" baseTableName="USERS_ROLES" baseTableSchemaName="PUBLIC" constraintName="UR_FK_1" deferrable="false" initiallyDeferred="false" onDelete="RESTRICT" onUpdate="RESTRICT" referencedColumnNames="ID" referencedTableName="USERS" referencedTableSchemaName="PUBLIC" referencesUniqueColumn="false"/>
            </changeSet>

    - foreign keys generated based on models:

            <changeSet author="jonathanmorgan (generated)" id="1391748478025-12">
                <addForeignKeyConstraint baseColumnNames="role_id" baseTableName="USERS_ROLES" constraintName="FKADBB81866B291D0" deferrable="false" initiallyDeferred="false" referencedColumnNames="id" referencedTableName="ROLES" referencesUniqueColumn="false"/>
            </changeSet>
            <changeSet author="jonathanmorgan (generated)" id="1391748478025-13">
                <addForeignKeyConstraint baseColumnNames="user_id" baseTableName="USERS_ROLES" constraintName="FKADBB8186ABDD55B0" deferrable="false" initiallyDeferred="false" referencedColumnNames="id" referencedTableName="USERS" referencesUniqueColumn="false"/>
            </changeSet>

    ### multi-part key uniqueness constraints

    - How do you do this in grails models?  If no easy way, then need to just have the constraints from existing database in the migration.

**Comment by felixhao28** [comment]
@jonathanmorgan Ctrl+R is a ST3 shorcut for "Goto symbol". In your case, _id_ attribute is considered as a symbol in this "html" document by ST3. Ctrl+R is not a feature of this plugin (even though it works well).

**Comment by jonathanmorgan** [comment]
Ah.  Ok.  Thanks for explanation!  I only noticed it after the latest release, but that must have been there the entire time, and this was the first time I placed code in a document with the "id" attribute.

**Comment by maliayas** [comment]
Actually we can decide what can/cannot goes into the symbol list via these files:

* [Symbol List - Heading.tmPreferences](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/master/Symbol%20List%20-%20Heading.tmPreferences)
* [Symbol List - Hide.tmPreferences](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/master/Symbol%20List%20-%20Hide.tmPreferences)
