### ISSUE TITLE
YAML Front Matter 

### ISSUE THREAD

**Issue by jackmcdade** [SublimeText-Markdown/MarkdownEditing#194]
I absolutely love this package, thank you so much for going to these lengths to make Sublime the best Markdown editor. :+1: 

Now for the obligatory feature request -- is there any chance you'd consider adding [YAML Front Matter](http://jekyllrb.com/docs/frontmatter/) support?

**Comment by reagle** [comment]
does v2.2.4 fix this?

**Comment by felixhao28** [comment]
v2.2.4 intends to address this enhancement.

**Comment by felixhao28** [comment]
@reagle regarding to the bug you found, let's discuss [over there](https://github.com/SublimeText-Markdown/MarkdownEditing/pull/448).
