### ISSUE TITLE
The first list entry marker is colored differently

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText-Markdown/MarkdownEditing#195]
This issue is also existant as #22 but it was merged (even though it was somehow not) and thus closed, so I open a new one.

The first list entry marker is not colored like all the following, for both ordered and unordered lists. Here is a screenshot illustrating the issue:
![2014-07-01_22 46 39_markdown-editing_first-list-item](https://cloud.githubusercontent.com/assets/931051/3449062/6df40668-0161-11e4-904d-324f016cb321.png)

Naturally, the scopes for the first list item markers are different.

**Comment by ivanpirog** [comment]
The same issue in 2020. Issue need to be reopened.
