### ISSUE TITLE
How to enable auto complete box in MarkdownEditing?

### ISSUE THREAD

**Issue by Vorsaykal** [SublimeText-Markdown/MarkdownEditing#201]
While editing a Markdown file, I don't get the option to auto complete things using the drop down box that appears. For example, if I am typing a word I've already typed, it'll list suggestions for that word, or suggestions for snippets and such.

I added _"tab_completion": true_ to my user settings, which brings back the tabbing, but it still doesn't display the box of suggestions.

I tried removing individual files to see what file is involved, but it wasn't so easy. For example, removing the _.sublime-settings_ will add the box, but adding the file and commenting everything except the _extensions_ out will remove the box, meaning there is no setting there specifying it on or off.

What needs edited to get the box back?

**Comment by nilslindemann** [comment]
> I don't see much point

People who don't see much points.
