### ISSUE TITLE
Too many settings in settings file

### ISSUE THREAD

**Issue by pomeh** [SublimeText-Markdown/MarkdownEditing#209]
While I really like this package, I think there are too many predefined settings in all your `sublime-settings`.
I installed the package to have _in the first place_ better syntax highlighting. That's why for example I don't understand why those settings are defined in [Markdown (Standard).sublime-settings](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/2b065d815bc852b8eca3b549e8e9d6bdf3b46cee/Markdown%20%28Standard%29.sublime-settings):

``` json
{
    "tab_size": 4,
    "translate_tabs_to_spaces": true,
    "trim_trailing_white_space_on_save": false,
    "auto_match_enabled": true,
    "draw_centered": true,
    "word_wrap": true,
    "wrap_width": 80,
    "rulers": [],
    "line_numbers": false,
    "highlight_line": false,
    "line_padding_top": 2,
    "line_padding_bottom": 2,
    "caret_style": "wide",
    "caret_extra_top": 3,
    "caret_extra_bottom": 3,
}
```

I **do not** want my ruler disappear when editing markdown text, I **do not** want line numbers disappear when editing markdown text, I **do want** to use tabs instead of spaces, and **I prefer** definitely wrap lines at 100 instead of 80. You should not change those settings on the behalf of the user, it's not what he expects from the package, at least it's not what I expect. The settings you are defining have **too strong** default values, it mess with my general preferences.

There is already _one_ solution for this problem, or I should say there are **three** solutions:
- use the file `User/Markdown.sublime-settings` to override the settings in `MarkdownEditing/Markdown.sublime-settings`
- use the file `User/Markdown (Standard).sublime-settings` to override the settings in `MarkdownEditing/Markdown (Standard).sublime-settings`
- use the file `User/MultiMarkdown.sublime-settings` to override the settings in `MarkdownEditing/MultiMarkdown.sublime-settings`

So I should copy almost my entire `Preferences.sublime-settings` file **3 times** to retrieve my prefered settings when editing a Markdown file ? That's not what I call a solution, it's only a workaround. A workaround to a problem that should even not exist in the first place.

I may have a working solution to resolve this problem while not changing too many things: use a subkey settings to store the default Sublime Text settings. 

Instead of having the following `Markdown (Standard).sublime-settings` file format:

``` json
{
    "color_scheme": "Packages/MarkdownEditing/MarkdownEditor.tmTheme",

    "tab_size": 4,
    "translate_tabs_to_spaces": true,
    "trim_trailing_white_space_on_save": false,
    "auto_match_enabled": true,

    "mde.match_header_hashes": false,

    "mde.list_indent_bullets": ["*", "-", "+"],
}
```

switch to the following format:

``` json
{
    // package specific settings
    // those settings are a totally non-sense everywhere but in this package
    // so they belong to here without problem
    "mde.match_header_hashes": false,
    "mde.list_indent_bullets": ["*", "-", "+"],

    // since you have a specific color_scheme for Markdown
    // it's ok to let this setting here
    "color_scheme": "Packages/MarkdownEditing/MarkdownEditor.tmTheme",

    // All general Sublime Text preferences related to view settings
    // belong to a "view" subkey. The list of possible options can
    // be found via Preferences -> Settings - Default
    "view": {
        "tab_size": 4,
        "translate_tabs_to_spaces": true,
        "trim_trailing_white_space_on_save": false,
        "auto_match_enabled": true,
    },
}
```

This is [the exact same technique as the package Sublimerge uses](http://www.sublimerge.com/docs/configuration.html#default-settings-view-panels) for it's settings, and it works very well:
- you can keep all your current settings default values,
- you allow the user to override any number of the proposed settings,
- you allow the user to **completely and easily** remove _your_ view settings with the following `User/Markdown.sublime-settings` content:

``` json
{
    "view": {
    },
}
```

Thanks a lot for your answer.

**Comment by adzenith** [comment]
I came here to ask about this same thing. I applied the syntax and thought I would just get nice syntax highlighting. Instead it totally changed around my editor. I would prefer it to do as little as possible visually, like @xguse was saying.

**Comment by usamitysam** [comment]
Almost 2 years old and this issue is still open?  Came here with the same question.

**Comment by fattredd** [comment]
Agreed. It's time to change this. We're going on 4 years now.

**Comment by tobek** [comment]
I agree this plugin should be less opinionated about all of these things, especially the color scheme (though they are sensible defaults for markdown editing that many users would want to use so it makes sense to make them available as an option).

As a workaround, just copy the https://github.com/SublimeText-Markdown/MarkdownEditing/blob/master/Markdown.sublime-settings file into `<sublime-folder>/Packages/MarkdownEditing/Markdown.sublime-settings` and comment out the stuff that you don't want this plugin to override. For example, commenting out the `color_scheme` setting will let you use whatever color scheme you have set for sublime in general (just make sure you also comment out any settings you set in `Packages/User/Markdown.sublime-settings`).

**Comment by deathaxe** [comment]
I think we should remove those settings.

I'd just keep `"trim_trailing_white_space_on_save": false,` because 2 spaces at the end of a line denote a line break. So trimming would break file content.

But all other settings are clearly user preferences. If someone doesn't want line numbers or the text being rendered in center, distraction free mode is the way to go. Also don't see any reason for forcing caret style or line paddings.
