### ISSUE TITLE
Latest ST update breaks syntax highlighting for "Markdown GFM"

### ISSUE THREAD

**Issue by lakenen** [SublimeText-Markdown/MarkdownEditing#210]
Build 3064, OS X (10.9.5). Let me know if you need any other details. Switching to "Markdown" or "MultiMarkdown" brings back highlighting.

**Comment by felixhao28** [comment]
@lakenen @sawshaw Does this issue still persist in the latest version? And how can I reproduce it?

**Comment by lakenen** [comment]
It seems to work for me again now...

**Comment by schmimae** [comment]
I seem to be having the same issue. When using "Markdown" everything works correctly - syntax highlighting, shortcuts and behaviour (e.g. when typing * + ENTER a new item is added). However, when using Markdown GFM, nothing is working except the settings in Markdown.sublime-settings (e.g. changing the theme). There is no syntax highlighting in Sublime (e.g. bold text), and all the other features do not work as well.

Is there any way I can debug this issue?
