### ISSUE TITLE
Reword "Standard Markdown" to "CommonMark"

### ISSUE THREAD

**Issue by AMorgaut** [SublimeText-Markdown/MarkdownEditing#211]
Due to a Markdown syntax author (John Gruber) request, the "Standard Markdown" name has had to be changed to "CommonMark"
http://www.infoq.com/news/2014/09/markdown-commonmark

If "Standard Markdown" in this SublimeText plugin represent direct John Gruber's implementation behaviors mapping, it can be preferable to get direct John's authorization to use the name.

If "Standard Markdown" is meant to represent the [CommonMark](http://commonmark.org/) spec that was "previously known as Standard Markdown", then it would be preferable to update the [README.md](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/master/README.md) file and maybe some files names like the ones of [Markdown (Standard).sublime-settings](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/master/Markdown%20(Standard).sublime-settings) or [Markdown (Standard).tmLanguage](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/master/Markdown%20(Standard).tmLanguage)

This link may help to find out required changes ;-)
https://github.com/SublimeText-Markdown/MarkdownEditing/search?utf8=%E2%9C%93&q=standard

**Comment by maliayas** [comment]
It's the one that comes with Sublime Text. Afaik that's based on Gruber's implementation. Some small changes have been made to it through this package's lifetime.

Thanks for the notice.
