### ISSUE TITLE
Last character disappearing bug when CJK character typing

### ISSUE THREAD

**Issue by doortts** [SublimeText-Markdown/MarkdownEditing#213]
First of all, I really appreciate your work, MarkdownEditing plug-in. : )

But we (CJK people - Chinese, Japanese, Korean) have a trouble using it, because of last character missing bug.

When I type korean and press the ENTER key, then last character is disappeared.

See the below link..
https://space.zeo.net/g/la5p/UBARY5ONHBSKVOG5XSJCY2K2ZJ3OI6MA

If I knew python, then I'll try to fix it. but I don't know.
Anyone who knows the python, please fix this.
You will be a hero of many asians..

**Comment by felixhao28** [comment]
I am going to close this issue for now. If you face the same problem, you are welcomed to comment below.
