### ISSUE TITLE
Raw javascript function breaks below syntax highlighting 

### ISSUE THREAD

**Issue by tylerhartley** [SublimeText-Markdown/MarkdownEditing#214]
All it takes is putting in any javascript function like so:

```
## Header 1

<script>
    $(document).ready(function(){
        $('#ex1').zoom();
        $('#ex2').zoom();
    });
</script>

## header 2

[some link](http://link.link)

```

And anything below that javascript function no longer shows syntax highlighting (i.e. the Header 2 and embedded link in the example).

Running SublimeText3 build 3065.

**Comment by Viomi** [comment]
These errors (including sublimetext refusing to autocomplete tags and whatnot) that happen after the <script> tag exist in vanilla SublimeText.
