### ISSUE TITLE
Incorrect Code Area

### ISSUE THREAD

**Issue by j5shi** [SublimeText-Markdown/MarkdownEditing#215]
Hi, please try to put below code snippet to a markdown file and you will find everything following this code section will be considered as a code snippet, what I mean is not error in html, but incorrect background color in sublime text.

```c
# ifndef __cplusplus

```
#error A C++ compiler is required!
```
# endif

```

# this should be a header, however, it's background color in ST is incorrect

**Comment by felixhao28** [comment]
Upcoming fix described in #484. Closing it for now. Feel free to reopen it if that solution is not sufficient.
