### ISSUE TITLE
Syntax highlighting at ST start

### ISSUE THREAD

**Issue by remitbri** [SublimeText-Markdown/MarkdownEditing#216]
I'm using ST 3066 on OSX 10.9.5

If when ST starts with markdown files automatically reopened, they get the default ST color scheme, even if I try then to fiddle with the file type ("set syntax to…" command).

If I open a markdown file, _then_ it gets the proper MarkdownEditing color scheme.

**Comment by felixhao28** [comment]
I confirm this problem. Installing the plugin with package control while a markdown file is open will cause this to happen.

**Comment by deathaxe** [comment]
Color schemes are defined in syntax specific settings. Maybe ST had issues loading them.

Reassigning syntax of open files after installation or before uninstallation can be handled in bootstrapper.
