### ISSUE TITLE
Paste as link keyboard shortcut broken

### ISSUE THREAD

**Issue by tkaufmann** [SublimeText-Markdown/MarkdownEditing#219]
Collides with Sublime 3's "Paste from history" now. I'm on 2.0.9 with ST3.

**Comment by felixhao28** [comment]
The proper way to use "paste as link":

![download](https://cloud.githubusercontent.com/assets/2417391/6386000/3314c768-bdad-11e4-8199-20e1150dbf67.gif)

**Comment by tkaufmann** [comment]
Strange thing. Part of this must have been a collision with another software I use. But the GIF seems to be wrong, it's Alt+Super+V, not Ctrl+Super+V.
