### ISSUE TITLE
All files with MD syntax highlighting with MarkdownEditing

### ISSUE THREAD

**Issue by dvapelnik** [SublimeText-Markdown/MarkdownEditing#222]
Hi!
I'm using MarkdownEditing SublimeText3 plugin but I feel uncomfortable when simple *.txt file with syntax similar with MD ("#" as comments, "====" as block separator) is highlighting with plugin.
Can I specify that MarkdownEditing plugin will highlighting only *.md-files?
It's very uncomfortable

**Comment by felixhao28** [comment]
Adding
```
"extensions":
[
	"md",
	//and other markdown related files like "mdown"
],
```
to your user settings will do the trick.

**Comment by dvapelnik** [comment]
@felixhao28 can you show simple example of user settings config with this section?

**Comment by felixhao28** [comment]
@dvapelnik Sure, this is my user config file:
```
{
	"extensions":
	[
		"md",
		"mdown"
	],
}
```

**Comment by dvapelnik** [comment]
@felixhao28 here is my config (Preferences -> Settings - User):
```
{
	"color_scheme": "Packages/Color Scheme - Default/Mac Classic.tmTheme",
	"font_size": 11,
	"ignored_packages":
	[
		"Vintage",
		"Markdown"
	],
	"translate_tabs_to_spaces": true,
	"update_check": false,
    "extensions":
    [
        "md",
        "mdown"
    ]
}
```
I have relaunch SublimeText3 and reopen simple *.txt file but it shown like marked. Look here
![laptop_20150128__15 12 50](https://cloud.githubusercontent.com/assets/1562244/5938078/3816c95a-a700-11e4-98d3-6581473e6d64.png)
![laptop_20150128__15 13 53](https://cloud.githubusercontent.com/assets/1562244/5938093/555121e6-a700-11e4-86fe-74fb0bfc2011.png)

**Comment by felixhao28** [comment]
Well, when I say user config file I actually mean `Preferences -> Package Settings -> Markdown Editing -> <the markdown flavor you use> Settings - User`, not the global user configs.
