### ISSUE TITLE
Could you make a version for Atom?

### ISSUE THREAD

**Issue by iclanzan** [SublimeText-Markdown/MarkdownEditing#224]
I really love this plugin and would love to be able to see it available for Atom.

**Comment by maliayas** [comment]
Unfortunately there is no plan for that at the moment. There have been several requests for this but there is no time to invest on it (unless somebody is volunteer for this). Thanks.

**Comment by stefanmaric** [comment]
One year after, does anyone know a similar plugin for Atom? I can't believe this is still missing in Atom.
