### ISSUE TITLE
Bold-Italic formatting is not formatted.

### ISSUE THREAD

**Issue by EdenSG** [SublimeText-Markdown/MarkdownEditing#225]
Markdown allows for *italic* (`*italic*`), **bold** (`**bold**`), and ***bold-italic*** (`***bold-italic***`) text. Single and double asterisks are displayed correctly, but bold-italic text is shown as only italic. As far as I can tell there is nothing in the `.tmtheme` for bold-italic text, it just shows as italic. 

I'm not at all familiar with ST themes, so sorry that I don't know how to add this functionality myself!

Thanks!

**Comment by felixhao28** [comment]
bold_italic style will be added in v2.1.1. Thanks for reporting the bug.

**Comment by EdenSG** [comment]
Awesome, thanks!
