### ISSUE TITLE
Cannot turn off "mde.keep_centered" (vertical cursor centering)

### ISSUE THREAD

**Issue by pruppert** [SublimeText-Markdown/MarkdownEditing#228]
I do not want to have the current line vertically-centered when editing. I have set 

```
"mde.keep_centered": false,
```

in all of the settings files (GFM, Standard, Multimarkdown) for both normal and distraction free mode, but the editor still vertically centers my line when editing. Is there somewhere else where this is set? How can I turn off vertical cursor centering?

Thanks.

**Comment by felixhao28** [comment]
You need to make sure `"mde.keep_centered": true` does not appear in all the following config files:

1. Settings-Default
1. Settings-User
1. Settings-More -> Syntax Specific-User
1. Settings-More -> Distraction Free-User
1. Package Settings -> Markdown Editing -> <Your flavour> Settings-Default
1. Package Settings -> Markdown Editing -> <Your flavour> Settings-User

**Comment by deathaxe** [comment]
Things should get easier with 3.0.0 as all settings are stored in _Preferences.sublime-settings_.
