### ISSUE TITLE
indenting and outdenting selected list items replaces list character throughout line, not just at beginning

### ISSUE THREAD

**Issue by jonathanmorgan** [SublimeText-Markdown/MarkdownEditing#233]
Hello,

If you select a set of list items and use tab to indent or shift-tab to outdent them, after the latest release, not only is the character in front of each line that indicates it is a list item changed, all instances of the list delimiter throughout the line are changed.

For example, if you select multiple items that are in a list (like the following):

        - file: normalize_data-step_1-create_tweets.py
        - reads raw table, makes a tweet row for each raw tweet row.

And then press shift-tab to outdent them one tab, you get the following:

    * file: normalize_data*step_1*create_tweets.py
    * reads raw table, makes a tweet row for each raw tweet row.

The dashes at the beginning of the line are changed to asterisks, as it behaved before.  But, the dashes inside the line are changed to asterisks, as well.

This happens throughout the selection, indent or outdent.

**Comment by felixhao28** [comment]
I confirmed this problem and committed a temporary fix in my repo. I will send a pr after the fix has been fully tested.
