### ISSUE TITLE
Highlighter issue for `dd` command

### ISSUE THREAD

**Issue by leesei** [SublimeText-Markdown/MarkdownEditing#237]
If I add `sh` syntax to this:
```
dd if=[iso] of=[usb device] bs=4M
```
The code block cannot close because of the `if`.

**Comment by felixhao28** [comment]
It is a bug in ST3. The `if` breaks backtick scope and causes `normaltext` to render differently.
![image](https://cloud.githubusercontent.com/assets/2417391/6411630/57d4787e-beb5-11e4-9488-af0ab7eb0885.png)

**Comment by leesei** [comment]
I see, I'll port this issue to ST3's issue list.
I'll close this one after porting.

**Comment by maliayas** [comment]
Closing due to duplicate.
