### ISSUE TITLE
Code block open with backtick should consume whole line

### ISSUE THREAD

**Issue by leesei** [SublimeText-Markdown/MarkdownEditing#238]
I'm editing some md files for [Hexo](http://hexo.io), whose highlighter supports extra parameters (besides specifying the language).

However MarkdownEditing won't highlight this backtick code block start maker:
<pre>
```java param1 param2
```
</pre>
The line after the supposedly code block end marker  is highlighted as code.

**Comment by felixhao28** [comment]
Extra parameters are not supported by GFM, vanilla Markdown or Multimarkdown, the three flavors of Markdown syntax we currently support. So you are actually asking for the support for "Hexo Flavored Markdown". When HFM users become as many as the users of the other three, we will consider it. But before that, it is best to put HFM syntax file in an individual ST3 plugin.
