### ISSUE TITLE
Custom color scheme

### ISSUE THREAD

**Issue by emilmilanov** [SublimeText-Markdown/MarkdownEditing#242]
Is it possible that people create custom colors scheme for markdown editing?

**Comment by felixhao28** [comment]
Yes, see #173. You can take a look at existing .tmTheme files to see which scopes are used. Scope Hunter plugin can be quite useful during the development.

**Comment by milanoxx** [comment]
Thanks. I'll update you when I do something about this.

**Comment by Haroenv** [comment]
@felixhao28 Is there no way you could refer to the default colour scheme for the colours?

**Comment by felixhao28** [comment]
I think only one color scheme can be used at one time. I maybe wrong but I have never seen two color schemes working together.
