### ISSUE TITLE
Space after shortcut reference link incorrectly marked as error

### ISSUE THREAD

**Issue by horsedrowner** [SublimeText-Markdown/MarkdownEditing#243]
See the following example:

```
See this [link] (also, ...)

[link]: http//localhost/
```

which is displayed as follows:

![screenshot of above example in ST3](http://s.horsedrowner.net/2015/03/1426342713-268x89.png)

The space between `[link]` and `(also, ...)` is marked red. I don't know how the different Markdown renderers handle it, but at least [CommonMark.js](http://spec.commonmark.org/dingus/) correctly renders it as an inline link to http://localhost/, followed by the text `(also, ...)`.  GitHub renders it as a relative link to `/also, ...` as if the space wasn't there in the first place..

Either way, I don't believe that space should be marked as an error, whether it is considered a shortcut reference link with text, or simply ignored whitespace.

See: http://spec.commonmark.org/0.18/#example-413 and http://spec.commonmark.org/0.18/#shortcut-reference-link

**Comment by maliayas** [comment]
Maybe it's more helpful this way. I'm not sure.

**Comment by felixhao28** [comment]
@maliayas Then it should be a lint feature, and separated from main syntax highlighting.

**Comment by maliayas** [comment]
@felixhao28 OK. Now that we have linting, we can move such functionality to the linting.
