### ISSUE TITLE
*italics* and _italics_ work but the bold counterparts do not. ST3

### ISSUE THREAD

**Issue by StJohn3D** [SublimeText-Markdown/MarkdownEditing#244]
Any ideas?

**Comment by felixhao28** [comment]
Can you show us a screenshot?

**Comment by StJohn3D** [comment]
![screenshot 2015-03-16 08 36 49](https://cloud.githubusercontent.com/assets/7581439/6666129/b470dfd2-cbb7-11e4-9de0-5593e7bb1585.png)

**Comment by roulette6** [comment]
![screen shot 2015-03-16 at 6 39 33 pm](https://cloud.githubusercontent.com/assets/4197563/6678022/d9ed458a-cc0b-11e4-91ac-4652dbeaaa9e.png)
Same idea. The package works well on my work PC but not on my iMac. Both machines run ST3, though I'm not sure if both are using the same build.

**Comment by felixhao28** [comment]
I don't have a mac at hand to test. So it is just a guess: maybe you accidentally disabled bold with `no_bold` in `font_options` somewhere in your settings?

**Comment by roulette6** [comment]
@felixhao28 Thanks. That didn't fix it, but you made me consider that it was the font. I was using Monaco as the font face and I guess it doesn't have a bold version. If @StJohn3D is also specifying a different font face, he should comment out that line and restart ST3 to see if the issue goes away. I had to restart to see the change.

**Comment by StJohn3D** [comment]
Thanks @roulette6, that was it. I was using the 'Andale Mono' font which apparently doesn't have a bold version.
