### ISSUE TITLE
Selecting Text and typing a backstick won't does not work as expected

### ISSUE THREAD

**Issue by osopolar** [SublimeText-Markdown/MarkdownEditing#245]
Hi, for the record: I just figured out that on german keybords if you select text and want to surround it with backtikcs you need to press `crtl+shift+backstick` (only the backstick-key will replace the selected text with the backstick).

**Comment by deathaxe** [comment]
Backticks are entered via `shift+´` on german keyboard. Without it an apostroph is inserted. That's how it works on german keyboard.

**Comment by osopolar** [comment]
Did you try it, selecting text and hit `shift + \``? If I do that the selected text gets replaced by the backtick. If I use `crtl + shift + backstick` instead, the selection gets surrounded by backtick, which is the expected behavior for example select text and type `(` the selection gets surrounded by parentheses. But maybe I just have configured something wrong/differently, so YMMV.
