### ISSUE TITLE
Problems with text and urls inside itallic (bold) markup

### ISSUE THREAD

**Issue by osopolar** [SublimeText-Markdown/MarkdownEditing#246]
URLs inside itallic or bold markup aren't highlighted properly. It looks like that:

![screen shot 2015-03-22 at 12 12 40](https://cloud.githubusercontent.com/assets/1523215/6769904/c88d9602-d08c-11e4-8a1f-4aaaa845567e.png)

Adding a space at the beginning or after the link result's in correct highlighting, but the space shouldn't be necessary.

![screen shot 2015-03-22 at 12 10 00](https://cloud.githubusercontent.com/assets/1523215/6769902/9c6cb990-d08c-11e4-947c-2882dfaba19a.png)

**Comment by maliayas** [comment]
I guess this is a very complicated issue. Because we can not know it the final underscore belongs to the URL or the italic.

I think this is a standards issue rather than plugin issue. You have to either use a space as you say or put the URL in `<>` as the standard markdown suggests.

**Comment by osopolar** [comment]
Its also working, if you put the space at the beginning like `_ see http://example.com_`, therefore I guess its a tiny bug in the regex. GFM itself knows where the underscore belongs to, so I guess it could be possible.

The Url cearly ends with a whitespace or newline character (anything else?). It also could end if there are one or more non alphanumeric characters followed by whitespace or newline (or whatever currently ends the url expression) - these non alphanumeric characters at the end of the url should not be part of the url anymore.

Anyway, thanks for pointing out the use of `<>`.

**Comment by ttscoff** [comment]
A space following a _ will not create emphasis in 90% of Markdown 
processors.

**Comment by osopolar** [comment]
Ah, OK, I understand. That's why the code section after the emphasis with the url part was working as expected ;)

**Comment by felixhao28** [comment]
Nevertheless, the code block should not be affected.
