### ISSUE TITLE
vertical centering for *.Rmd will not go away

### ISSUE THREAD

**Issue by maxheld83** [SublimeText-Markdown/MarkdownEditing#247]
I have everywhere

```
"mde.keep_centered": false,
```

and yet, for my *.Rmd files, when I select `knitr (Markdown)` as a syntax (from [knitr](https://github.com/andrewheiss/SublimeKnitr/issues) package, the view will always vertically center.

My hunch is that this has something to do with MarkdownEditing (as opposed to the knitr) package, because whenever I uninstall MarkdownEditing, the problem goes away.

Again, problem does *not* exist for normal `*.md` files.

The re-centering is very disorienting, if anyone has a hunch how to solve this, that would be great.

**Comment by maxheld83** [comment]
ok, that was pretty dumb of me: I just added

```
"mde.keep_centered": false,
```

to syntax-specific settings - user, and the problem went away.

Still it'd be nice if this somehow did not default to vertical centering

**Comment by felixhao28** [comment]
In your case, I believe you have left a `"mde.keep_centered": true` somewhere in your settings. Vertical centering is NOT turned on by default. It must be turned on through setting `mde.keep_centered` to something other than false.

**Comment by maxheld83** [comment]
thanks @felixhao28 – anyhow, I fixed it by adding the above to the syntax specific settings
