### ISSUE TITLE
more "paste as link" in command palette

### ISSUE THREAD

**Issue by felixhao28** [SublimeText-Markdown/MarkdownEditing#256]
As suggested by @maliayas 

- [x] Pastes the contents of the clipboard as an inline link on selected text.
       Command Palette -> Paste as Inline Link/Image with url in clipboard

- [x] Inserts a standard inline link.
       Command Palette -> Paste as Inline Link without url in clipboard

- [x] Inserts an inline image.
       Command Palette -> Paste as Inline Image without url in clipboard

- [x] Inserts a footnote and jump to its definition. If your cursor is in a definition, it will jump back to the marker.
       Command Palette -> Magic Footnotes

- [x] Locates footnote markers without definitions and inserts their markers for the definition.
       Command Palette -> Gather Missing Footnotes

closes #107

**Comment by felixhao28** [comment]
Here are the features we currently have regarding links/inline links/footnotes (for better reading, "anchor" is the upper part of these links, e.g. `[text][link]`, `[text](inline_link)` and `[text][^footnote]`, and "reference" is the lower part, e.g. `[link]: link_url` and ` [^footnote]: footnote_content`):

| Feature\Anchor Type | Links(Images)                                                                                                                                               | Inline Links(Images)                                                         | Footnotes                                                          |
| ----------------    | ----------                                                                                                                                                  | --------------------                                                         | ----------                                                         |
| Jump                | :x:                                                                                                                                                         | :x:                                                                          | :o: (Included in Magic Footnotes command)                          |
| Insert New          | :o: (Included in Paste As References command, when clipboard content is not URL, and Insert Numbered Reference command when using number as reference name) | :o: (Included in Paste As References command, when clipboard content is URL) | :o: (Included in Magic Footnotes command)                          |
| Paste as XXX        | :o:                                                                                                                                                         | :o:                                                                          | :x:                                                                |
| Delete              | :x:                                                                                                                                                         | :x:                                                                          | :x:                                                                |
| Organize            | :question: (Partially implemented as Gather Missing Links command)                                                                                          | :question: (Partially implemented as Gather Missing Links command)           | :question: (Partially implemented as Gather Missing Links command) |

* ___Jump___ is the ability to change cursor location from a definition to the related anchor(s) and the other way around.
* ___Insert New___ is the ability to help users to create new anchor(s) when the content/link is not determined yet.
* ___Paste as XXX___ is the ability to create new anchor(s) when the content/link is already copied to clipboard
* ___Delete___ is the ability to remove reference(s) and related anchor(s)
* ___Organize___ is the ability to remove abundant references and to create missing ones.

The way that these features are very similar to each other and all the commands and shortcuts is confusing. That leads me to find a general feature that supports all the three kinds. And links, inline links, footnotes all serve the shared purpose of providing additional information and are mutually exclusize to some extent. So, here is what I suggest:

* We remove all these current features and reform them in the following way
* ___Jump Reference___ jumps cursor between definition and the related anchor
    - If multiple cursors exist, this applies to each one of them.
* ___New <AnchorType\> Reference___ create a new anchor with default/auto-generated content
    - If appropriate content is availble in clipboard, then use that instead of default/auto-gen content.
    - If multiple cursors exist, create an anchor for each one of them but only create one reference.
* ___Delete Reference___ delete selected anchor(s) and related references
    - If cursor is on an anchor, delete it first then check if the reference is used anywhere else. If not, delete the reference as well.
    - If cursor is on a reference, delete it and all related anchors.
    - If multiple cursors exist, this applies to each one of them.
* ___Organize Reference___ removes unused, duplicated references and create empty references that relate to all orphan anchors. It also warns any references with the same name but different content.

Given all five anchor types, we then will have 8 new commands replacing and expanding existing 9.

@maliayas I will be working on this for a while. Please share your opinion with me.

**Comment by maliayas** [comment]
I love the idea. They are very confusing at the moment.

As a note, dealing with multicursors for "Jump Reference" command may not be necessary as there may be weird cases.
