### ISSUE TITLE
Not available via package control?

### ISSUE THREAD

**Issue by rowe-morehouse** [SublimeText-Markdown/MarkdownEditing#257]
Package Control did not see it for me. Had to git clone for manual install. 

Sublime Text 3
Stable Channel, Build 3083
OSX 10.10.2

May be an issue for others as well.

**Comment by yrammos** [comment]
Yes, it doesn't show up on my end either.

**Comment by felixhao28** [comment]
Maybe you have it already installed? Try package:control remove package and see if MarkdownEditing shows up.

**Comment by yrammos** [comment]
Duh! False alarm indeed, terribly sorry.

**Comment by rowe-morehouse** [comment]
Yes, I made the same mistake. Thanks for the correction, @felixhao28
