### ISSUE TITLE
Ability to turn off autoscrolling

### ISSUE THREAD

**Issue by Suor** [SublimeText-Markdown/MarkdownEditing#259]
This could be very annoying, a setting to turn it off will be very welcome.

Also I feel like this feature has nothing to do with editing markdown in particular, so it could be even better as separate plugin.

**Comment by maliayas** [comment]
It is disabled by default for normal mode and enabled by default for distraction free mode which _requires a separate plugin_ to be able to run. Are you sure your issue is caused by this plugin?

Also please make sure you didn't override `mde.keep_centered` setting to `true`

**Comment by Suor** [comment]
Disabling Markdown Editing plugin switched of autoscrolling, so yes it is causing it.

I think I know why this happens. You are using fragile code to test for `mde.keep_centered` setting:
```python
if view.settings().get("mde.keep_centered") is False:
    return False
```
And I am using "Markdown Extended" mode, for which you didn't specify that setting. The better way of checking it would be:
```python
if not view.settings().get("mde.keep_centered"):
    return False
```

**Comment by maliayas** [comment]
@felixhao28 We finally found the reason for this rare bug. It was happening to people who didn't have those settings at all or didn't update them [when I changed their names](https://github.com/SublimeText-Markdown/MarkdownEditing/commit/0a0bcf6b78e630ca81b4a3401edf3a9b90e7ac00#diff-800b252573cfcc89c11026bcc8498c13R46)

@Suor noticed this and fixed it.

**Comment by felixhao28** [comment]
@maliayas So package control does not update default configurations? Good to know.
