### ISSUE TITLE
Italics not slanted in ST3

### ISSUE THREAD

**Issue by Magnus-G** [SublimeText-Markdown/MarkdownEditing#264]
Hi, 

Thank you for creating this! It's really great. 
However in ST3 I can't get the italic sections to look slanted. They just look a bit darker. How can I make them appear slanted like they do in ST2?

ST2:

![image](https://cloud.githubusercontent.com/assets/2095625/7208069/f8f101ba-e50b-11e4-89da-100184726530.png)

ST3:

![image](https://cloud.githubusercontent.com/assets/2095625/7208046/cd534e82-e50b-11e4-8cf2-60b192c56572.png)

**Comment by felixhao28** [comment]
Did you disable italics somewhere in your settings? What font are you using? Does it support italics?

**Comment by felixhao28** [comment]
@Magnus-G is this still troubling you? If not, we can close the issue then.

**Comment by Magnus-G** [comment]
@felixhao28 Hey! Sorry I never got back to you. This works fine now. Thanks
