### ISSUE TITLE
Large gutter/margin when editing markdown files 

### ISSUE THREAD

**Issue by nikmartin** [SublimeText-Markdown/MarkdownEditing#266]
I installed MarkdownEditing in ST3 Build 3083, and when I open a markdown file, I get a huge left margin/gutter inside the editing window:
![screenshot from 2015-04-20 16 44 59](https://cloud.githubusercontent.com/assets/1226452/7241208/df15b5ce-e77c-11e4-9a63-7c36992cf0f4.png)

I'm not sure if this is a configuration issue, or a package conflict, but the packages I have loaded that affect the sidebar are GitGutter and SideBar. Could this be the issue?

**Comment by felixhao28** [comment]
How about setting "draw_centered" to false? It is true by default.

**Comment by nikmartin** [comment]
that did it :)
