### ISSUE TITLE
Switch bullet list to numbered list, the numbered list all start from "1", not "1", "2", "3"

### ISSUE THREAD

**Issue by zgjie** [SublimeText-Markdown/MarkdownEditing#269]
> Switch List Bullet Type

> Switches the highlighted list between numbered and bulleted style.

Good to see this feature. But now switching bullet list to numbered list, the numbered list all start from "1", not "1", "2", "3". 

I also expect a way to quickly update the number of the list to "1", "2", "3" from any unordered number. Although I know the exported html is same.

Thanks!

**Comment by ttscoff** [comment]
I've lost the source of [this perl 
script](https://gist.github.com/f51dc2aec536eb876939), but it's what I 
use for my own list cleanup (I believe it was originally by @fletcher. 
I'm not good enough at Python to quickly port it to a plugin, though.

-Brett

**Comment by fletcher** [comment]
Yes.  That is a non-attributed copy of my script.

:)


F-

On 4/21/15 2:23 PM, Brett Terpstra wrote:
> I've lost the source of [this perl
> script](https://gist.github.com/f51dc2aec536eb876939), but it's what I
> use for my own list cleanup (I believe it was originally by @fletcher.
> I'm not good enough at Python to quickly port it to a plugin, though.
>
> -Brett
>
>
>
>
>
> On 21 Apr 2015, at 11:01, zgjie wrote:
>
>  >> Switch List Bullet Type
>  >
>  >> Switches the highlighted list between numbered and bulleted style.
>  >
>  > Good to see this feature. But now switching bullet list to numbered
>  > list, the numbered list all start from "1", not "1", "2", "3".
>  >
>  > I also expect a way to quick update the number of the list to "1",
>  > "2", "3" from any not ordered number. Although I know the exported
>  > html is same.
>  >
>  > Thanks!
>  >
>  > ---
>  > Reply to this email directly or view it on GitHub:
>  > https://github.com/SublimeText-Markdown/MarkdownEditing/issues/269
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SublimeText-Markdown/MarkdownEditing/issues/269#issuecomment-94895431>.
>

-- 
Fletcher T. Penney
fletcher@fletcherpenney.net

**Comment by ttscoff** [comment]
Now it's loosely attributed :)

**Comment by felixhao28** [comment]
There are two flavors of making numbered lists. One is to always use "1." and another one is to use an ascending number sequence (which is more natural but requires maintenance). Currently it is a bit messy, given that linter accepts both (by default and can be configured to just accept either), hitting "enter" always creates ordered number list and switching list type always creates "1." lists. There should be one setting to control them all.

**Comment by felixhao28** [comment]
Also I noticed that it dumps the selection to the console. I will fix that later.

**Comment by Pandahisham** [comment]
@zgjie fornow you can use https://github.com/duydao/Text-Pastry this plugin from incremental listing .
@felixhao28 have look into the source please

**Comment by felixhao28** [comment]
@Pandahisham you can set `mde.auto_increment_ordered_list_number` to True to enable auto-incrementing number.
