### ISSUE TITLE
Keybinding Errors  

### ISSUE THREAD

**Issue by rdsalemi** [SublimeText-Markdown/MarkdownEditing#270]
I am seeing the following keybinding errors:
       
     Error trying to parse file: Trailing comma before closing bracket in ~/Library/Application Support/Sublime Text 2/Packages/MarkdownEditing/Default (OSX).sublime-keymap:73:9

     Error trying to parse file: Trailing comma before closing bracket in ~/Library/Application Support/Sublime Text 2/Packages/MarkdownEditing/Default (OSX).sublime-keymap:73:9

**Comment by rdsalemi** [comment]
Also Line 88,

**Comment by maliayas** [comment]
fixed in the new version. see https://github.com/SublimeText-Markdown/MarkdownEditing/pull/267
