### ISSUE TITLE
Latest version produces invalid setting file (OSX)

### ISSUE THREAD

**Issue by dacook** [SublimeText-Markdown/MarkdownEditing#272]
After automatic upgrade, when starting Sublime 2 I get:
`Error trying to parse file: Trailing comma before closing bracket in ~/Library/Application Support/Sublime Text 2/Packages/MarkdownEditing/Default (OSX).sublime-keymap:73:9`

Workaround: After fixing the two offending commas, it's ok.
* line 72 col 107
* line 87 col 107

**Comment by imyelo** [comment]
+1 in windows

**Comment by felixhao28** [comment]
Duplicated #267 #268 

Try update again. It should be fixed by now.
