### ISSUE TITLE
Behaviour of 4-space indented text

### ISSUE THREAD

**Issue by yoonghm** [SublimeText-Markdown/MarkdownEditing#276]
See the sample below:

+ __Markdown__

    This line is indented. - Okay.
  
    This line is also indented - Okay
  
```
#include <stdio.h>
```

    However, this line is not but become code. - Not okay.

I suggest should use 4 spaces for indented text instead of code.

**Comment by felixhao28** [comment]
The first two lines are indented because it is under a list. By default, indenting by 4 spaces means preformatted code block.

**Comment by felixhao28** [comment]
This "issue" seems to be related to Markdown syntax only, not to MarkdownEditing plugin. So I am closing this issue. MarkdownEditing's behaviors should remain consistent with most Markdown parsers.
