### ISSUE TITLE
Automatic title slurps up whole paragraphs in documents without headers.

### ISSUE THREAD

**Issue by phyllisstein** [SublimeText-Markdown/MarkdownEditing#277]
Hey there! I've noticed a little glitch with MarkdownEditing's automatic titling feature: in Markdown documents that have neither filenames nor headers, it'll set the Sublime tag name to the contents of entire paragraphs at a time:

![screen shot](https://cloud.githubusercontent.com/assets/2207980/7728924/e40a4dae-fedf-11e4-904d-4103580bd61a.png)

I'm going to endeavor to take a look at the regex and submit a pull request, but I thought it might be worth pointing the issue out to contributors already familiar with `DecideTitle`'s internals. Thanks in advance for looking into it!

**Comment by felixhao28** [comment]
Thanks for pointing it out. The implementation of "decide title" function is well contained in decide_title.py. It does not require you to read the regex.

When you contribute, please push to v2.1.4 branch. And don't forget to put your name in the change log.

**Comment by felixhao28** [comment]
After reviewing this issue, I find that MDE v2.1.4 does not put the whole paragraph in the title. Closing it.
