### ISSUE TITLE
wiki markup lists

### ISSUE THREAD

**Issue by flowlikeh2o** [SublimeText-Markdown/MarkdownEditing#278]
Hi,

I was wondering how it might be possible to use this package, or at least the list functionality, with support for mediawiki markup. I tried editing the default settings but have not had luck so far.

Thanks

**Comment by felixhao28** [comment]
how about this: https://github.com/tosher/Mediawiker

**Comment by flowlikeh2o** [comment]
Thanks for the suggestion, I currently use that package and it works great but unfortunately does not have the specific feature I'm looking for.

________________________________

**Comment by felixhao28** [comment]
Well mediawiki seems to use a heavily customized markdown syntax, and it is not supported by markdown editing at the moment. I think it might be a good idea to send your feature request to them and see what they can do.
