### ISSUE TITLE
Cursor dislocation

### ISSUE THREAD

**Issue by HeartUnchange** [SublimeText-Markdown/MarkdownEditing#279]
While I use this plugin to write some document which contains Chinese characters,it happened.The  
cursor didnot appear at right loction.

And it is strange.If the line did not start with "#",everything looks normaly.Just look like this:

![ja](https://cloud.githubusercontent.com/assets/8402502/7787806/818f3480-0251-11e5-95fc-5f32ee779e02.PNG)

I use Sublime Text 2 on windows7 64bits.

**Comment by felixhao28** [comment]
duplicated #213

**Comment by felixhao28** [comment]
duplicated #187
