### ISSUE TITLE
fails to load with sublimetext dev 3087

### ISSUE THREAD

**Issue by joeybaker** [SublimeText-Markdown/MarkdownEditing#280]
With build 3087 of sublime text, I get the following error on startup:

```
Error loading syntax file "Packages/MarkdownEditing/Markdown.tmLanguage": Unable to read Packages/CSS/CSS.sublime-syntax
```

**Comment by felixhao28** [comment]
Are you using some third-party packages to maintain CSS syntax? Build 3087 seems to include many new syntax format files (.sublime-syntax) to replace old ones (.tmLanguage).

**Comment by joeybaker** [comment]
I am. I've got the CSS3 package installed. I'm not totally clear on why that matters, since this error doesn't reference it, but I'll try removing and let you know.

**Comment by joeybaker** [comment]
I tried disabling the CSS3 package, but have the same error. (now on build 3088)

**Comment by felixhao28** [comment]
If you open a normal .css file, will the file be correctly highlighted? If not, you default css package must be somehow corrupted/disabled. I suggest you repair it (if you know how) or reinstall ST3.

**Comment by joeybaker** [comment]
doh! Thanks! That gave me a clue … for some reason I had marked the css package as disabled. re-enabling it fixed the problem. Thanks!
