### ISSUE TITLE
Adding #! in the first line of code will number the code

### ISSUE THREAD

**Issue by yoonghm** [SublimeText-Markdown/MarkdownEditing#281]
Adding __#!__ in the first line of code markdown will force the code to be number. For example

```
#!/bin/bash
echo "Hello World"
```

will produce
```
1    #!/bin/bash
2    echo "Hello World"
```

However, this does not
```
# The magic code will not work anymore
#!/bin/bash
echo "Hello World"
```

**Comment by felixhao28** [comment]
I don't understand your question. Are you expecting

    ```bash
    #!/bin/bash
    echo "Hello World"
    ```

to produce

 ```bash
1    #!/bin/bash
2    echo "Hello World"
```

?

**Comment by yoonghm** [comment]
No. The #! tells shell the program that supposed to parse the following code. However, markdown here create line numbering.  I think if ''' is used, all markdown format shall  ot be in force.

**Comment by felixhao28** [comment]
Shebang is a language feature of scripts in unix-like os. As long as you surround it in a code block, it should not affect how markdown parses your document. And I don't think markdown automatically add line numbers in produced html for you.

Can you be more specific on what situation you are currently at and what results you are expecting and what operations you have done?

**Comment by yoonghm** [comment]
![issue_281_1](https://cloud.githubusercontent.com/assets/4215991/8106739/a1640ece-1076-11e5-8b12-2e0ed77d3acb.jpg)

Here is the output in the browser.

![issue_281_2](https://cloud.githubusercontent.com/assets/4215991/8106740/a1647b34-1076-11e5-8930-19b49782c861.jpg)

**Comment by felixhao28** [comment]
I see. It seems to be more related to your markdown renderer than MarkdowngEditing package. MarkdownEditing only offers a syntax highlight and some handy shortcuts/snippets for SublimeText 3.
