### ISSUE TITLE
Shortcut for code snippets like these: ``

### ISSUE THREAD

**Issue by jonathan-s** [SublimeText-Markdown/MarkdownEditing#282]
Just like there is a shortcut for bold and italic it would be nice with a shortcut for code snippets too.

**Comment by felixhao28** [comment]
@jonathan-s , when I check it, MDE already contains a shortcut for code snippets backtick surrounding. First you select some text then you type `.

**Comment by jonathan-s** [comment]
Thanks, I missed that when I read the keyboard layout.
