### ISSUE TITLE
Code block parameters break syntax highlighting

### ISSUE THREAD

**Issue by sman591** [SublimeText-Markdown/MarkdownEditing#283]
When using parameters with language-specific code blocks, MarkdownEditing's syntax highlighting fails.

Incorrect:
![screen shot 2015-06-08 at 12 04 34 pm](https://cloud.githubusercontent.com/assets/1441807/8039289/a8352500-0dd6-11e5-8b2c-14a4500ef689.png)

Correct (missing parameters):
![screen shot 2015-06-08 at 12 06 04 pm](https://cloud.githubusercontent.com/assets/1441807/8039304/c5186ba0-0dd6-11e5-8a18-9111ba690062.png)

It appears to break at the presence of any special/non-alphanumeric character on the first line.

**Comment by felixhao28** [comment]
Can specify which flavor of markdown you are using? Code blocks should not support additional parameters for both vanilla Markdown and GFM.

**Comment by ttscoff** [comment]
Yeah, I've never seen that format for additional parameters either. Markdown Extra, Python Markdown2, and Kramdown all have syntaxes for line numbers and other stuff, but haven't seen this. In my app Marked, which tries to normalize a variety of flavors, I just ignore anything after the standard lang identifier formats, as they don't have any effect on the internal highlighter.

**Comment by sman591** [comment]
It's a formatting option in [Rouge](https://github.com/jneen/rouge/), and [redcarpet](https://github.com/vmg/redcarpet) parses it. Was found here: https://github.com/jneen/rouge/issues/187

However, regardless of whether or not parameters are supported, most online parsers I tried, including GitHub's editor, just ignored them and parsed the block correctly. Would it not be possible to do the same for this?

**Comment by maliayas** [comment]
We should change [this line](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/83fe0c5bacd67f5aff1fc6eeff90d8a0355d7085/Markdown.tmLanguage#L1898) to allow a fallback here.

I propose:

````diff
-^(\s*(`{3,}|~{3,}))\s*[\w\-+#]*\s*$
+^(\s*(`{3,}|~{3,})).*$
````

**Comment by ttscoff** [comment]
Compressed:

`^(\s*[`,]{3,}).*$`

**Comment by maliayas** [comment]
Did you mean `` [`~] `` instead of `` [`,] ``? On the other hand that would allow fences like `` `~` ``, `` ~~` ``

**Comment by ttscoff** [comment]
sorry, yes to the tilde, not the comma. I wrote it too early in the morning.
