### ISSUE TITLE
Default Markdown syntax gets removed

### ISSUE THREAD

**Issue by taneltm** [SublimeText-Markdown/MarkdownEditing#284]
ST3 comes with a default Markdown syntax:
  View -> Syntax -> Markdown -> [Markdown, MultiMarkdown]

When MarkdownEditing is installed in ST3, both Markdown and MultiMarkdown syntaxes are removed.
After Uninstalling MarkdownEditing, the default Markdown syntaxes are not restored.

**Comment by felixhao28** [comment]
They are not removed. They are just disabled to prevent conflicts. You probably need to re-enable them by `Preferences -> Settings - User -> find "Markdown" under "ignored_packages" -> delete that item`.

If you are not familiar with JSON format, and have package control installed, use "Package Control: Enable Package" command and choose Markdown.
