### ISSUE TITLE
Objective-C code block display issue

### ISSUE THREAD

**Issue by zgjie** [SublimeText-Markdown/MarkdownEditing#285]
When use _Markdown GFM_ to show objective-c code block, the syntax highlight will make the text outside below the block display wrongly.

For example, this code block has the display issue: 

``` objective-c
[NSLayoutConstraint constraintWithItem:self.button1 attribute:NSLayoutAttributeRight
                      relatedBy:NSLayoutRelationEqual toItem:self.button2
                      attribute:NSLayoutAttributeLeft multiplier:1.0 constant:-12.0];
```

![screen shot 2015-06-15 at 11 57 33 am](https://cloud.githubusercontent.com/assets/2997193/8152909/dc84ed98-1355-11e5-80ea-3d519e2a4a31.png)

**Comment by felixhao28** [comment]
I think it is of the same cause with #241 that 4-space indent will break code hightlight.

**Comment by felixhao28** [comment]
It seems to be fixed.
