### ISSUE TITLE
A new line is required for code block syntax highlight per GFM

### ISSUE THREAD

**Issue by felixhao28** [SublimeText-Markdown/MarkdownEditing#286]
> Below are _not_ valid fenced code blocks according to the [GFM docs](https://help.github.com/articles/github-flavored-markdown). It says there must be a blank line before the code block. However, GitHub highlights them. So, they _should_ be highlighted.
> -- quoted from [tests/GFM.md](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/master/tests/GFM.md)

    - List item
        ```js
        for (var i = 0; i < 10; i++) {
            console.log(i);
        }
        ```

    - List item
    ```js
    for (var i = 0; i < 10; i++) {
        console.log(i);
    }
    ```

However they get highlighted nevertheless.

**Comment by AndreyMZ** [comment]
They _should_ and they _do_. What is the problem?

**Comment by felixhao28** [comment]
Github seems to have changed the description of GFM docs. Closing it.
