### ISSUE TITLE
Both bold and italic formatting do not show up when non-monospaced fonts are used

### ISSUE THREAD

**Issue by EdenSG** [SublimeText-Markdown/MarkdownEditing#288]
As shown, fonts that aren't monospaced do not receive italic or bold formatting.
### Monospaced (Source Code Pro)

![](https://infinit.io/link/EdenSG/k2rHF6b.png)
(Note as well the lack of bold-italic formatting — see issue #225)
### Sans (Avenir Next)

![](https://infinit.io/link/EdenSG/nQGTGth.png)
### Serif (Baskerville)

![](https://infinit.io/link/EdenSG/fJh8VdH.png)

I'm not sure whether this is an issue with font metadata or something else, but I've been using Sublime as a regular text editor and writing app, and proper formatting for non-monospaced fonts would be very useful.

**Comment by felixhao28** [comment]
Can anyone confirm these fonts have proper styles? I know some fonts don't have italics and some don't have bold.

**Comment by EdenSG** [comment]
They do:
> ![screen shot 2015-06-26 at 10 00 37 am](https://cloud.githubusercontent.com/assets/5727389/8378911/85dbb542-1bea-11e5-8ed6-96d92261e756.png)
> ![screen shot 2015-06-26 at 10 01 07 am](https://cloud.githubusercontent.com/assets/5727389/8378912/85dd9fb0-1bea-11e5-8087-a25794544fb3.png)

**Comment by danilaml** [comment]
I think I have the same problem - there is no highlighting for bold or italic formatting. I have ST3 with default font running on Windows.

**Comment by sambody** [comment]
I have the same problem, tested with Open Sans, Arial, Verdana, Times New Roman (which do have bold and italic). 

When using the default monospace font, the bold and italic styles show up again. I'm using Sublime Text build 3114 on Windows 10.

**Comment by felixhao28** [comment]
https://forum.sublimetext.com/t/italic-bold-not-working/22089/30?u=felixhao28

Now there is the official voice that this is an intended behavior, not a bug.
