### ISSUE TITLE
Use dark theme only for markdown files

### ISSUE THREAD

**Issue by tillkruss** [SublimeText-Markdown/MarkdownEditing#290]
Is there any way to use the dark markdown theme for only for markdown files? I'd like to keep using my personal color scheme for all other files.

**Comment by dubeg** [comment]
There is a way, mentionned under the 'Configuration' section of the [Readme.md](https://github.com/SublimeText-Markdown/MarkdownEditing#configuration). 
I'll add to this that you can assign a specific color scheme for every syntax that SublimeText recognizes. 

Ex: a markdown file that's currently opened and active in Sublime. Via the application menu, ..

    Preferences > 'Settings - More' > 'Syntax Specific - User'

This opens a file named after the syntax. Add brackets and the color_scheme key/value pair, save and see if it changed the scheme for the markdown file. Also be aware that this plugin contains 3 different markdown syntaxes, so if you use more than one, you will have to set the color scheme for those as well.

**Comment by tillkruss** [comment]
Fantastic, thank you very much!
