### ISSUE TITLE
Blockquote left border shows only for first line (lazy)

### ISSUE THREAD

**Issue by galambalazs** [SublimeText-Markdown/MarkdownEditing#291]
If the blockquote only has > in the beginning line, the left border is only shown for the first line.
![capture](https://cloud.githubusercontent.com/assets/309987/8781459/72fb66f6-2f0f-11e5-9b34-e029b66a34fa.PNG)

**Comment by maliayas** [comment]
It is a ST limitation. There have been some discussion on #42 and #130. It seems we don't have anything we can do about it, yet.
