### ISSUE TITLE
Blockquote needs left padding (like github has) + config

### ISSUE THREAD

**Issue by galambalazs** [SublimeText-Markdown/MarkdownEditing#292]
Text is too close, needs more negative space:

![capture](https://cloud.githubusercontent.com/assets/309987/8781545/f4046e50-2f0f-11e5-8f26-86936b05edbd.PNG)

Compare & contrast:

> Here is some quotation for you
> to look at and it's multiline

This padding and the border width/color should be configurable from the preferences file.

**Comment by maliayas** [comment]
That is indeed a hack. You will understand how it happens if you select that text with mouse. So, until a day that ST offers such a customization, the only way to have more spaces there is actually putting more spaces there manually.

**Comment by galambalazs** [comment]
Are there a http://sublimetext.userecho.com/ tickets for the ones I posted (or related)?

**Comment by maliayas** [comment]
I don't know. Probably not. For such powerful styling, you may want to checkout Atom editor.
