### ISSUE TITLE
Bold, italic, `inline` shouldn't break with word wrap

### ISSUE THREAD

**Issue by galambalazs** [SublimeText-Markdown/MarkdownEditing#293]
e.g.:

![capture](https://cloud.githubusercontent.com/assets/309987/8781691/ea8372c6-2f10-11e5-9861-6b6d5f6fda4f.PNG)

**Comment by maliayas** [comment]
For backticks, it is not possible yet. It is a ST bug. See #141.

For bold and italic, it is a known bug. See #103.

**Comment by galambalazs** [comment]
cool
