### ISSUE TITLE
Document level top/bottom padding

### ISSUE THREAD

**Issue by galambalazs** [SublimeText-Markdown/MarkdownEditing#294]
You don't want to start your files with a newline, but it looks *much* nicer if there's negative space in the beginning.

I hope this is possible with Sublime.

![capture2](https://cloud.githubusercontent.com/assets/309987/8781782/6a21b59c-2f11-11e5-8134-dd44608c4479.PNG)

 *vs.*

![capture](https://cloud.githubusercontent.com/assets/309987/8781778/68166fae-2f11-11e5-8f18-adcf30fda2e8.PNG)

**Comment by maliayas** [comment]
Would be nice but ST doesn't allow such styling. I'm marking the issue as "impossible" so that we can easily return to it in the future as ST has interesting updates.
