### ISSUE TITLE
Image relative URL

### ISSUE THREAD

**Issue by matej-zajacik** [SublimeText-Markdown/MarkdownEditing#296]
In my markdown document, I have the following line:

    ![AI sight cone](pics/ai_sight_01.png "AI sight cone")

So I would expect it to generate this HTML:

    <img src="pics/ai_sight_01.png" title="AI sight cone" alt="AI sight cone"/>

But instead, it generates this:

    <img src="///d://my_docs/my_game/game_docs/pics/ai_sight_01.png" title="AI sight cone" alt="AI sight cone"/>

My folder / file structure is this:

* game_docs
    * pics
        * ai_sight_01.png
    * game_doc.md
    * game_doc.html (generated from md)

Is there a way to retain relative URLs in images, links, etc.?

**Comment by felixhao28** [comment]
This plugin does not generate HTML. You must be using some other plugin.

**Comment by devkhan** [comment]
In case, anyone else comes here: It's most probably the [Markdown Preview Plugin for Sublime Text](https://github.com/revolunet/sublimetext-markdown-preview/).
