### ISSUE TITLE
How can I turn off the markdown theme just for .txt files?

### ISSUE THREAD

**Issue by lbraun** [SublimeText-Markdown/MarkdownEditing#297]
I tried removing txt from "extentions" in preferences but this did not work:
```java
"extensions":
  [
    "md",
    "mdown"
    // "txt"
  ],
```

**Comment by felixhao28** [comment]
Does this work?
View -> Syntax -> Open all with current extension as... -> Plain Text (or whatever you like)

**Comment by lbraun** [comment]
Actually, it no longer sets the theme for .txt files after restarting my computer. Thanks!

**Comment by liuyigh** [comment]
In my case, restarting Sublime Text is enough to take effect. No need to restart computer.
