### ISSUE TITLE
Syntax highlighter maybe incorrect when there is 'case' keyword appears in shell code

### ISSUE THREAD

**Issue by aneasystone** [SublimeText-Markdown/MarkdownEditing#298]
When I type the following example text in Sublime Text 3 with MarkdownEditing installed, the syntax highlighter is broken. I found the keyword 'case' maybe the cause of this problem, because when I remove the word 'case', it'll be fine.

```
Show some shell code here:

` ` `shell
      echo This is a test case > test.txt
` ` `

The text below is also assumed as code...
Blahblah...

The keyword 'case' maybe the cause of this problem.
```

Note the **\` \` \`** should be replaced by **```** if you try this in your Sublime Text, since I cannot write a code block inside another code block using GFM. (if anyone knows how, please let me know, thanks a lot !)

And you can see the effect like the image following:

![in](https://cloud.githubusercontent.com/assets/1259773/9194066/213fe81c-404b-11e5-8e34-bfdfba5f7436.png)

**Comment by felixhao28** [comment]
duplicate #221

**Comment by aneasystone** [comment]
Sorry for the duplication.. @felixhao28 

I'll close this.
