### ISSUE TITLE
Some bug about headline highlight and chinese

### ISSUE THREAD

**Issue by myy1966** [SublimeText-Markdown/MarkdownEditing#299]
![test](https://cloud.githubusercontent.com/assets/10590090/9287557/a3cf5074-434d-11e5-866f-e3f4a2fd9109.gif)

I am a Chinese and find that if I set Chinese word as headline,when I select them,it seems very strange.I think it's a bug.

![test](https://cloud.githubusercontent.com/assets/10590090/9287584/52c6d07e-434f-11e5-8a19-0ca9616715cc.gif)

In fact,the bug in relation to bold also arise when using Japanese

**Comment by felixhao28** [comment]
duplicate #187 

I am a Chinese too and I found that setting `"font_options":["directwrite"]` (if your are a windows user) solves the problem.
