### ISSUE TITLE
trim trailing white space while preserving line breaks

### ISSUE THREAD

**Issue by robsonsobral** [SublimeText-Markdown/MarkdownEditing#302]
Hi! Thanks for the package.

Is it possible to remove trailing white spaces just if they're the only thing in the line or they're less than 2?

Thanks.

**Comment by maliayas** [comment]
This is out of the scope of this plugin. You can check this plugin: https://github.com/SublimeText/TrailingSpaces You can write regex for your requirement and it has a feature to delete automatically what is highlighted.
