### ISSUE TITLE
Is it possible to use another Syntax Highlighter?

### ISSUE THREAD

**Issue by wesbos** [SublimeText-Markdown/MarkdownEditing#305]
When I write in markdown I use the triple backticks along with js. Like this without the spaces:

  \`\`\`js
     code here...
  \`\`\`

But - it uses the Sublime Text JavaScript syntax highlighter, which isn't great. I use the Babel Syntax Highlighter which also supports JSX. 

Problem is, my code ends up all weird:

![](http://wes.io/dE5t/content)

Is it possible to invoke another syntax highlighter when `js` is used?

**Comment by leesei** [comment]
https://github.com/SublimeText-Markdown/MarkdownEditing/blob/master/Markdown.tmLanguage#L1815-L1830

MarkdownEditing map fenced JS code block to syntax `source.js`, (L1827) which is defined by the Babel package.
To archive your goal, you need a `.tmLanguage` that defines your syntax (say `source.myjs`, possibly forked from Babel) and then add a `fanced-myjs` block that maps ````myjs` to `source.myjs`).
I would also recommend [facelessuser/ScopeHunter](https://github.com/facelessuser/ScopeHunter). It helps you analyse the color defined by the syntax.

**Comment by wesbos** [comment]
Hrm okay thanks - I just raised an issue on their GH. I'm not the only one with this issue so it would be great if we could get the two packages to play along.

**Comment by felixhao28** [comment]
In MDE, we just reference the scope source.js. If you disable the default JavaScript package and have babel-sublime installed, you will have babel syntax definition instead.

**Comment by craigcosmo** [comment]
@wesbos Have you figured out the solution :) ?

**Comment by wesbos** [comment]
Yes - delete the default JS package all together

**Comment by craigcosmo** [comment]
Are you sure? There is a disable package entry in the command palette, we can disable it from there.
