### ISSUE TITLE
use highlighted word as footnote marker

### ISSUE THREAD

**Issue by katrinleinweber** [SublimeText-Markdown/MarkdownEditing#307]
This is connected to #306. Again, for long documents, esp. when split into several files and processed further with Pandoc, the default way of inserting footnotes as `[^1]`, `[^2]`, etc. can cause duplicates. How about (adding an option to) using the currently highlighted word.

Example: `Chemical XYZ[^XYZ] is suspected of causing something.`

**Comment by felixhao28** [comment]
This feature will be added when v2.1.5 comes out. Thanks for suggestion.

**Comment by katrinleinweber** [comment]
Thank you for implementing it :-)
