### ISSUE TITLE
bullet lists are not properly highlighted when there are no double line breaks

### ISSUE THREAD

**Issue by arielelkin** [SublimeText-Markdown/MarkdownEditing#308]
Only the first bullet is highlighted: 

![image](https://cloud.githubusercontent.com/assets/1756909/10909075/a11e1608-8236-11e5-93b3-2380e316e16e.png)

All bullets should be highlighted!

**Comment by maliayas** [comment]
It is an old and fixed bug. Are you having this issue with 9800ec81d1a0db087436c1f3e012b6de571186fe?

**Comment by felixhao28** [comment]
I think we can close it. It almost certainly is a version issue.
