### ISSUE TITLE
MarkdownEditing won't switch color schemes

### ISSUE THREAD

**Issue by arielelkin** [SublimeText-Markdown/MarkdownEditing#309]
![image](https://cloud.githubusercontent.com/assets/1756909/10909174/66f74b06-8237-11e5-844d-295fe546c206.png)

Even after restarting SublimeText.

**Comment by AndiH** [comment]
I seem to have the same problem.

**Comment by younes0** [comment]
same

**Comment by younes0** [comment]
I had the same problem: be sure to add the color_schema to your default markdown parser:
```json
 {
       "color_scheme": "Packages/MarkdownEditing/MarkdownEditor-Dark.tmTheme",
	"extensions":
	[
		"md",
		"mdown"
	],
}
```

**Comment by maliayas** [comment]
That's not done through the menu. It should be done by modifying the MarkdownEditing settings file as @younes0 mentioned. Also documented in the README.

**Comment by arielelkin** [comment]
Well then it shouldn't be a menu option.

**Comment by maliayas** [comment]
See e3cb36a1950e766a8d105c4fbb9065e6b183d164 and 07d8ff7d8eb244a5f538cd8d9302d47854b2809e. May be one day.

**Comment by lmj0011** [comment]
Can these themes be all added by default? If not, a link to the instructions in the README should be closer to the top. I think this one of the first things a user will try to accomplished after installing this package. 

@arielelkin is right, a theme shouldn't be a menu option if you can't even use it. This was very frustrating indeed.

PR: https://github.com/SublimeText-Markdown/MarkdownEditing/pull/407

**Comment by maliayas** [comment]
I've merged your PR with some changes. Thanks.

**Comment by maliayas** [comment]
Having it under the menu is necessary for some other reason. See the comment right above yours.
