### ISSUE TITLE
syntax highlighting after code block containing forward slash

### ISSUE THREAD

**Issue by rootsical** [SublimeText-Markdown/MarkdownEditing#311]
i am wrapping some javascript code with three back ticks to denote a code block. i need to use a forward slash to denote regex within the javascript code. however this seems to break syntax highlighting for markdown in the file after the code block. thanks.

**Comment by felixhao28** [comment]
![hey](https://cloud.githubusercontent.com/assets/2417391/11767963/4de3e3f4-a1f9-11e5-9d31-deaa13234ad2.png)

**Comment by maliayas** [comment]
I love the screenshot :)

**Comment by rootsical** [comment]
![joe](https://cloud.githubusercontent.com/assets/1428831/11778371/cf59f7dc-a24b-11e5-92fe-1af5f0432ad6.png)  
sorry if i've done something stupid, i just assumed it would be the regex..

**Comment by felixhao28** [comment]
Have you installed some JS syntax (or plugin that overtakes the syntax)? That may cause incompatibility.

![image](https://cloud.githubusercontent.com/assets/2417391/11780841/f4f07350-a29f-11e5-83a8-e6b6f8d40f59.png)

**Comment by rootsical** [comment]
yes sorry, the culprit was [JavaScript Next](https://packagecontrol.io/packages/JavaScriptNext%20-%20ES6%20Syntax). sorry for the trouble and thanks for your help. closing..

**Comment by maliayas** [comment]
@rootsical  By the way, have you noticed the missing `]` in `gulp.src(['src/*.src.js']` in your screenshot?
