### ISSUE TITLE
`Enter` in Chinese input method conflicts with list item.

### ISSUE THREAD

**Issue by Quantizen** [SublimeText-Markdown/MarkdownEditing#312]
If I want to input "welcome" with Chinese input method, I should hit each character and then the `Enter` key. Because I can use the number key to choose Chinese words in the candidates.

If this just happens in the (not only at the end) line after a list item, `Enter` will not input the word and cause to change to another line and add a new list item bullet. In the other cases, `Enter` will input "welcome" as expected.

**Comment by felixhao28** [comment]
Can you be more specific? I tested with Sogou Pinyin IME and it worked just fine.

**Comment by Quantizen** [comment]
I tested Mac's input method and Squirrel in Mac OS.

**Comment by felixhao28** [comment]
Don't have a mac. Need a contributor working with Mac to potentially help with this matter. There is another issue(#213) might be related to this.

**Comment by Quantizen** [comment]
Maybe. I tested Sougou Pinyin IME, same issue.

**Comment by Quantizen** [comment]
Where should we report this bug? If it cannot solved within MarkdownEditing.

**Comment by felixhao28** [comment]
I think ultimately it is a ST3 bug. ST3 should not catch that Enter event when IME takes charge of that.

**Comment by poc7667** [comment]
I can simply reproduce the bug , please take a look https://www.youtube.com/watch?v=uDJnJxjv-80&feature=youtu.be

**Comment by CHENPoHeng** [comment]
facing the same issue (as user poc7667 showed above) here!

**Comment by alswl** [comment]
Please help CJK user solve this problem.

**Comment by qria** [comment]
So... is there a mitigation strategy? I use Korean IME extensively and run into this several times a day. Maybe with keybinding?

**Comment by felixhao28** [comment]
I haven't tested yet but a wild guess is to delete/comment out keybindings from [line 323](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/master/Default%20(Windows).sublime-keymap#L323) to [line 375](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/master/Default%20(Windows).sublime-keymap#L375). To do it you have to either install MDE without package control (with git) or unzip the MDE file from Installed Packages.

**Comment by wxk6b1203** [comment]
I faced this issue when typing Chinese. I tried to comment the line involved, but it seems a little inconvenient. To compromise, I changed the key binding into `ctrl+super+enter` ( it is not good enough either.)
I suspect this problem is caused by the adaptation of Unicode characters. Because the console said that:
```python3
Traceback (most recent call last):
  File "./python3.3/logging/__init__.py", line 941, in emit
UnicodeEncodeError: 'ascii' codec can't encode characters in position 41-44: ordinal not in range(128)
Logged from file udl.py, line 603
```

It seems to be a little problem which caused by multi-reason. Anyway, it's fine.

**Comment by felixhao28** [comment]
@wxk6b1203 The error you saw seems from another plugin. MDE does not contain a `udl.py`. I know this issue is persistent and maybe irritating, but I just lack the knowledge/skill to solve this. The best I can offer is to disable the auto list completion as a workaround.
