### ISSUE TITLE
Suggestion - require closing tags for HTML blocks be at the beginning of the line

### ISSUE THREAD

**Issue by twhb** [SublimeText-Markdown/MarkdownEditing#316]
This deviates from parsing behavior, but hear me out.

The current approach, ignoring nesting and looking for the closing tag text, is also incorrect. It closes HTML blocks at the first closing tag for an element with the same name, rather than the block's closing tag, mis-highlighting the rest of the HTML block.

A proper solution is difficult - it would mean rewriting the entire language file as a .sublime-syntax, which isn't supported in Sublime Text 2.

Since the syntax file currently requires HTML block open tags be at the beginning of their line, and handles blocks that open and close on the same line separately, adding this requirement would yield correct output for all conventionally indented code. I think that breaking on unconventional code, while not a good thing, is preferable to breaking on conventional code as is done now.

This is not a hypothetical situation, I encounter it often when using nested `dl` structures to express methods and their parameters in READMEs.

Users can currently work around this bug by wrapping HTML blocks in a tag unique within that block, but I believe that code tailored to syntax highlighters should be avoided.

Any feedback? If given the go-ahead I'd be happy to implement the change, the actual change to the syntax files is trivial.

**Comment by felixhao28** [comment]
I know there have been some scoping issues related to code blocks from the birth of this plugin. But I am not sure what I am thinking is what you are saying. Can you provide some examples to help me understand?

Rewriting the entire language files (we have three) as .sublime-syntax files is a huge task. What do you mean by "the actual change to the syntax files is trivial"?

**Comment by felixhao28** [comment]
And of course, any contribution is welcome and appreciated.

**Comment by twhb** [comment]
Sure, no problem. It's a little bit hard to get a distilled case, since of course a myriad other highlighting rules are applied to the output before you see it, but you can see that in the following code the `</span>` does not get highlighted.

```markdown
<div>
  <span>
    <div></div>
  </span>
</div>
```

That's because [this line](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/master/Markdown.tmLanguage#L139) causes the preceding `</div>` to close the entire block, instead of waiting for the correct one.

What I was calling trivial was to just stick a `^` at the beginning of that regex. That's what I'm suggesting, because it seems to me it would solve many use cases without requiring much work.

.sublime-syntax files I mention only because they are the only way I see to solve this properly, ie to maintain a context stack and close only when the first `<div>` is closed. .tmlanguage files can't do that - the regex engine actually is powerful enough, but the patterns are limited to one line for performance reasons.

**Comment by felixhao28** [comment]
I see. It definitely makes sense to require the closing tag on the same indent level of the opening one. Sadly it introduces new fail cases like:

```html
<div>This sentence is so long that I would like to manually
split it into two lines with the closing tag on the tail.</div>
```

Though I don't think this will affect many users. What do you think @maliayas ?

**Comment by twhb** [comment]
It actually, happily, doesn't fail in that case, because single-line and
multiline HTML blocks are handled separately.

>

**Comment by felixhao28** [comment]
```html
line 1: <div>This sentence is so long that I would like to manually
line 2: split it into two lines with the closing tag on the tail.</div>
```

**Comment by maliayas** [comment]
@felixhao28 I'm having some issues. I'll get back to these.

**Comment by felixhao28** [comment]
@twhb You can submit a pull request to v2.1.5 branch. We can review these changes when Ali comes back.

**Comment by maliayas** [comment]
I understand the problem. However proposed solution is risky also. We, as a highlighting plugin, can not force users to write in specific style (final closing tag at the beginning of the line). For the case @felixhao28 mentioned, rest of the document will not be rendered in markdown, as HTML block is not closed and markdown is disabled inside block-level tags.

![ekran goruntusu 2016 01 16 21_49_32](https://cloud.githubusercontent.com/assets/844008/12374141/6149d25c-bc9b-11e5-820f-ffd2f0a138d8.png)

On the other hand, you can push this in the next update and see people's feedback. I don't know how often people write `... lorem ipsum<div>`.

To me, forcing style is worse than failing at highlighting.

**Comment by felixhao28** [comment]
> To me, forcing style is worse than failing at highlighting.

We are not forcing a style. We are fixing a bug by creating another.

**Comment by twhb** [comment]
I see what you're saying, failing to highlight the rest of the document is worse than failing to highlight the rest of the HTML block, which would be the overriding factor if the first situation isn't vastly less common.

How about we require the first character of the line containing the closing tag be non-whitespace? This works for all situations my previous suggestion did, as well as the situation you pointed out. The only failure modes that remain, I think, are improperly/unconventionally indented code.

**Comment by felixhao28** [comment]
@twhb Sounds good. Notify me when you updated your pr.

**Comment by twhb** [comment]
I haven't been able to figure this one out, maybe somebody more familiar with tmlanguage files or regular expressions can help.

I'd assumed the regex engine supported variable-length lookbehinds, it doesn't. So we can't just do `(?<=^(\S.*)?</\1>)`. The `\K` flag could be used as a replacement I think, but it isn't supported either.

It seems the `endCaptures` field is made to solve this (we would match the whole final line then re-apply the desired context to the matched text), but I haven't gotten that to work.
