### ISSUE TITLE
Spell check problems with footnotes

### ISSUE THREAD

**Issue by openmedi** [SublimeText-Markdown/MarkdownEditing#319]
I tried to search for this specific issue, I found nothing but I assume (infering from [this issue](https://github.com/SublimeText-Markdown/MarkdownEditing/issues/175)) that also my issue with MDE and spell check is probably impossible to fix within MDE alone. With that said, here's my problem:

<img width="557" alt="screen shot 2016-01-16 at 13 32 47" src="https://cloud.githubusercontent.com/assets/423471/12372400/a9575754-bc55-11e5-8b16-d7699af5bc2c.png">

As you can see, all words at the end of sentences that have footnotes are false positives. (The used language in the screen shot is German btw.)

So this regex…

```
(\w*).\[\^\d*\]
```

…will always yield a false positive error with spell check, meaning the "word" (capture group 1 in my regex) will get a red squiggly underline.

**Comment by felixhao28** [comment]
If you change the syntax to plain text does the problem persists? There is nothing in MDE that controls spell checking behavior. So I don't know how we can help you on this case.

**Comment by openmedi** [comment]
The Problem might have resolved itself with the new update.
