### ISSUE TITLE
add LICENSE to repo

### ISSUE THREAD

**Issue by chrisdias** [SublimeText-Markdown/MarkdownEditing#320]
Hi!

Would it be possible to add a LICENSE file to the repo directly, instead of linking to the MIT license? This way you can include the proper attribution in the  `Copyright (c) <year> <copyright holders>` statement which in turn makes it much easier for us ([VSCode](https://code.visualstudio.com)) to properly provide attribution.

Thanks!

**Comment by chrisdias** [comment]
Any chance this will be merged soon?  Thanks!!

**Comment by felixhao28** [comment]
It is merged into v2.1.6 branch and will be released in the next version. Thank you.

**Comment by chrisdias** [comment]
Thanks!!

**Comment by robsonsobral** [comment]
How this repo was used on VSCode, @chrisdias ? Please.

**Comment by chrisdias** [comment]
@robsonsobral it looks like we no longer consume this repository in VS Code, but at the time (2 years ago) we probably were pulling in the .tmLanguage or .tmTheme files.
