### ISSUE TITLE
st3 build 3099，can't automatic add list

### ISSUE THREAD

**Issue by helloyan** [SublimeText-Markdown/MarkdownEditing#321]
in build 3083，everything works well except i can't find MarkdownEditing folder under packages folder，in build 3099，it's the same。
   But another bug is，when i click enter ,it can't add list automatic，like
\- #### 123 (click enter)
\-       (the - can't automatic add,i manual type it)

**Comment by ryne661** [comment]
unsubscribe

**Comment by zertosh** [comment]
I'm also seeing this. New list item insertion isn't working anymore in ST3 build 3099. It definitely worked in 3095.

**Comment by zertosh** [comment]
Doesn't seem to be an issue anymore in 3102.

**Comment by helloyan** [comment]
yes,like a issue about st,close it
