### ISSUE TITLE
Tab key dead in bulleted lists after restarting Sublime

### ISSUE THREAD

**Issue by klassenjm** [SublimeText-Markdown/MarkdownEditing#325]
I have installed MarkdownEditing in ST3 (build 3103 on Windows 10)

Immediately after install the <tab> key operates as expected / described in the documentation here, for working with bulleted lists.

After restarting ST, the <tab> key is dead when working with bulleted lists. If I enter a bullet with * on a new line, add some text after the bullet, and press return, ST provides the next bullet BUT the tab key is unresponsive. Pressing <tab> does nothing. It does not even add a tab to text. The key is dead.

If I edit other text outside of the bulleted list, <tab> works.

Could anyone provide an suggestion on why this might be happening, and how to resolve it?

**Comment by felixhao28** [comment]
I will be fixed in the next version. Thank you for reporting.

**Comment by klassenjm** [comment]
Excellent. Thank you.
Is there a small repair I could apply to my current installation?

**Comment by felixhao28** [comment]
I just released the new version. Package Control should handle the update next time you launch SublimtText.

You can close the issue if the problem is gone.

**Comment by klassenjm** [comment]
Thank you! Problem resolved.
