### ISSUE TITLE
Setting option to preserver order of headers during quick navigation in file (cmd+R)

### ISSUE THREAD

**Issue by rkpatel33** [SublimeText-Markdown/MarkdownEditing#329]
It would be great to have a settings option to preserver order of headers during quick navigation.

I am using it to navigate some very long .md files and often user search to narrow the list, but get confused sometimes as the closest match is at the top instead of matches in order of line number.

**Comment by felixhao28** [comment]
This is a ST3 behavior and you can post your issue/request in their issue tracker.
