### ISSUE TITLE
Setting to stop adding ellipses to long headers in `Got to Symbol` dropdown

### ISSUE THREAD

**Issue by rkpatel33** [SublimeText-Markdown/MarkdownEditing#330]
I am using MarkdownEditing to navigate and view a text version of a very long legal document. I wrote a script to convert the doc to text and add in '#' tags at specific line items based on features, however these lines can be very long.

Is there a setting to prevent MardownEditing from adding ellipses to the previews in the dropdown? Not sure if this is a native SublimeText behavior that can't be overridden. It would be really great if one could do that.

https://www.evernote.com/l/AApSEBUekXZMva2AG1ciGiBU9UxgtPFOuuw

**Comment by felixhao28** [comment]
Your guess is right: this is a native behavior of ST3, and there is little we can do about it.
