### ISSUE TITLE
Removed shortcut?

### ISSUE THREAD

**Issue by MattDemers** [SublimeText-Markdown/MarkdownEditing#332]
Hey there;

Basically I remember you guys having a shortcut for inserting link syntax on highlighted text (CTRL + WIN + K, I think?) without inserting what was in the clipboard. This seems to be removed or not working recently, and seems to have disappeared from your documentation. Was this removed recently, or was I seeing things?

**Comment by felixhao28** [comment]
Yes, some link-footnote-reference-related shortcuts are deprecated in the last patch. Now we have some new commands: (available from Command Palette, `ctrl+shift+p`)

MarkdownEditing: Jump Reference
MarkdownEditing: New Reference (this is what you are looking)
MarkdownEditing: New Inline Link (or maybe this)
MarkdownEditing: New Inline Image
MarkdownEditing: New Image
MarkdownEditing: New Footnote
MarkdownEditing: Delete Reference
MarkdownEditing: Organize References

**Comment by MattDemers** [comment]
Yup, looking for the new inline link, but blank; IIRC, `ctrl+win+v` will paste what's currently on your keyboard as a link; I'm looking for something that'll just surround my highlighted text with square brackets and add round brackets to the end with my cursor moved between them.

Basically my usecase is that I have a number of Autohotkey text placements set up for things like my Twitter or Facebook Page; I'd like to make it easier to insert these links without having to copy them first.

**Comment by MattDemers** [comment]
I'm an idiot:

If there's a URL in the clipboard, `ctrl+win+v` will create a link with that URL. If you don't have a URL in the clipboard (like, `ctrl+c` "sajklhsdjkf" or something beforehand), `ctrl+win+v` will create a blank link, like I wanted. Best of both worlds. Thanks.

**Comment by ggrrll** [comment]
fwiw after 6y, those key bindings have become 

`ctrl + alt + v/r`
