### ISSUE TITLE
How to customize markup.heading foreground?

### ISSUE THREAD

**Issue by klickreflex** [SublimeText-Markdown/MarkdownEditing#333]
I'm trying to set a custom font color for my headings but it won't work

	<dict>
		<key>name</key>
		<string>Markup: Heading</string>
		<key>scope</key>
		<string>markup.heading</string>
		<key>settings</key>
		<dict>
			<key>fontStyle</key>
			<string>bold</string>
			<key>foreground</key>
			<string>#009CCF</string>
		</dict>
	</dict>

What am I doing wrong?

**Comment by felixhao28** [comment]
You should modify this part of the theme:

```xml
<dict>
    <key>name</key>
    <string>Sections</string>
    <key>scope</key>
    <string>entity.name.section,entity.name.section.markdown</string>
    <key>settings</key>
    <dict>
        <key>fontStyle</key>
        <string>bold</string>
        <key>foreground</key>
        <string>#333333</string>
    </dict>
</dict>
```

`markup.heading` refers to the whole line of the header, including "#". The actual bold type of the title name is overridden by `entity.name.section.markdown`

**Comment by klickreflex** [comment]
Thanks a lot, that did it :+1:
