### ISSUE TITLE
New comands for footnotes not working…

### ISSUE THREAD

**Issue by openmedi** [SublimeText-Markdown/MarkdownEditing#334]
After the recent update I can't use the `alt+shift+6` comand anymore as I was used to. I have to admit that I don't understand why this would be the case, but that's besides the point. My issue: I can insert a footnote with `alt+shift+6`, but it doesn't update my screen to the position of the inserted footnote, meaning I have to start writing or scrolling to get to my footnote, which seems wrong. Secondly the jumping is not working properly it seems like. If I try to use the jump reference command, it simply does nothing. It also doesn't give an error or warning message. I press `cmd+ctrl+shift+l`, the command get executed, which I can see when I'm activating `sublime.log_commands(True)` in the console, but nothing else happens.

P.S.: I'm on OSX 10.11.3 and using the ST3 Build 3103.

**Comment by openmedi** [comment]
After working a little bit more with the new commands, I could identify some more details:

1. as already described, jumping to and from a reference doesn't update the view, which is at best confusing
2. If one does use footnotes to refer to pandoc-style citations, e.g. `[^20]: @hennion_latour2003, S. 2`, the next footnote will not be inserted correctly if `alt+shift+6` is used to create it.
3. If one does use footnotes to refer to pandoc-style citations, e.g. `[^20]: @hennion_latour2003, S. 2`, jumping back to the position in the text is broken (`cmd+ctrl+shift+l` doesn't work)
4. Jumping works only if a) the footnotes are given there own paragraph and b) they are a citation of the form `@$index` **any additional text leads to a broken footnote (see 3. and 4.)
5. the display of footnotes is incosistent: <img width="218" alt="screen shot 2016-03-21 at 14 36 14" src="https://cloud.githubusercontent.com/assets/423471/13920249/50904cde-ef72-11e5-8e00-be28d9da7939.png">
6. Jumping back and forth between footnotes is inconvenient, because the cursor (which you can't see; see 1.) is moved inside the brackets of the footnote index, it should be: behind the brackets (in the text) and at the end of the footnote (in the footnote).

I would say that these are major regressions and would like to see some kind of comment. I am willing and interested to help.

**Comment by openmedi** [comment]
Here's a gif of what I'm refering to (with `sublime.log_commands(True)`): 
![footnotes](https://cloud.githubusercontent.com/assets/423471/13920698/b4b0ec4e-ef74-11e5-984c-91c4194281dd.gif)

**Comment by felixhao28** [comment]
Footnotes, references, inline links were pretty messed up and out of maintenance for quite some time. I completely overhauled these features during last patch into what we have today. I am sorry for regressions you are experiencing and I would like you to know I read your post and working on it.

So here are the issues you are addressing:

1. `alt+shift+6` does not scroll the view into the editing position. (will fix)
2. Jumping does not work on footnotes. (will fix)
3. Jumping does not scroll the view properly. (will fix)
4. The display of footnotes is inconsistent (the reason is that sublime took the previous one as URL, will fix).

> If one does use footnotes to refer to pandoc-style citations, e.g. [^20]: @hennion_latour2003, S. 2, the next footnote will not be inserted correctly if alt+shift+6 is used to create it.

I don't understand what this means.

**Comment by openmedi** [comment]
Thank you for your comment, it's greatly appreciated! As regards to the part you don't unterstand:

>If one does use footnotes to refer to pandoc-style citations, e.g. [^20]: @hennion_latour2003, S. 2, the next footnote will not be inserted correctly if alt+shift+6 is used to create it.

I observed that creating footnotes through the afformentioned shortcut stops working depending on the content of the created footnote. It seemed to me that inserting and using the footnote functionality soped properly workign when I had a pandoc style citation in the footnote, but this was not reproduceable easily. I assume it's a parsing problem, but I'm not sure.

**Comment by felixhao28** [comment]
Yes, there was a parser problem on footnotes.I will release a new patch soon and let's see if the problem persists.

**Comment by openmedi** [comment]
Are you really not going to hotfix the bug with the footnotes?

**Comment by felixhao28** [comment]
It is already fixed in v2.1.6. Are you still reproing these issues?

**Comment by openmedi** [comment]
I removed the comment. It was written on a particularly hot headed day. It seemed that MDE didn't update the view when jumping between footnotes and text, but this might've been because of my origami layout or some other reason. I appologize for the harsh tone. Please ignore and carry on.
