### ISSUE TITLE
Have to set "wrap_width": 81 to wrap at 80.

### ISSUE THREAD

**Issue by Arcank** [SublimeText-Markdown/MarkdownEditing#336]
STEPS
- Have a 80 chars line.
- Have the default "wrap_width": 80.

WHAT HAPPENS
Line gets wrapped.

WHAT SHOULD HAPPEN
Line should not get wrapped.
Note: Setting to "wrap_width": 81 wraps correctly.

CONFIG
Sublime Text 3
Markdown GFM syntax

There must be an off-by-one error somewhere.

**Comment by felixhao28** [comment]
Word wrap at 80 means 79 is the maximum number of characters per line.

**Comment by Arcank** [comment]
This seems not specific to Markdown GFM, but Sublime Text.

The [doc says](https://www.sublimetext.com/docs/2/distraction_free.html):
"The value of 80 causes wrapping to happen at 80 characters. You may want to set this to a higher value, or wrap to the window width, by setting it to 0."

It's ambiguous how to understand "at 80 chars". I always thought you could have:
<img width="597" alt="screen shot 2016-03-29 at 11 09 44" src="https://cloud.githubusercontent.com/assets/197492/14103414/57365cde-f5a0-11e5-97ce-0cb05bddee75.png">

That's why the ruler at 80 would let you input 80 chars then the newline marker.
I'll file at Sublime Text :)

**Comment by Arcank** [comment]
https://github.com/SublimeTextIssues/Core/issues/1159
