### ISSUE TITLE
iA Writer-style UI theme

### ISSUE THREAD

**Issue by kevinSuttle** [SublimeText-Markdown/MarkdownEditing#342]
In conjunction with #343, I've been working on an iA Writer-style UI theme for ST.

Here's a preview. Definitely a WIP, but it's getting there. 

<img width="1440" alt="screen shot 2016-04-19 at 11 38 02 pm" src="https://cloud.githubusercontent.com/assets/95672/14662810/d38ccdfc-0687-11e6-8a55-867ba5c7cf8f.png">

I found myself taking one of 2 approaches when building this (which was based off of Soda Light 3). 

1. Copy the styles _exactly_ from iA Writer
2. Make the styles a bit more reasonable to work with for code. 

I chose 1, because 2 can always added as tweaks later. 
The main issues I came across with Sublime UI theming in general are documented here: https://github.com/kevinSuttle/Architect-Theme/issues

**Comment by felixhao28** [comment]
Put current default theme here for comparison.

![image](https://cloud.githubusercontent.com/assets/2417391/14667528/5631307e-0712-11e6-90f4-e03445921895.png)

**Comment by felixhao28** [comment]
@kevinSuttle I noticed you already have [Architect-Theme](https://github.com/kevinSuttle/Architect-Theme). How about integrating your changes for MDE into your theme so users can choose whether to use your theme or not?

**Comment by kevinSuttle** [comment]
I can do that.

**Comment by felixhao28** [comment]
An entirely separate theme. I can advertise your theme in the README when it is done.

**Comment by kevinSuttle** [comment]
+1. Thanks @felixhao28!
