### ISSUE TITLE
Only first bullet in list gets correct color

### ISSUE THREAD

**Issue by mberasategi** [SublimeText-Markdown/MarkdownEditing#344]
Only the first bullet in any kind of list gets the correct color from the color scheme when using the `Markdown (Standard)` syntax; they display OK with `Markdown GFM` or `MultiMarkdown`. This is `Markdown (Standard)` in the [OceanicNext Dark](https://github.com/voronianski/oceanic-next-color-scheme) color scheme (ST3 build 3103):

![bullet-colors](https://cloud.githubusercontent.com/assets/738823/14847372/90c3adf6-0c68-11e6-97ed-43d01136784d.png)

This also happens with the `AcademicMarkdown` syntax from the [AcademicMarkdown](https://github.com/mangecoeur/AcademicMarkdown) extension to MarkdownEditing.

**Comment by maliayas** [comment]
I'm not sure if we should improve the standard syntax. Maybe we should only update it from the upstream. It is developed here: https://github.com/sublimehq/Packages/commits/master/Markdown. If you wish to improve it you can send PR to upstream so that everybody benefits.

**Comment by mberasategi** [comment]
I have tried but I am not skilled enough to do so. In my way, I have found some references that maybe someone better fitted could use to solve this issue: #195 (closed on Feb 2015) and [SublimeText 3 Syntax Highlighting Markdown List Asterisk](http://superuser.com/questions/1046133/sublimetext-3-syntax-highlighting-markdown-list-asterisk) (solved Mar 2016).
