### ISSUE TITLE
How to edit the sublime-completions to MarkdownEditing

### ISSUE THREAD

**Issue by sequencer** [SublimeText-Markdown/MarkdownEditing#346]
I'm having a good time with MarkdownEditing.
However,the auto-complete is troubling me.
I wondering that, if there exist an method to replace the build-in .sublime-completions?
I wanna add the latex symbols to it.
And is there any way to bind command+shift+( to \(\), and command+shift+[ to \[=\]?

**Comment by felixhao28** [comment]
> I wondering that, if there exist an method to replace the build-in .sublime-completions?

We don't have any .sublime-completions in this plugin.

> And is there any way to bind command+shift+( to \(\), and command+shift+[ to \[=\]?

Yes. Check Preferences -> Key Bindings. There are extensive amount of examples [here](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/master/Default%20(Windows).sublime-keymap).
