### ISSUE TITLE
Key Bindings Overriding Built-In Key Bindings

### ISSUE THREAD

**Issue by joezimjs** [SublimeText-Markdown/MarkdownEditing#353]
Ctrl+Shift+B is the built-in key binding for "Build with...", but when I'm in a MD file, you guys have it (un)bold the selection. I'm ok with just overriding your functionality in my own key bindings file, but I don't know the command name for Build with...

So, can you either change your key bindings, or help me out with the build with... key binding?

**Comment by joezimjs** [comment]
Nevermind. Found it: `{ "keys": ["ctrl+shift+b"], "command": "build", "args": {"select": true} }`

**Comment by joezimjs** [comment]
You still may want to consider changing your key bindings though, so I'll leave this open.

**Comment by FichteFoll** [comment]
This should definitely be resolved. Overriding default key bindings is highly discouraged, especially an important one that also applies to this context, like ctrl+shift+b.

**Comment by felixhao28** [comment]
The shortcut was changed from `ctrl+b` to `ctrl+shift+b` in 7e28ad2fb777692f28e20197595e7479a53fd011 by @maliayas in 2013 when `build with` command was not present. I never used this shortcut.

So should we remove this shortcut or change it to something like `alt+shift+b` (it is a bit hard to press with one hand)?

**Comment by FichteFoll** [comment]
FWIW, `ctrl+shift+i` is a default binding as well, btw:
```
{ "keys": ["ctrl+shift+i"], "command": "show_panel", "args": {"panel": "incremental_find", "reverse": true} },
```

I don't type `ctrl+b` (or `ctrl+shift+b` for that matter) with one hand anyway, so I wouldn't have a provlem with the binding being changed to `alt+shift+b`. A key chord could also be a consideration. Unfortunately, `ctrl+k, ctrl+b` is already bound to toggle the sidebar, so `ctrl+k, ctrl+shift+b` would remain, but I doubt it's better than `alt+shift+b`

**Comment by joezimjs** [comment]
Personally, I don't see the need too press 2 or 3 keys of a shortcut to replace 2 or 4 keypresses to add the characters myself.

**Comment by FichteFoll** [comment]
The advantage of the keybinding is that it wraps the selection as well.

**Comment by tobikster** [comment]
I noticed also a problem with binding ctrl+alt+s on Windows - it is used in polish language to enter "ś" letter.
I have done workaround by removing this binding from default sublime-keymap file, but it will be nice if you could change this to another keys.

**Comment by FichteFoll** [comment]
Unfortunately, <kbd>Alt+i</kbd> is the accelerator for opening the "Find" menu.

**Comment by felixhao28** [comment]
Well then. At least nearly all commands in Find menu have a shortcut on their own so user don't necessarily need to on Find menu through shortcut.
