### ISSUE TITLE
[Feature Request] Dimmed HTML In Headings

### ISSUE THREAD

**Issue by vladipus** [SublimeText-Markdown/MarkdownEditing#354]
It's not a secret that in order to have anchors in headings you have to use the `<a>` elements. However, it decreases the readability of headings greatly: `### <a name='hddtemp-installation'/>Installation` It would be great, if the highlighting was dimmed or even "unbolded" for such HTML inclusions.

Thank you for you project!

**Comment by maliayas** [comment]
@vladipus Is this the fix you were looking for? On the other hand, you can put the anchor at the right side of the line. Even with some preceding whitespace before it.

**Comment by vladipus** [comment]
@maliayas Well, it's kinda working, but not for plain Markdown version. Is that by design?

BTW, are there any plans to support CommonMark?

**Comment by maliayas** [comment]
There is no current plan. I don't know if @felixhao28 has any.

**Comment by felixhao28** [comment]
> but not for plain Markdown version. Is that by design?

No, I just fixed (in the next version).

> are there any plans to support CommonMark?

No, but contributions are welcome.

**Comment by vladipus** [comment]
Plans to support the `# Heading {#custom-anchor-id}` syntax? =D
