### ISSUE TITLE
GFM syntax highlighting is broken?

### ISSUE THREAD

**Issue by danilaml** [SublimeText-Markdown/MarkdownEditing#355]
When I choose regular Markdown syntax the view changes drastically, to the white theme and centered text (btw, is there a way to keep the same style as default chosen one of ST? I just want highlighting of MD constructs not the entirely different looking editor), everything is highlighted and formatted as it should (with **bold** and *italic* and etc.) but when I select `Markdown GFM` there is no change. Only some html tags are highlighted.

**Comment by danilaml** [comment]
Hm, I think it got fixed after I restarted sublime. Still strange and the question about style stands.

**Comment by felixhao28** [comment]
This is being discussed in #209. Let's move discussion there.
