### ISSUE TITLE
please add convert to html feature

### ISSUE THREAD

**Issue by kaiyulee** [SublimeText-Markdown/MarkdownEditing#358]
please add convert to html feature~

**Comment by felixhao28** [comment]
This seems to be the plugin you are looking for: https://packagecontrol.io/packages/MarkdownBuild

**Comment by maliayas** [comment]
We may include such functionality in the future. Related to #99.

**Comment by felixhao28** [comment]
Just add it here: MarkdownPreview is the solution for ST3 users.
