### ISSUE TITLE
Why inconsistent keyboard shortcut for italic/bold across win/osx?

### ISSUE THREAD

**Issue by reagle** [SublimeText-Markdown/MarkdownEditing#359]
I use this on Linux and OS X machine and am wondering if there's a reason the modifiers shift and alt are different? I can remap them, I know, but is there some collision or issue I'm not aware of? Why not be consistent?

**Comment by felixhao28** [comment]
I can trace it to here: 7e28ad2fb777692f28e20197595e7479a53fd011

There are discussions here #121 and here #116

> Why not be consistent?

Ctrl/alt/super/option/shift has different meaning on Windows/Linux and Mac despite having the same name. For example, on Windows super (Windows Logo Key) is bound to the OS-level functions while it is a commonly-used modifier on Mac.
