### ISSUE TITLE
Line highlight is too dark (2016-07-20 change)

### ISSUE THREAD

**Issue by Fironet** [SublimeText-Markdown/MarkdownEditing#369]
[This commit](https://github.com/SublimeText-Markdown/MarkdownEditing/pull/348/commits/d85293f5631fbaa19a7aee6ee43aa48828006393) changes the line highlight to a much darker shade of grey that makes light grey text in markdown documents harder to see and is generally unattractive. The original color worked well, and contrary to the commit description was not lighter than the background color but a pleasant subtle light grey that suited the original color scheme.

I have no screenshot of the previous highlight shade but here is the current for reference:

![screenshot](https://cloud.githubusercontent.com/assets/6971981/16978510/89d5fc46-4e9f-11e6-98fd-bf016d80566a.png)

Having the package auto update change the color as I was editing a document made the change immediately obvious and distracting. For the time being is there a way of installing a previous version of MarkdownEditing and disabling Package Control auto updates for the package?

**Comment by felixhao28** [comment]
Well it shouldn't highlight the whole line:

![image](https://cloud.githubusercontent.com/assets/2417391/17008502/79b58be4-4f24-11e6-83b0-7e57c5cc79d9.png)

Have you set some non-default settings somewhere that may lead to "highlighting whole line" behavior?

**Comment by felixhao28** [comment]
You probably have set "highlight_line" to true in the package settings. You can set it to false.

There is a way to install a previous version. It requires a bit knowledge on using git.

1. Uninstall package (Command Palette -> Uninstall Package -> MarkdownEditing)
1. Open a terminal
1. Navigate to Packages directory (%APPDATA%\Sublime Text 3\Packages)
1. Clone repository (git clone https://github.com/SublimeText-Markdown/MarkdownEditing.git)
1. Check out a commit prior to d85293f5631fbaa19a7aee6ee43aa48828006393 (git checkout 7417dd812176f5d5b8028240a40273b94f2a06a6)
1. Add MarkdownEditing to "auto_upgrade_ignore" in Packages Settings for Package Control.

**Comment by Fironet** [comment]
I much prefer having highlight_line set to true as it's useful seeing the whole line highlighted. It's enabled for all the themes I use.

Thanks for the steps for installing a previous version, I'll see if I can get it working. It's a pity I didn't know how to disable specific packages earlier.

**Comment by felixhao28** [comment]
https://github.com/SublimeText-Markdown/MarkdownEditing/releases/tag/2.1.6

I just realized you can download a previous release here. So you don't need to mess with git.

**Comment by Fironet** [comment]
@felixhao28 cheers. I removed the original package with Package Control then unzipped the release and placed in `C:\Users\Fironet\AppData\Roaming\Sublime Text 3\Packages\MarkdownEditing` (the directory that appears when choosing 'Browse Packages in ST3). Also tried the `\User` directory.

However while .md Markdown files display correctly other extensions like .txt display the default theme/styling, even though the Markdown user settings are the same as before. Any idea why?

**Comment by maliayas** [comment]
Related: https://github.com/SublimeText-Markdown/MarkdownEditing/pull/378
