### ISSUE TITLE
Bug for jsx syntax highlighting

### ISSUE THREAD

**Issue by Shaxmatist** [SublimeText-Markdown/MarkdownEditing#370]
![image](https://cloud.githubusercontent.com/assets/6180887/16984049/c0e0cfbe-4e80-11e6-814b-41e0997212cb.png)

**Comment by felixhao28** [comment]
You need to install a React syntax (e.g. babel). Vanilla JS syntax does not parse JSX well.

**Comment by felixhao28** [comment]
You can also try ```jsx instead of ```js. In case your React syntax extension does not override vanilla JS syntax.

**Comment by leesei** [comment]
I've installed `JavaScript (Babel)`, my `.js` files are using it but js code blocks like the one above uses the built-in `JavaScript` syntax.
Is there any settings to specify the syntax?

**Comment by felixhao28** [comment]
@leesei Try disabling the built-in JavaScript package?
