### ISSUE TITLE
How can I remove the horizontal scroll bar?

### ISSUE THREAD

**Issue by Kristinita** [SublimeText-Markdown/MarkdownEditing#372]
When I work with my Markdown documents in Live Preview mode, my texts appears horizontal bar. It is very uncomfortable. How can I see my text without rewinding is horizontal? Thanks.

![Horizontal scroll bar](http://i.imgur.com/O5vizje.png)

**Comment by felixhao28** [comment]
set "wrap_width" to a lower number than 80. Say 40 or even 0 to fit window width.

Preferences -> Package Settings -> Markdown Editing -> XXX Settings - User

```json
{
  "wrap_width": 20
}
```
