### ISSUE TITLE
Initial save doesn't use first h1 for filename

### ISSUE THREAD

**Issue by jaacob** [SublimeText-Markdown/MarkdownEditing#375]
It used to be that if I had a `# Header` block at the top of my document, Markdown Editing would grab that and use it for the filename of the document on initial save.

This feature recently stopped working in the last couple of days. Is this a regression or future correct behavior?

I use multimarkdown with metadata in the header—perhaps this is causing the bug?

Example:
```
Title: Foo
Author: Me
Date: July 28, 2016
Tags: foo, bar

# Header of document
...
```

**Comment by felixhao28** [comment]
There was a recent code change that caused this regression. It will be fixed in the next release.

**Comment by jaacob** [comment]
Great, thanks!
