### ISSUE TITLE
Change default branch to the newest dev branch

### ISSUE THREAD

**Issue by felixhao28** [SublimeText-Markdown/MarkdownEditing#376]
Hi @maliayas , would you consider changing the default branch from master to the newest dev branch? The reason is new contributors usually submit their PRs on the default branch and I have to tell them switch to dev branch.

**Comment by maliayas** [comment]
Yeah, I see that happens often.

I did some research and found the good news. GitHub added a new feature [yesterday](https://github.com/blog/2224-change-the-base-branch-of-a-pull-request) (yes that's true) which allows us to modify PR's target branch. I tried it with #350 and it seems working.

**Comment by felixhao28** [comment]
Cool
