### ISSUE TITLE
tab name for new files not taking first line

### ISSUE THREAD

**Issue by johnathanz** [SublimeText-Markdown/MarkdownEditing#380]
When I edit a new file in "plain text" the ST automatically default the tab name to the first line in the file. This makes is super easy to identify files when navigating using (CMD+P).

When editing in any of the MarkdownEditing syntax, we lose this ability. Is there a setting I could toggle to turn this back on?  I generally have up to 10 different new files open at once. Right now, I literally have to click on each one to check contents.

Any help appreciated!

**Comment by felixhao28** [comment]
Related to #375

**Comment by johnathanz** [comment]
thx Felix!
