### ISSUE TITLE
Tabbing to indent a list does not work in the latest build

### ISSUE THREAD

**Issue by dkurth** [SublimeText-Markdown/MarkdownEditing#382]
Using the latest release (2.1.9), if I am typing a list, and I hit Enter to create a new item, then hit Tab to indent, the Tab does not work.  The cursor stays where it was, as if I never hit Tab.

I fixed this locally by editing indent_list_item.py.  I changed this line:

`from MarkdownEditing.mdeutils import *`

to:

`from mdeutils import *`

I don't know if this is unique to my environment, or I'd consider creating a pull request.

**Comment by jpcaruana** [comment]
same issue, same fix solved it. You should consider creating a pull request

**Comment by dkurth** [comment]
@jpcaruana Thanks for confirming.  I have created the pull request.

**Comment by felixhao28** [comment]
What version of SublimeText are you using? SublimeText 3 uses python 3 since Build 3006 (released on Jan 2013)

**Comment by felixhao28** [comment]
I think you are using ST 2. We are not maintaining the compatibility for ST 2 anymore. And most features are never tested on ST 2. I strongly suggest you to upgrade to ST 3.

**Comment by dkurth** [comment]
You're right, I'm on ST 2 still, and I didn't realize it wasn't supported.  Thanks!
