### ISSUE TITLE
How to change the font size for headings?

### ISSUE THREAD

**Issue by Kshitiz-Sharma** [SublimeText-Markdown/MarkdownEditing#387]
This plugin currently shows all levels of heading with the same size in the editor. I think it would be easier to navigate and understand a large document if the headings had relative sizes. 

Can this be accomplished by editing any configuration files? If not, then please consider this as a feature request and add it to the project backlog.

Thanks

**Comment by felixhao28** [comment]
> Can this be accomplished by editing any configuration files?

Sorry, no. And I don't think it is even possible in ST3.

**Comment by minexew** [comment]
Has anything changed about this?
