### ISSUE TITLE
[Bug] Ampersand in links bad color

### ISSUE THREAD

**Issue by Kristinita** [SublimeText-Markdown/MarkdownEditing#389]
MarkdownEditor.tmTheme — my color scheme file
Markdown GFM — my syntax file

For example, my link:

`<a href="bitcoin:1DF9jgzftTFn4ZnDV2YEjUtZ3uHtBywj57?label=In%20the%20treatment%20of%20Sasha's%20teeth&amount=0.0037">![Bitcoin Donate Button](https://www.drupal.org/files/project-images/bitcoindonate.png)</a>
`

Visible yellow on gray is very bad.

![Ampersand](http://i.imgur.com/9uRMUoD.png)

Scope of this ampersand is `text.html.markdown.gfm meta.paragraph.markdown meta.tag.inline.a.html meta.attribute-with-value.html string.quoted.double.html invalid.illegal.bad-ampersand.html`.

Thanks.

**Comment by felixhao28** [comment]
I think this issue is somehow fixed. At least in build 3141.
