### ISSUE TITLE
no syntax highlighting for Setext-style headers

### ISSUE THREAD

**Issue by Nono459** [SublimeText-Markdown/MarkdownEditing#392]
Hello,

I am using the MarkdownEditing syntax.
It works great, including the ATX style headers, which it displays in bold.
It seems to reconize the setext-style headers, since they are in the symbol list.
However, the setext-style headers have no syntax highlighting: they are not bold and they have the same color as the regular text.

Is it the standard behavior?
Can it displays the setext-style headers as the ATX style headers?

I am using sublime text 2, version 2.0.2, build 2221.
I installed the Markdown Editing package in the beginning of september.

Best regards,
Nono

**Comment by felixhao28** [comment]
MarkdownEditing works best with Sublime Text 3. You are highly encouraged to use ST3 over 2.

And it is a known issue (https://github.com/SublimeText-Markdown/MarkdownEditing#known-bugs).
