### ISSUE TITLE
Features not functioning: automatic list bullets,  CTRL+[NUMBER] hotkeys

### ISSUE THREAD

**Issue by vongoh** [SublimeText-Markdown/MarkdownEditing#396]
Some of the features in ST3 have quit functioning for me:
- Hitting enter after a bullet - `*` or `-` - inserts a blank return, not another bullet
- Using CTRL+[NUMBER] - ex. CTRL+1 - to put in a corresponding heading does nothing

I have to type in the `#` manually instead.

The interesting thing about this issue is that it started showed up on my old PC a couple of months ago (I never took a minute to report it).  Since then I have built a brand new PC with a fresh install of ST3, and used a batch script to get all of my favorite plugins reinstalled from scratch.   It's the same thing here with no change.  Anything I should be looking for?  Thanks .. 

Win 10
ST3 Build 3126

**Comment by felixhao28** [comment]
Both features are working for me. Probably some conflicts with other plugins?

**Comment by felixhao28** [comment]
Well I am closing this issue for now. Reopen it if you are still bothered by this issue.
