### ISSUE TITLE
How to use Monokai Extended theme 

### ISSUE THREAD

**Issue by kujiy** [SublimeText-Markdown/MarkdownEditing#398]
I installed MarkdownEditing and Monokai Extended on Sublime Text 3. But there is no .tmTheme file of Monokai Extended. How can I use it for MarkdownEditing?

**Comment by kujiy** [comment]
Oh, I got the solution from just my imagination.

```
{
   "color_scheme": "Packages/Monokai Extended/Monokai Extended.tmTheme",
}
```

**Comment by caseros** [comment]
Was stuck for 1hr+ trying to get this to work, thanks! 👍 

(on OSX)

``` "color_scheme": "Packages/Monokai\ Extended/Monokai\ Extended.tmTheme" ```
