### ISSUE TITLE
Code block not closing when brackets are not closed inside it.

### ISSUE THREAD

**Issue by cristobal-io** [SublimeText-Markdown/MarkdownEditing#400]
Description: 

Reading (react-redux-universal-hot-example)[https://github.com/erikras/react-redux-universal-hot-example/blob/master/README.md] I noticed that after a specific code block, it wasn't displaying the proper color scheme.

Inside a code block, the curly bracket on line 149 is not closed, causing an unexpected behavior with wrong color scheme.

Device: 
- iMac (27-inch, Late 2009)

Operating system: 
- OSX 10.11.6 (15G1004)
- Sublime Text Build 3126

Steps to reproduce: 
- open (react-redux-universal-hot-example readme)[https://github.com/erikras/react-redux-universal-hot-example/blob/master/README.md]
- go to line 149 to see the non-closed curly bracket.

Actual behavior: after the code block, the color scheme is not the right one, it seems like it is not closing the `code block`

Expected behavior: close the code block and continue with the normal syntax, no matter if the brackets inside the `code block` are closed or not.

**Comment by felixhao28** [comment]
Upcoming fix described in #484. Closing it for now. Feel free to reopen it if that solution is not sufficient.
