### ISSUE TITLE
Markdown (GFM) javascript code block's first single-line comment '//' breaks syntax highlighting.

### ISSUE THREAD

**Issue by kennyklee** [SublimeText-Markdown/MarkdownEditing#401]
Whe using Markdown (GFM) 'javascript' code block, the first comment that is not blocked scoped breaks the rest of the syntax highlighting.

See screenshots:

Working correctly:
<img width="737" alt="screen shot on 2016-10-25 at 22-34-38" src="https://cloud.githubusercontent.com/assets/1432489/19714543/f3d6f9be-9b03-11e6-8898-3d9fd8156330.png">

Not working correctly:
<img width="812" alt="screen shot on 2016-10-25 at 22-33-22" src="https://cloud.githubusercontent.com/assets/1432489/19714550/fccec164-9b03-11e6-8af1-487891d59bdb.png">

Not working correctly:
<img width="727" alt="screen shot on 2016-10-25 at 22-32-59" src="https://cloud.githubusercontent.com/assets/1432489/19714551/ff1df19c-9b03-11e6-88de-0951bad9eb2e.png">

**Comment by guowenfh** [comment]
I met the same problem,I think it's because block-level syntax

![image](https://cloud.githubusercontent.com/assets/15883471/23468346/8a7eab74-fedb-11e6-983d-7419e6f684bf.png)

**Comment by felixhao28** [comment]
Upcoming fix described in #484. Closing it for now. Feel free to reopen it if that solution is not sufficient.
