### ISSUE TITLE
Problem to activate the theme

### ISSUE THREAD

**Issue by aborruso** [SublimeText-Markdown/MarkdownEditing#402]
Hi,
I have just installed MarkdownEditing in sublimetext 3, I have restarted it but the theme is not applied.

What could be the reason?

Thank you

**Comment by felixhao28** [comment]
Try View->Syntax->MarkdownEditing->Markdown GFM

**Comment by aborruso** [comment]
I do not know why, but it works from a few days

**Comment by felixhao28** [comment]
I have a guess what was happening. See this: https://github.com/SublimeText-Markdown/MarkdownEditing#installation .
