### ISSUE TITLE
a user defined theme would be great

### ISSUE THREAD

**Issue by okken** [SublimeText-Markdown/MarkdownEditing#403]
I like the dark theme. But I'd really like to make the background actual black, and not just grey.
It would be great to allow users to edit the theme or set a user defined one.

**Comment by yycsrkl** [comment]
yeah, that is gonna be awesome. but instead, u could design and make ur own one I guess

**Comment by felixhao28** [comment]
You can if you git clone this repo into your packages folder and edit the theme files by yourself.
