### ISSUE TITLE
How to set the default (4 spaces code) highlight to shell?

### ISSUE THREAD

**Issue by elgalu** [SublimeText-Markdown/MarkdownEditing#406]
Here in GFM, if one uses 4 spaces it styles it as code but uncolored:

    echo "great ${PLUGIN} thanks!!" && exit 0

The plugin works fine, and in the same way.

However, is it possible to set a default syntax highlight for it? I would set it to bash.

```sh
echo "great ${PLUGIN} thanks!!" && exit 0
```

If not, can you point me to the source where I can implement it?

**Comment by felixhao28** [comment]
No you can't use hightlight on 4 spaces code blocks. You can take a look at [Markdown.tmLanguage](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/master/Markdown.tmLanguage#L459), but I don't know if it is possible to implement that.

**Comment by elgalu** [comment]
Ah ok, thanks!
