### ISSUE TITLE
Request to add trailing whitespace highlighting to denote line breaks in MultiMarkdown

### ISSUE THREAD

**Issue by tommai78101** [SublimeText-Markdown/MarkdownEditing#408]
In the following screenshot, you can see that there's trailing whitespace highlighting for the Markdown GFM syntax:

![](http://i.imgur.com/WocKNdd.png)

But in MultiMarkdown, I cannot seem to have trailing whitespace highlighting:

![](http://i.imgur.com/ymaVYum.png)

May I request to have the option to highlight trailing whitespaces to denote line breaks for MultiMarkdown?

Thanks.

**Comment by felixhao28** [comment]
That yellow hightlight is introduced by your color scheme. Apply the same color schema to MultiMarkdown (MultiMarkdown Settings - User) and you will see it.

**Comment by tommai78101** [comment]
Thanks @felixhao28

I'm able to successfully add a custom color scheme to point out line-breaks in Markdown:

```
<dict>
            <key>name</key>
            <string>Markdown: Linebreak</string>
            <key>scope</key>
            <string>text.html.markdown meta.dummy.line-break</string>
            <key>settings</key>
            <dict>
                <key>background</key>
                <string>#A57706</string>      <----------   Set any color here.
                <key>foreground</key>
                <string>#E0EDDD</string>
            </dict>
        </dict>
```

**Comment by felixhao28** [comment]
Just out of curiosity, what color scheme were you using on the first screenshot? @tommai78101

**Comment by tommai78101** [comment]
The default theme, Solarized (Dark).
