### ISSUE TITLE
Line-breaks within Markdown comments breaks highlighting

### ISSUE THREAD

**Issue by pjpaulpj** [SublimeText-Markdown/MarkdownEditing#409]
In MarkdownEditing, comments of this form are highlighted properly: 

`[//]: # (This is a comment without a line-break.)`

While comments of this form are not:
`[//]: # (This is a comment with
a line-break.)
`

**Screnshot**
![Screen-shot](https://cloud.githubusercontent.com/assets/7358059/21337178/fd5dcbbc-c690-11e6-8255-156ed4a58c34.png)

I'd like to change this so that the highlighting is not affected by line-breaks.

I used Package Resource Viewer and Color Scheme Editor to try and edit the colour scheme. But, I'm not sure how and what to edit in the .tmTheme xml file.

**Comment by felixhao28** [comment]
It is definitely a syntax parsing bug but it is not easy to fix. Thanks for reporting anyway.
