### ISSUE TITLE
Markdown Lint breaks on horizontal line

### ISSUE THREAD

**Issue by Timber232** [SublimeText-Markdown/MarkdownEditing#410]
Markdown Lint doesn't do anything when Horizontal break is introduced:

`---`

I was expecting a feedback message like so (success or failed):
![image](https://cloud.githubusercontent.com/assets/627637/21583809/541ce844-d05e-11e6-892e-7afdcb105506.png)

This does not happen when a horizontal line is inserted, nothing is shown in the status bar.

![image](https://cloud.githubusercontent.com/assets/627637/21583819/e5259b1a-d05e-11e6-8558-200b5baa5c81.png)

Using Sublime Text 3 Version 3126 on Windows 10 64-bit.

**Comment by felixhao28** [comment]
thanks for reporting!
