### ISSUE TITLE
Potential Error in Readme Documentation

### ISSUE THREAD

**Issue by govindrai** [SublimeText-Markdown/MarkdownEditing#412]
readme file states: 
Typing return at the end of a line that begins with hashmarks will insert closing hashmarks on the headline. They're not required for Markdown, it's just aesthetics, and you can change the mde.match_header_hashes option in your settings to disable.

However to my knowledge, hashmarks is set to false by default, but can be turned on in the settings.

Should instead read:
Typing return at the end of a line that begins with hashmarks will insert closing hashmarks on the headline if `mde.match_header_hashes` is set to enabled.

However, another issue also exists: changing the property value from false to true does not start adding hashes at the end of the header. So this feature seems to be broken. (I did restart my sublime after making the changes).

**Comment by felixhao28** [comment]
> However to my knowledge, hashmarks is set to false by default, but can be turned on in the settings.

Yes you are correct. I will change that in readme.

> However, another issue also exists: ... So this feature seems to be broken.

Well it works on my end.

![a](https://cloud.githubusercontent.com/assets/2417391/21969213/648700a0-dbd7-11e6-841e-07fab84ef97f.gif)

**Comment by IanJang** [comment]
@felixhao28 Hi. I want know what is the tool you used to record your screen.

**Comment by felixhao28** [comment]
@IanJang 

[ScreenToGIF](https://github.com/NickeManarin/ScreenToGif) — programs for screencasts for me.
[KeypressOSD](https://autohotkey.com/boards/viewtopic.php?t=225) — script for displayed keyboard keys and mouse buttons for me.

I got them once from another MDE user (and contributor) @Kristinita.

**Comment by IanJang** [comment]
@felixhao28 Thanks for your answer. It seems very useful to me!
