### ISSUE TITLE
Two carets when using IME

### ISSUE THREAD

**Issue by et2010** [SublimeText-Markdown/MarkdownEditing#413]
I'm using Chinese IME, and there are two carets when typing Chinese. An intended feature?  or just me?
I've tested several IMEs, here's some of them:

Rime: 
![bug](https://cloud.githubusercontent.com/assets/11584902/22209226/a6791e3c-e1c0-11e6-8ae9-b140bb08e931.gif)

Microsoft Pinyin:
![bug2](https://cloud.githubusercontent.com/assets/11584902/22209527/c2cff14a-e1c1-11e6-8f4f-2397536a7834.gif)

When *not* editing markdown, it looks like this:
![right](https://cloud.githubusercontent.com/assets/11584902/22209961/2e76e592-e1c3-11e6-8979-ad42b01fa8ff.gif)

You can see that there is only one caret and the IME tooltip (I'm not so sure about this terminology) is always below the caret.

Can I get the latter when editing markdown?  @felixhao28 Thanks.

**Comment by felixhao28** [comment]
As far as I know, Sublime Text does not work perfectly with CJK IME. You can try reporting this issue to https://github.com/SublimeTextIssues/Core/labels/C:%20i18n and see if anyone will actually take a look.

I cannot quite repro what you are seeing. I tried the default Win10 Pinyin IME and the suggestion bar is always on the left top corner of the primary screen. And I didn't see any carets other than the blue one.

**Comment by felixhao28** [comment]
Meanwhile, you can set "draw_centered" to false in your user settings to workaround it.

> IME tooltip (I'm not so sure about this terminology)

It is called Candidate List or Candidate Window or just simply Candidates.

**Comment by et2010** [comment]
> I tried the default Win10 Pinyin IME and the candidate list is always on the left top corner of the primary screen.

Sorry, I forgot to mention that I'm using a ST3 plugin called [IMESupport](https://github.com/chikatoike/IMESupport) to keep the candidate list always following the caret. 

> It is called Candidate List or Candidate Window or just simply Candidates.

Thanks for clarifying.

> Meanwhile, you can set "draw_centered" to false in your user settings to workaround it.

It works like a charm! Thanks very much! @felixhao28

**Comment by gaochangyu** [comment]
@et2010 If you still care, there could be another workaround for this problem. 
I'm using sublimetext3 on Ubuntu 14.04 and also meet the same chinese input problem. I used a solution from https://github.com/lyfeyaj/sublime-text-imfix and fixed the chinese input problem. However, when I type chinese in markdown with markdown editing, the candidates does not follow the caret like what happed to you.
I happed to find this solution uses a dirty workaround to find the caret position with the caret rectangle width. And the markdown editing plugin changed the caret property. So I tried changing the caret setting of markdown editing to:
```json
"caret_style":"smooth",
"caret_extra_width":1
```
It worked for me. Maybe you can try changing the caret setting and it will work.
