### ISSUE TITLE
Error after removal

### ISSUE THREAD

**Issue by Fastidious** [SublimeText-Markdown/MarkdownEditing#414]
I no longer wanted to use MarkdownEditing, so I removed the package. Yet now, each time I open a markdown (.md, .markdown) file I get the following error (and the editor changes its background to white):

```
Error loading colour scheme Packages/MarkdownEditing/MarkdownEditor-Dark.tmTheme: 
Unable to open Packages/MarkdownEditing/MarkdownEditor-Dark.tmTheme
```

How to correct this? Thanks!

**Comment by Ishmaeel** [comment]
Open an *.md file, dismiss the error message, navigate to Menu > Preferences > "Settings - Syntax Specific" and remove everything from the user settings that you did not add yourself. Save. Restart.

Me, I had no manual changes there, so I just emptied out the user settings.

**Comment by felixhao28** [comment]
Sublime caches all previously opened file with last used syntax. You can `ctrl+shift+p` and `syntax: markdown` to switch back to default markdown highlight. If the option does not appear, open Preferences -> Settings and remove "Markdown" from "ignored_packages".
