### ISSUE TITLE
Linking to File on Local Drive

### ISSUE THREAD

**Issue by vongoh** [SublimeText-Markdown/MarkdownEditing#417]
Is there a way to link to a file on our local drive from within a document in MarkDownEditing?   Or is this not possible due to O/S restrictions, thanks.

**Comment by felixhao28** [comment]
I think you can use `file://` protocal. I am not sure how/whether it works on every platform or browser.

**Comment by vongoh** [comment]
Thanks - I used this syntax in the markdown document:

`[Test](file://N:\[PATH]\[TO]\[FILE]\[FILENAME].md)`

- I opened it up in a Chrome browser preview
- clicked the link

It opens it up in the browser as a text file, ie. it shows the markdown code, hashmarks etc.  If I can find a Chrome extension that interprets markdown to HTML in the browser on the fly that would be useful.  

I was hoping that there would be a way to click the link and open the file up in Sublime.  Interestingly, clicking the link in Chrome wants to open it in the same tab.  If I CTRL-click or right click to New Tab it opens either in the same tab,  or opens up to `about:blank`

**Comment by felixhao28** [comment]
> If I can find a Chrome extension that interprets markdown to HTML in the browser on the fly that would be useful.

There is a `Markdown Preview` plugin for ST3 I use everyday. There also seems to be plenty of similar Chrome extensions.

> I was hoping that there would be a way to click the link and open the file up in Sublime.

Well the best you can do is initiate a download action and choose open when it prompts.

````html
<a href="file://N:\[PATH]\[TO]\[FILE]\[FILENAME].md" download>Test</a>
````
