### ISSUE TITLE
⌘-Tab for folding conflicts with app switcher

### ISSUE THREAD

**Issue by slambert** [SublimeText-Markdown/MarkdownEditing#418]
I noticed that section folding is linked to `⌘-Tab` and unfolding to `⌘-⇧-Tab` in OS X. (Image of README below)

<img width="707" alt="screen shot 2017-02-05 at 4 10 43 pm" src="https://cloud.githubusercontent.com/assets/67271/22629940/8a2cc2c6-ebbe-11e6-8045-2f8c25c1f6a0.PNG">

These conflict with the OS X app switcher.

Reviewed issue #171, but didn't see this discussed. I'm surprised it hasn't been brought up before so maybe I'm missing something?

**Comment by felixhao28** [comment]
It must've been a typo. The key binding for OSX is same as for PC (Shift+Tab and Ctrl+Shift+Tab\.)
