### ISSUE TITLE
Switch bullet type changes from unordered list to ordered list

### ISSUE THREAD

**Issue by alecsatin** [SublimeText-Markdown/MarkdownEditing#420]
_Using Sublime Text 3126_

New to MarkdownEditing, so it may be that I am misunderstanding how this command is supposed to work.  If I select an unordered list, like this:

```
- list item 1
- list item 2
- list item 3
```

and then select MarkdownEditing: Switch List Bullet Type, I end up with this:

```
1. list item 1
2. list item 2
3. list item 3
```

Instead of:

```
+ list item 1
+ list item 2
+ list item 3
```

Once it switches to an ordered list (1., 2., 3., etc), there is no way to get it back to an unordered list without doing it manually (e.g. select the columns with Shift-Right Click then do a multiple replace).

This is really a small thing in such a really great package (MarkdownEditing) but it is confusing.  

Thanks for any help or explanation.
Alec

**Comment by felixhao28** [comment]
Switch bullet type is meant for switching a list's type between ordered list and unordered list. I can confirm there is a code defect preventing an ordered list to be converted back to unordered one.

To cycle through unordered bullet type, we don't have that feature yet. However you can workaround by selecting the whole list and then press `tab` (for switch bullet+indent) followed by `shift+tab` (for unindent).
