### ISSUE TITLE
jsx syntax support

### ISSUE THREAD

**Issue by craigcosmo** [SublimeText-Markdown/MarkdownEditing#422]
when I jsx or js extension for jsx syntax, all the code in the page got messed up. 

<img width="883" alt="screen shot 2017-02-19 at 10 28 39 am" src="https://cloud.githubusercontent.com/assets/538657/23098979/5469b3da-f68e-11e6-82ff-357e9893fd34.png">

**Comment by felixhao28** [comment]
You need to install Babel plugin for JSX highlight.

**Comment by craigcosmo** [comment]
I got that as well. Doesn't help

<img width="1049" alt="screen shot 2017-03-01 at 10 14 17 am" src="https://cloud.githubusercontent.com/assets/538657/23444474/ec0c48f2-fe67-11e6-8bed-95d7836f061e.png">

**Comment by felixhao28** [comment]
Have you disabled the vanilla JavaScript package?

**Comment by craigcosmo** [comment]
@felixhao28  that will work but it will also disable sublime's javascript autocomple and suggestion.

**Comment by felixhao28** [comment]
You can still use `ctrl+space` to trigger the suggestion list.

**Comment by craigcosmo** [comment]
That's not what I mean. 

to reproduce: enable js package. Then create a new .js file, then try typing `if` suggestion for keyword `if` will show up

If disable js package, and do the same step as above, suggestion for keyword `if` will not show up, even you press ctrl+space, a suggestion box will show up but there is not suggestion for `if` keyword.

**Comment by fzaninotto** [comment]
I have the same bug, I din't understand why it's closed...
