### ISSUE TITLE
Auto-Preview mode

### ISSUE THREAD

**Issue by dessalines** [SublimeText-Markdown/MarkdownEditing#424]
It would be really nice to have an auto-preview mode for links, bolds, and italics. Basically it just shows what it would look like, until you click the text, upon which it expands the markdown(IE the italics, bold, or link). 

This is the killer feature that programs like [Typora](https://typora.io/) have that makes it the best markdown editor. Its basically a WYSIWYG editor, until you click the word or phrase that contains the formatting.

**Comment by felixhao28** [comment]
It can be easily achieved with some other plugins:

1. Markdown Preview (https://packagecontrol.io/packages/Markdown%20Preview)
1. Livereload (https://packagecontrol.io/packages/LiveReload)

Install them if you haven't. Then 
1. Open Palette
1. LiveReload: Enable/Disable Plugins
1. Enable Simple Reload.

Now open palette and choose "Preview in Broswer" and you will get a WYSIWYG editor.

**Comment by felixhao28** [comment]
Anyway I think it is good to include that in the readme. Thanks for bringing it up.

**Comment by dessalines** [comment]
I knew about markdownpreview, but its not a WYSIYWG editor. It's an uneditable preview of your content in a browser window. Typora is an in place WYSIWYG editor.

**Comment by felixhao28** [comment]
With the combination of LiveReload it is.

**Comment by felixhao28** [comment]
Oh I see what you mean. Well, I don't think sublime supports that.

**Comment by ttscoff** [comment]
This just isn't possible in Sublime. Live preview is the closest you'll 
get. If you're on a Mac, I do suggest checking out Marked 2, for which 
there's also a Sublime plugin/build system: http://marked2app.com

(full disclosure, that's my app)

-Brett

**Comment by marcus-at-localhorst** [comment]
Here is a new way of Markdown preview directly in Sublime Text:
https://packagecontrol.io/packages/MarkdownLivePreview
Without having any insight/knowledge about the code, it looks like it _could_ be possible to have something like inline edit (I don't think so, but who knows). 
This plugin renders Markdown to a its own syntax, thus it should be possible to make this view editable.

> the preview view (the view on the right) is a specific syntax (called — sorry for the originality — `MarkdownLivePreviewSyntax`)

![](https://packagecontrol.io/readmes/img/23e1908ae6f76be37e87ed0fea18e163e39d445b.gif)

**Comment by felixhao28** [comment]
> Here is a new way of Markdown preview directly in Sublime Text:

Yeah I tried that one but somehow ST hanged and became unresponsive. So I didn't recommend that. Since you can get it working so may it's just me.

**Comment by marcus-at-localhorst** [comment]
@felixhao28  It's not perfect and large documents do indeed hang/not render. Interesting concept though.
