### ISSUE TITLE
Scheme not applied to markdown files

### ISSUE THREAD

**Issue by ap4125** [SublimeText-Markdown/MarkdownEditing#425]
I have two files open in ST3. One is a markdown file, the other is an ordinary text file.

I apply a MarkdownEditing scheme. What happens is that the scheme is applied to the non-markdown file. The scheme is NOT applied to the markdown file.

If I try to apply any other scheme, say Monokai Extended, or any other scheme, the scheme is applied to the non-markdown file, and the markdown file remains without a scheme.

Actually, this happens not only for text files, but all other files, like php files.

What should I do?

**Comment by SheepGoesBaa** [comment]
You have to change it in the configuration files. See https://github.com/SublimeText-Markdown/MarkdownEditing/blob/master/README.md#configuration

**Comment by ap4125** [comment]
I see. Thanks for pointing it out.
