### ISSUE TITLE
Code block fencing is broken with stateful constructs in 3129

### ISSUE THREAD

**Issue by djspiewak** [SublimeText-Markdown/MarkdownEditing#430]
![broken stuffs](http://i.imgur.com/fblnXgA.png)

A slightly more minimal text example is as follows:

~~~markdown
```scala
object Foo {
}
```

Testing?
~~~

The Scala mode uses the stateful `set` directive in the new `sublime-syntax` format as part of handling the `object` definition, and the very first state transition follows `object Foo`.  I'm pretty sure this is what is screwing up MarkdownEditing's embedding.  Note that, oddly, the embedded syntax continues to work until the end of the fenced block, even though the background styling indicating that fenced block is broken.

My current workaround is tossing the following after every broken fenced block:

~~~markdown
<!--
```
-->
~~~

That's not great, but it works.

I suspect this is a bug in Sublime itself, but I thought I would file it here first to confirm.

**Comment by djspiewak** [comment]
Any updates on this?

**Comment by djspiewak** [comment]
@felixhao28 I found the bug.  It's an issue in the Scala mode (which I maintain, so… whoops).  Can confirm that when the now-linked PR is merged, the bug as described in the OP goes away.  Would you like me to close this issue now?  Or should I wait until the PR is merged?

**Comment by felixhao28** [comment]
Let's wait for the PR to be merged before closing. Maybe your case is not same as other "unclosed code scope" issue on code blocks.

**Comment by djspiewak** [comment]
Oh I'm pretty sure it is (I have a merged version locally and it's working), it's just that the bug meant that we were "closing" the outer code block, rather than anything controlled by the Scala mode. So I was literally popping off your stack, which naturally messed everything up.

So it's almost like the opposite of an unclosed block: it was closed too early.

**Comment by felixhao28** [comment]
Oh that makes sense. Let's close it then.
