### ISSUE TITLE
How to use the snippets with MarkdownEditing?

### ISSUE THREAD

**Issue by Edenharder** [SublimeText-Markdown/MarkdownEditing#435]
The first question is how to set the scope of new created snippet to MarkdownEditing? Does
```
<scope>text.html.markdown.multimarkdown, text.html.markdown</scope>
```
work?

The second question is that it seems that we cannot use [the default snippets](https://github.com/SublimeText-Markdown/MarkdownEditing/tree/master/snippets) by default. Should we change something in the setting of MarkdownEditing?

**Comment by felixhao28** [comment]
> Does ... work?

It should work. Take a look at https://github.com/SublimeText-Markdown/MarkdownEditing/tree/master/snippets for example.

> we cannot use the default snippets by default.

The default Markdown package is disabled upon MDE installation because it causes conflicts with MDE.
