### ISSUE TITLE
Feature Request: Color Scheme Option

### ISSUE THREAD

**Issue by MrPoetry** [SublimeText-Markdown/MarkdownEditing#436]
I _love_ MarkdownEditing. I personally don't like the color schemes that come with it; I prefer my own custom color schemes. I have successfully specified my preferred color schemes in MarkdownEditing's User Prefs, but to switch back and forth between my custom light and dark themes now requires (as far as I can tell) editing that User Prefs file manually. It would be wonderful to be able to specify a MarkdownEditing User Preference to use whatever ST3-wide color scheme is currently selected.

P.S. I am currently extracting the MarkdownEditing Package, and commenting out the color scheme lines in the .tmTheme files, but it's a minor pain to *have* to do that every time the package updates.

**Comment by felixhao28** [comment]
Most color schemes out there are made for coding. Markdown however is not a programming language. So themes for markdown should be focusing on document writing experience. There are a few differences for document writing from coding:

* Writing focus more on content than grammar-level structural correctness
    - This means grammar structures should be dimmed or even hidden without extra attention.
    - And it also means authors need to focus on the current line instead of glittering colorful baubles all around.
* People don't switch visual context too often when writing. On the other hand, navigating through code files, documents and web searches are quite often during coding.
    - This means the color should be muted and somewhat dull to avoid fatigue.
* The document should be somewhat readable. You should be able to quickly scan the markdown like rendered text and skip unimportant details.

Here are the examples proving my theory:

Monokai:
![image](https://user-images.githubusercontent.com/2417391/27680081-3c0a9b4a-5ced-11e7-873e-68e802a6c69d.png)

Material:
![image](https://user-images.githubusercontent.com/2417391/27680118-50e8ca28-5ced-11e7-95d5-87e99165f16c.png)


MarkdownEditor-ArcDark (my favorite)
![image](https://user-images.githubusercontent.com/2417391/27680048-1d99f570-5ced-11e7-94de-c2271fc16a37.png)

So defaulting to a built-in color scheme makes sense to me.

I've just added a command to change the color scheme (`MarkdownEditing: Change color scheme...`), trying to address this issue. Given the subjective nature of this issue, I'd like to hear from more people on this.

**Comment by slhck** [comment]
I think this can be closed, no? Thanks for offering the option to change the color scheme despite there being opinionated defaults (which makes sense the way you explained it).

**Comment by davidbonnet** [comment]
Not until there is a way to tell MarkdownEditing to use the default theme from the user preferences (e.g., setting `color_scheme` to `null` could imply that but currently just disables the theme).

**Comment by mahiki** [comment]
I am confused by the resolution here: 

- For other syntax color themes the user-defined .tmTheme files that live in the ./Pacakges/User/ folder are available to be found alongside the defauts in the command palette 
- In Markdown Editing the Command Palette can access `MarkdownEditing: Change color scheme...`, however only the default .tmTheme color schemes are discovered, even if some user-defined MarkdownEditing tmTheme files are saved in the Sublime ./Packages default location.

**Wouldn't the simple solution be to have MarkdownEditing discover syntax files (.thTheme) in the ./User file as well?** Perhaps adding a path is all that would be needed.

**Comment by mahiki** [comment]
> Most color schemes out there are made for coding. Markdown however is not a programming language. So themes for markdown should be focusing on document writing experience. There are a few differences for document writing from coding:

Its not necessary to examine the reasoning of people who want to alter the syntax highlighting or customize the default `MarkdownEditor-Dark.tmTheme`. 

Typical behavior through the Sublime ecosystem is that a User-defined version of a configuration/preference/settings file overrides the package default settings.

In my use-case, I altered the .tmTheme file to fade out the `#` headings symbol when in a markdown headings scope, making the headings text more distinct. Again -- the reasoning is not important, lets just empower the users to make customization.

Can we have User-defined versions of package files be found?

**Comment by deathaxe** [comment]
> Wouldn't the simple solution be to have MarkdownEditing discover syntax files (.thTheme) in the ./User file as well? Perhaps adding a path is all that would be needed.

Next release will look for _MarkdownEditor-[whatever you want].sublime-color-scheme_ in any package.
