### ISSUE TITLE
Feature request: provide syntax highlighting for clojure/lisp

### ISSUE THREAD

**Issue by Kshitiz-Sharma** [SublimeText-Markdown/MarkdownEditing#439]
Markdown editing provides syntax highlighting for other languages such as Java, bash, sql etc, but for clojure it does not. 

Example snippet:
```clojure
(defn functionName
    [numbers]
(/ (apply + numbers) (count numbers)))
```

**Comment by felixhao28** [comment]
lisp is already supported. Clojure support will be released in the next version. Thanks for reporting.
