### ISSUE TITLE
linkify local links

### ISSUE THREAD

**Issue by jbshirk** [SublimeText-Markdown/MarkdownEditing#444]
This plugin enhancement would turn Sublime in to a Markdown wiki:

Show links to existing local .md files as blue hyperlinks, missing files as red links. Clicking the link opens the file in a new tab. 

So far I really have not found anything out there that does this. I would not really care about prettyfying the links, just knowing they aren't dead, and being able to navigate them would do.

**Comment by felixhao28** [comment]
Try [Open URL plugin](https://github.com/noahcoad/open-url).
![a](https://user-images.githubusercontent.com/2417391/27017429-e7fe3ad8-4f5a-11e7-9333-88b850461cc3.gif)

**Comment by felixhao28** [comment]
> Show links to existing local .md files as blue hyperlinks, missing files as red links.

The syntax highlight is static. So I don't think we can support dynamic highlight.
