### ISSUE TITLE
Headings not bolded after font change

### ISSUE THREAD

**Issue by hearsayongit** [SublimeText-Markdown/MarkdownEditing#445]
I am hoping this has a simply solution. I changed the "Preferences-sublime.settings" so that my font would be Garamond across all projects. However, when I did this, I lost bold functionality in MarkdownEditing. 

How can I fix this? I have attached some screen shots.

Thanks for your help.
<img width="388" alt="screen shot 2017-06-11 at 9 57 45 pm" src="https://user-images.githubusercontent.com/29363304/27016840-9488d21e-4ef1-11e7-9924-ade07fc38749.png">
<img width="339" alt="screen shot 2017-06-11 at 9 58 48 pm" src="https://user-images.githubusercontent.com/29363304/27016844-982c1340-4ef1-11e7-9ddf-819c121a5c83.png">

**Comment by felixhao28** [comment]
Duplicated #288 

You can use a mono-spaced font for now until Sublime fix this.
