### ISSUE TITLE
DarkTheme doesn’t apply

### ISSUE THREAD

**Issue by 4sStylZ** [SublimeText-Markdown/MarkdownEditing#446]
Hello,

I have installed Markdown Editing. (Great package btw),
And I have pasted this :

```
{
    "color_scheme": "Packages/MarkdownEditing/MarkdownEditor-Dark.tmTheme"
}
```

on GFM and standard Markdown settings.

I have changed my personal theme too to the markdown editing dark theme one and that change all my syntax highlighting on many extensions like php or json but that doesn’t work on .md files.

Any suggestion ?

![image](https://user-images.githubusercontent.com/7487411/27543378-54552f36-5a8a-11e7-93ed-ed2ad8eefd86.png)

**Comment by felixhao28** [comment]
You need to use `Markdown.sublime-settings` instead of `Markdown (Standard)`. The previous is for GFM which is used by default.

**Comment by felixhao28** [comment]
A simpler way is to click Preferences -> Settings - Syntax Specific
