### ISSUE TITLE
markdown folding must ignore `#` in code blocks

### ISSUE THREAD

**Issue by mahiki** [SublimeText-Markdown/MarkdownEditing#447]
Markdown folding is the best -- super-feature that quickly converts a file to its own table of contents.

Currently however any heading fold is terminated by a code block that contains the hash symbol `#` as a comment character, such as bash, python, ruby, perl, postgres, powershell, et al.

The comment is interpreted as a heading level 1 by the markdown folder.  Better to ignore a `#` that is part of a code block scope.

## Example
*this is literal text in a Markdown document, followed by the MarkdownEditor folded version. I am trying to:*
**MarkdownEditing: Fold Level 3 Sections** 

```
### Level 3 Heading
Discussion about this point regarding a coding syntax. And more.

```bash
echo "this is a code block section in a bash syntax scope"

cut -d$'\t' -f2- datafile.txt

# this is a bash comment explaining something in the result from previous command

grep "sandwich" datafile.txt

# this is a bash comment, should be folded under level 3
``` <this is end of code block in markdown document>

And here is more discussion.
This should also be folded into the 'Level 3 Heading' above. 
However the first bash comment is interpreted
as a level 1 heading and therefore is not folded.
```

### Result of *MarkdownEditing: Fold Level 3 Sections*
```
### Level 3 Heading <...folded...>
# this is a bash comment explaining something in the result from previous command

grep "sandwich" datafile.txt

# this is a bash comment, should be folded under level 3
\```
```

**Comment by felixhao28** [comment]
Ha, good catch. I will fix that.

**Comment by mahiki** [comment]
Just checked some of my markdown files -- ***brilliant!*** 
T H A N K   Y O U U U U U !!!
