### ISSUE TITLE
Folding: problems with "next heading" shortcut keys and movement

### ISSUE THREAD

**Issue by reagle** [SublimeText-Markdown/MarkdownEditing#450]
Two problems:

1. `show_fold_all_sections` shows two entries for "find previous heading" (of any or of same level). Why no entries for "find next heading"?
2. `super+shift+pageup` works great for moving to previous headings. I don't know what `super+shift+pagedown` is doing; it seems to select everything but first and last line.

**Comment by felixhao28** [comment]
> show_fold_all_sections shows two entries for "find previous heading" (of any or of same level). Why no entries for "find next heading"?

`show_fold_all_sections` sets the filter text to "fold" (to show all folding-related commands) and "find previous heading" somehow fits the filter text. If you are looking for "find next heading", try some other filter text like "find heading".


> super+shift+pageup works great for moving to previous headings. I don't know what super+shift+pagedown is doing; it seems to select everything but first and last line.

I don't have a Mac at hand to test that but my guess is `super+shift+pagedown` conflicts with some OSX keybindings. You can try mapping goto_next_heading command to another keybinding (the following is default value):

```json
    { "keys": ["super+ctrl+pagedown"], "command": "goto_next_heading", "args": {"same_level": true}, "context":
        [
            { "key": "setting.mde.keymap_disable.goto_next_heading", "operator": "not_equal", "operand": true },
            { "key": "selector", "operator": "equal", "operand": "text.html.markdown", "match_all": true }
        ]
    },
    { "keys": ["super+shift+pagedown"], "command": "goto_next_heading", "args": {"same_level": false}, "context":
        [
            { "key": "setting.mde.keymap_disable.goto_next_heading", "operator": "not_equal", "operand": true },
            { "key": "selector", "operator": "equal", "operand": "text.html.markdown", "match_all": true }
        ]
    }
```

**Comment by reagle** [comment]
> show_fold_all_sections sets the filter text to "fold" (to show all folding-related commands) and "find previous heading" somehow fits the filter text. 

Somehow?  So you don't expect it to actually show?

> I don't have a Mac at hand to test that but my guess is super+shift+pagedown conflicts with some OSX keybindings. 

Even when I remap it to keys that don't use `shift` the bug persists. {"same_level": true} works fine. It is {"same_level": false} that selects all text except first and last line.

sublime-text-dev: 3141

**Comment by reagle** [comment]
Same bug in: sublime-text: 3126 (OSX Sierra)

**Comment by felixhao28** [comment]
> Somehow? So you don't expect it to actually show?

No.

> Even when I remap it to keys that don't use shift the bug persists. {"same_level": true} works fine. It is {"same_level": false} that selects all text except first and last line.

I will need a mac to debug it. I can't repro it on windows. Does this issue happen to every document for you or just specific ones?

**Comment by reagle** [comment]
> Does this issue happen to every document for you or just specific ones?

Good question. It happens on my markdown files that have yaml front matter. I think there is something about the first line `---` throwing it off?

```
---
title: 'DRAFT: 06 Health'
author: Joseph Reagle
date: 2016
suppress-bibliography: true
md_opts_: --quash-citations --style-csl chicago-fullnote-bibliography.csl
...
```

**Comment by reagle** [comment]
All my heading levels ones had been folded, but hitting `super+shift+pagedown` expands the last section and selects everything but the first and last line.
<img width="1145" alt="screen shot 2017-07-20 at 8 25 46 am" src="https://user-images.githubusercontent.com/596814/28417226-48796224-6d25-11e7-8d47-72858ad09d2c.png">

**Comment by felixhao28** [comment]
Yes it's caused by the front matter syntax. `---` can also be used in markdown for level-2 titles so it confuses the parsing script.

**Comment by reagle** [comment]
Since YAML blocks (in pandoc) begin with 3 hyphens, do you object to changing your setext-style header parsing and linting to **four** or more dashes or equals (up from three)? That would be an easy fix.

Another option would be to ignore the first line of the file `if text[0:4] == '---\n'` but that would probably be buggier and would still break on other yaml blocks.

**Comment by reagle** [comment]
moving to `if re.match(r'^(-{4,}|={4,})$', m.group()):` in `folding.py` and `decide_title.py` works well for me. (Would it require a change to `lint.py`?) However, I then encounter a new bug where a fold section get unfolded as I move down the headings, but I'll hold on that until we resolve this one.

**Comment by felixhao28** [comment]
Don't worry I will work on a solution to this.
