### ISSUE TITLE
Sublime Text build3126 Ctrl+Win+R invalid

### ISSUE THREAD

**Issue by anjia0532** [SublimeText-Markdown/MarkdownEditing#451]
sublime text version : build 3126
os version : win10 1703
markdownEditng version : v2.2.3

create a new markdown file named 'demo.md',the first time ,<kbd>Ctrl</kbd>+<kbd>Win</kbd>+<kbd>R</kbd> it's ok,but the 2 time ,it's dont work.

the <kbd>Ctrl</kbd>+<kbd>Win</kbd>+<kbd>V</kbd> it's ok

**Comment by felixhao28** [comment]
Can you share your actions in detail? What do you have in clipboard? Does demo.md has any text on it? Where did you ctrl+win+r in the document?

**Comment by anjia0532** [comment]
@felixhao28 thanks for your reply. 

1. create a new markdown file named `demo.md`
2. copy `http://nginx.org/` and write `nginx` to `demo.md` and selected this word.
3. <kbd>Ctrl</kbd>+<kbd>Win</kbd>+<kbd>R</kbd>,
```markdown
[nginx][]
[nginx]: http://nginx.org/
``` 
the first time ,it was vaild.
4. copy `https://www.google.com` and insert `google` after the `[nginx][]` and selected that.
```markdown
[nginx][]
google
[nginx]: http://nginx.org/
```
5. <kbd>Ctrl</kbd>+<kbd>Win</kbd>+<kbd>R</kbd>,it's invaild in this time

**Comment by felixhao28** [comment]
Thanks! I can repro this issue with your steps now. It's definitely a bug. I will take a look at it.

**Comment by anjia0532** [comment]
How should I fix it by myself before the v2.2.4 released? i cannot find the references.py in sublime packages dir

**Comment by felixhao28** [comment]
@anjia0532 if you are using Package Control, it's zipped in %AppData%\Roaming\Sublime Text 3\Installed Packages

**Comment by felixhao28** [comment]
Check this out for manual installation:
https://github.com/SublimeText-Markdown/MarkdownEditing#manual-installation

**Comment by anjia0532** [comment]
thanks for your reply. i got it but it's not in `%AppData%\Roaming\Sublime Text 3\Installed Packages`,i use the [Everything](http://www.voidtools.com/) search `MarkdownEditing` in my disk ,i found the `Sublime Text 3\Data\Installed Packages\MarkdownEditing.sublime-package` and unzip it to modified `references.py`. it's work. thanks again : ) .
