### ISSUE TITLE
code fencing with java syntax highlighting is broken

### ISSUE THREAD

**Issue by evanemolo** [SublimeText-Markdown/MarkdownEditing#454]
Bug: dark gray background indicating a code blocks bleeds outside fenced-in code block. See attached screenshot.

Expected: dark gray background should stop at bottom backtick fencing. 

<img width="715" alt="screen shot 2017-07-25 at 4 56 09 pm" src="https://user-images.githubusercontent.com/1220668/28593439-53714604-715a-11e7-907c-ed26a1f83259.png">

**Comment by felixhao28** [comment]
I think you are missing colons in your construstor

**Comment by evanemolo** [comment]
@felixhao28 that was the issue. thank you!
