### ISSUE TITLE
Provide golang highlighting support in snippets

### ISSUE THREAD

**Issue by Kshitiz-Sharma** [SublimeText-Markdown/MarkdownEditing#456]
The plugin doesn't seem to provide highlighting when I insert a \```go or ```golang snippet in my document. Please consider this as a feature request.

Or else, is there a way of configuring it with other plugins that I'm not aware of?

**Comment by felixhao28** [comment]
> Or else, is there a way of configuring it with other plugins that I'm not aware of?

Highlighting in code blocks? No.
