### ISSUE TITLE
Disable link highlighting

### ISSUE THREAD

**Issue by lrdegeest** [SublimeText-Markdown/MarkdownEditing#457]
When links span a line the empty space gets highlighted: 

![screen shot 2017-08-23 at 10 51 59 am](https://user-images.githubusercontent.com/10857097/29622472-897e7d9a-87f1-11e7-8577-b274a2050437.png)

Very distracting. How do you disable link highlighting? 

The same goes for the yaml. The "---" delimiters highlight the entire line as well.

**Comment by deathaxe** [comment]
That's a combination of 2 core issues

- https://github.com/sublimehq/sublime_text/issues/218.
  Related with #395
- https://github.com/sublimehq/sublime_text/issues/3674
  Related with #349

**Comment by deathaxe** [comment]
None can be fixed by this package.
