### ISSUE TITLE
Provide kotlin highlighting support in snippets

### ISSUE THREAD

**Issue by Kshitiz-Sharma** [SublimeText-Markdown/MarkdownEditing#458]
Kotlin is now a popular language for JVM. Its popularity would now grow exponentially, because Google has declared it to be the official language for development of apps on Android.

https://www.theverge.com/2017/5/17/15654988/google-jet-brains-kotlin-programming-language-android-development-io-2017

Please consider this as a feature request and provide highlighting support for \```kt and \```kotlin snippets

Thanks

**Comment by Kshitiz-Sharma** [comment]
@felixhao28 Is it working for you? I have updated the package to latest version v2.2.4. (I can see the new code in `MarkdownEditing.sublime-package` when I open it with zip viewer). But the \```kt snippets still appear without highlighting.

Golang has started working.

**Comment by felixhao28** [comment]
Have you installed Kotlin package for sublime? MDE does not come with any additional syntax parsers except MD itself. It only mark certain code snippets with proper scope and expect Sublime will handle it.

**Comment by Kshitiz-Sharma** [comment]
@felixhao28 Yes, that was it. Working now. Thanks for this awesome plugin!
