### ISSUE TITLE
Is there a keyboard shortcut for toggling GFM tasklist items done/undone

### ISSUE THREAD

**Issue by dahanbn** [SublimeText-Markdown/MarkdownEditing#462]
I was just wondering what is the best way to toggle the status of GFM tasklist items from `[ ]` (open) to `[X]` (done) or in the other direction. 

Has MarkdownEditing a builtin function for that?

**Comment by felixhao28** [comment]
No. There are some related discussions in #239

**Comment by deathaxe** [comment]
Duplicate of #589
