### ISSUE TITLE
After upgrade from 2.2 to 2.2.4, I cannot see GFM in syntax options

### ISSUE THREAD

**Issue by 61t** [SublimeText-Markdown/MarkdownEditing#463]
I got this issue in both mac and windows. 

![image](https://user-images.githubusercontent.com/13398892/30218781-f7671dc4-9487-11e7-9be8-b0514987307c.png)

**Comment by 61t** [comment]
I prefer to use GFM syntax as it's easy to embed code in my md file.

**Comment by 61t** [comment]
Also if possible, I would like to rollback to 2.2 before it is fixed. Please let me know how can I do that.

**Comment by 61t** [comment]
Hi Boss, any update?

**Comment by felixhao28** [comment]
Let me guess, you are using ST2 instead of ST3?

**Comment by felixhao28** [comment]
In v2.2.4, I switched to the new Sublime Syntax Definition which won't work in ST2 or old version of ST3. I highly recommend you upgrade your ST for the features and patches to come in future updates, but you can always revert to v2.2.3 (0d38b40fe726f206f992a0df41793c58356e4949) as a backup option.

To do so, you need to download the v2.2.3 version (https://github.com/SublimeText-Markdown/MarkdownEditing/releases/tag/2.2.3) and extract it to the package folder.

**Comment by felixhao28** [comment]
If you choose to update, you need Build 3103 or higher.

**Comment by 61t** [comment]
That's clear. Thank you. I will rollback to 2.2.3 for now, and leave a feedback here. Actually I use both ST2 and ST3. ST2 is main editor and ST3 is a temp editor. Awesome plug-in and thanks again. I will move to ST3 as main editor soon or later. 


By the way, I really need a feature that can add photo(e.g. shared link from dropbox) into MD document and see preview easily(by hovering mouse on the link, I can see the preview). 
If you happen to know something about it in ST family, please let me know. Thanks in advance.

**Comment by 61t** [comment]
I get my 2.2.3 back by download zipped file (https://github.com/SublimeText-Markdown/MarkdownEditing/releases/tag/2.2.3) and unzip it to package folder (/Users/<your user name>/Library/Application Support/Sublime Text 2/Packages/MarkdownEditing  in MAC OS X). Be sure to backup this folder first before replacement. 

Thanks author again and good luck to everyone.
