### ISSUE TITLE
2.2.4 Doesn't recognize open markdown documents: They are Plain Text until I manually select

### ISSUE THREAD

**Issue by aviris** [SublimeText-Markdown/MarkdownEditing#464]
Not sure if anyone else has as many tabs open as I do, but freaked out a bit when I opened ST3 today and none of my markdown documents had any sort of highlighting. 

Restarted a couple times - no help.

Noticed that all the _open_ files were listed as Plain Text. Specifying their type as Markdown (GFM & multi also works).

New files open as expected, so it may not be a huge deal, but it is a pain for me to use that selection list for all the files. 

If it is a simple re-check of open documents after setup, it would be a nice fix. If not, maybe some warning that re-opening Sublime Text is not enough, you either have to close each document and re-open them or re-select your markdown variant as the Syntax

**Comment by felixhao28** [comment]
This might be true. I changed the syntax definition from old .tmlanguage to the new .sublime-syntax format. This probably caused Sublime to not see them as the same.

At least to fix it you only need to select the syntax again.

**Comment by felixhao28** [comment]
Closing this issue for now due to lack of activity.
