### ISSUE TITLE
disable keybindings of some keys

### ISSUE THREAD

**Issue by faridcher** [SublimeText-Markdown/MarkdownEditing#465]
ctrl+1...6 is used to switch between groups in sublime. I don't want markdown editing to override this keybinding. Is there a way to disable this?

In general, I think, it is much better to define the keybindings at ST3 level instead of hard-coding them in the code behind.

thanks

**Comment by felixhao28** [comment]
Sublime Text does not allow user to opt out a key binding from a plugin. However as an easy fix, you can just put the original key bindings into your MDE user keymap file:

```
	{ "keys": ["ctrl+1"], "command": "focus_group", "args": { "group": 0 } },
	{ "keys": ["ctrl+2"], "command": "focus_group", "args": { "group": 1 } },
	{ "keys": ["ctrl+3"], "command": "focus_group", "args": { "group": 2 } },
	{ "keys": ["ctrl+4"], "command": "focus_group", "args": { "group": 3 } },
	{ "keys": ["ctrl+5"], "command": "focus_group", "args": { "group": 4 } },
	{ "keys": ["ctrl+6"], "command": "focus_group", "args": { "group": 5 } },
	{ "keys": ["ctrl+7"], "command": "focus_group", "args": { "group": 6 } },
	{ "keys": ["ctrl+8"], "command": "focus_group", "args": { "group": 7 } },
	{ "keys": ["ctrl+9"], "command": "focus_group", "args": { "group": 8 } },
```

Into Preferences->Package Settings->Markdown Editing->Markdown GFM Settings - User

```
[
 (paste here)
]
```

**Comment by faridcher** [comment]
That worked. Anyway, I don't think typing a couple of pound sign is a big deal :-)

thanks
