### ISSUE TITLE
Markdown GFM option has disappeared

### ISSUE THREAD

**Issue by drkvogel** [SublimeText-Markdown/MarkdownEditing#466]
After recent update to 2.2.4, the Markdown GFM option has disappeared on all of my machines (Windows and Linux)

**Comment by felixhao28** [comment]
Duplicate #463 ?

**Comment by drkvogel** [comment]
Yes, rollback to 2.2.3 fixed this, as per https://github.com/SublimeText-Markdown/MarkdownEditing/issues/463#issuecomment-328611481
