### ISSUE TITLE
I don't get a "Markdown: linebreak"  syntax highlighting

### ISSUE THREAD

**Issue by dahanbn** [SublimeText-Markdown/MarkdownEditing#470]
Sometimes I use the Markdown: linebreak syntax (two blank spaces) at the end of a line to specify a linebreak. 

I didn't get a special syntax highlight for that with Markdown Editing color schemes. Do I have to enable something to get that behaviour?

**Comment by felixhao28** [comment]
Is this a documented usage? Two spaces to indicate a line break?

**Comment by GiovanH** [comment]
Yes, this is a core part of the markdown syntax. Two spaces followed by a newline indicates a line break without a paragraph break.
