### ISSUE TITLE
Github style comments are not recognized

### ISSUE THREAD

**Issue by maximegariel** [SublimeText-Markdown/MarkdownEditing#471]
The end of the Github style comments `<!--- comment --->` are not picked up by the syntax highlighter. See example below

![screen shot 2017-09-15 at 3 12 39 pm](https://user-images.githubusercontent.com/5765549/30505264-7e66b62c-9a28-11e7-9d37-e09ec83b061e.png)

**Comment by felixhao28** [comment]
I can confirm Github supports three dash comment. But is there a specification for this?
