### ISSUE TITLE
Selective Wrap for Lists

### ISSUE THREAD

**Issue by storrgie** [SublimeText-Markdown/MarkdownEditing#474]
Is it possible to have word_wrap enabled, but selectively disable it for lists?

Not requesting as a feature, just curious to know if its something I'm not spotting in the configuration default.

**Comment by felixhao28** [comment]
I don't think so.

As an alternative, you can manually insert line breaks in a paragraph and the lines still render into one single paragraph in HTML.

**Comment by deathaxe** [comment]
Basically ST wraps `text` but doesn't `source`, but I don't think it's a good idea to scope lists as soruce code.
