### ISSUE TITLE
Win10 ST3 3143 Error loading syntax file

### ISSUE THREAD

**Issue by dlidstrom** [SublimeText-Markdown/MarkdownEditing#475]
I get this error upon installing this package:

![st3_markdownediting](https://user-images.githubusercontent.com/371713/30639814-b146793e-9e00-11e7-8efe-55b58c16655c.PNG)

Any more details you need? Thanks!

**Comment by zwjun** [comment]
+1

**Comment by DmitriyK-CPKIO** [comment]
This refers to a built-in Markdown package of ST3, not MarkdownEditing.

**Comment by VictorChen** [comment]
same issue after installing `MarkdownEditing`

**Comment by dlidstrom** [comment]
Thanks for clarifying, Mark. Everything does seem to work fine.
