### ISSUE TITLE
Cut and copy in html?

### ISSUE THREAD

**Issue by cougil** [SublimeText-Markdown/MarkdownEditing#476]
Hi!
I'm starting to use this plugin (with the latest version of Sublime) for editing some Markdown files and I found that if you use the shortcut for cut & copy paste, the content is copied as a HTML file, but not only the selected text, it seems that all the file content it is copied. 
I removed the package and installed again without no luck. 
Any ideas about what is going on?
Best,

**Comment by felixhao28** [comment]
It's the first time I have heard of such behavior. MDE does not have any logic interfering with copying and pasting. Have you tried a clean-installed Sublime Text to reproduce this issue?

**Comment by felixhao28** [comment]
Closing for now as not reproducible. Feel free to reopen if the same issue strikes again.
