### ISSUE TITLE
draw_centered and line_numbers not working

### ISSUE THREAD

**Issue by akotulu** [SublimeText-Markdown/MarkdownEditing#479]
Sublime Text
Version 3.0, Build 3143

"draw_centered": false,
"line_numbers": true,

[Editor](http://existanz.planet.ee/temp/MarkdownEditingEditor.png)
[Settings](http://existanz.planet.ee/temp/MarkdownEditingSettings.png)

**Comment by DmitriyK-CPKIO** [comment]
Select not Markdown GFM (lower right corner), but standart Markdown. You have Markdown settings file opened, not MD GFM.

**Comment by DmitriyK-CPKIO** [comment]
One more «default» config in addition to `Preferences.sublime-settings`? I disagree.

**Comment by felixhao28** [comment]
> Also a base config file would solve problems

That would be too counter-intuitive for people who only uses one flavor of the syntax.

> Maybe change the naming of these markdowns

Naming right now is fine. We use the official names for the three supported flavors. GFM is the default because it has the most features.
