### ISSUE TITLE
Feature Request: Fenced Code Shortcut

### ISSUE THREAD

**Issue by tajmone** [SublimeText-Markdown/MarkdownEditing#480]
It would be nice to have a keyboard shortcut to quickly create fenced code blocks.

Example, I type at the beginning of a line the desired language name (eg: `python`), then while the cursor is still on that line I press the keyboard shortcut (eg: <kbd>Ctr</kbd><kbd>SHIFT</kbd><kbd>F</kbd>, for "fenced") and the original line becomes:

~~~~~~~~~ markdown
~~~ python

~~~
~~~~~~~~~

... with either tildas or backticks (whichever covers best most markdown flavours).

I'm not sure about the exact number of tildas this should produce. Three is neater to look at, but it would cause problems if the code block contains itself fenced code; 80 would be safer, but also too long as it would cause the language name to either wrap or be out of sight when working with dual panel.

Anyhow, this shortcut could be a real time saver, especially on non-US keyboards which don't have a tilda nor a backtick key — forcing to either use Alt-codes (on Windows) or define some custom shortcut to emit a tilda or backtick.

**Comment by felixhao28** [comment]
To add this as a default feature, I will need more voices on it. Before that happens, you can try adding this to `Preferences->Key Bindings`

```json
    { "keys": ["ctrl+alt+c"], "command": "insert_snippet", "args": {"contents": "~~~$SELECTION\n$0\n~~~"}, "context":
     [
         { "key": "selector", "operator": "equal", "operand": "text.html.markdown", "match_all": true },
         { "key": "selector", "operator": "not_equal", "operand": "markup.raw", "match_all": true }
     ]
    }
```

**Comment by tajmone** [comment]
Thanks a lot!

When I first wrote this issue I wasn't aware of the snippet's existence, later on I've discovered it by chance. The snippet does simplify a lot creation of fenced blocks on keyboards without tilde and backtick.

The tip you provided above is very useful, thank you.

> To add this as a default feature, I will need more voices on it. 

Sure. Hopefully they'll be, after all I guess that most of this package users are likely to be coders, and use  fenced code quite a lot. But then again, maybe users with more experience than me with Sublime Text (still learning how to use many of its features) might preferr to handle shortcuts on their own.

**Comment by felixhao28** [comment]
As a coder, you probably noticed no vastly used IDE/editors in this world provides a shortcut for inserting a "if" block, which exists in nearly every advanced programming language. That is my personal defense for not adding it as a default shortcut or command.

Still, you said on a non-US keyboard does not have a backtick or tilda key. That's another issue. I remember a Russian keyboard layout user complaining shortcuts are not working well. I totally admit and understand the issue is causing dissatisfaction, but it should be Sublime Text's dev team's work. We cannot know or change key-mappings on plugin level. Before that, you can find some keyboard mapping software to map unused keys (like F-keys) to backtick and tilda.

**Comment by tajmone** [comment]
I agree with you @felixhao28 , the root of the problem is that most standards are still USA-centric, and the "Unicode revolution" didn't really change the fact that hardware keyboards are still derivates of the ASCII oriented keyboard (again ASCII standing for _American_ Standard Code for Information Interchange).

I can't say it for sure, but I think that actually **most** keyboards _don't_ have tilde and backtick keys on them (at least not both); some don't even have the pipe "`|`" key. So many standards are well intended, but then fail on simpler considerations. Markdown is surely human readable, but tildas and backticks make less human-_writable_ than expected for certain linguistic groups — needless to say, there is no way you're going to find a laptop with a US-keyboard in Italy (and this probably applies to most countries also).

Surely, one can resort to hacks or tools to remap keys;.

What is really needed is a paradigmatic shift that rethinks standards on a more international scale. Unicode is a good example of such thinking, yet it has taken so long to come into place, and hardware keyboards are still a barrier in many cases .

English is a language with no special accents or diacritic points, so it leaves more physical space on the keyboard for extra symbols. Languages with more consonants, or vowels with diacritics and accentss tend to consume up all keyobard extra spaces, sacrificing symbols like the tilde (instead of currency symbols 😡!!). Quite annoying that in my keyboard I have the Euro symbol, the Dollar and even the Sterlin!! — but not the tilde and the backtick! Looks like keyboards aren't designed with coders in mind, surely not as much as online-shoppers 😉 !

The real problem at hand here is not the occasional tilde or backtick (an Alt Code here and there is fine), but the fact that markdown uses them _really_ a lot. For the backtick, I've set SublimeText to display it via <kbd>Alt Gr</kbd>+<kbd>'</kbd>. For the tilde I still use the Alt code "96" on numeric keypad.

Anyhow, snippets are a good workaround to similar problems — at least in SublimeText,

**Comment by felixhao28** [comment]
> ... but also Chinese (1st), ...

In China we just use US keyboards with a Latin-Chinese mapping standard called "PinYin" (you learn it since kindergarden) and a software called IME to help with typing. Disappointing, I know. But to be fair there is no way to [map thousands of characters into a keyboard](http://image.baidu.com/search/index?tn=baiduimage&ps=1&ct=201326592&lm=-1&cl=2&nc=1&ie=utf-8&word=%E6%B4%BB%E5%AD%97%E5%8D%B0%E5%88%B7).

> there is no way you're going to find a laptop with a US-keyboard in Italy (and this probably applies to most countries also).

True. I studied in Japan and I had to place an oversea order to buy a US keyboard.

> but I haven't yet come across a "programmers" keyboard that solves these issue.

I wonder if it's profitable to start a company selling keyboard extensions to non-US keyboard users.

> I wonder how multi-languages translators do?

When I was in Japan, I need to type English, Japanese and Chinese. Chinese uses US keyboard with IME so the real issue is Japanese. Luckily there is a Japanese IME that converts Latin pronunciation into Japanese characters, e.g. "konichiwa<space>" into "こんにちわ". This is not the native way of typing and it's slow and error-prone, but it worked for me.

For professionals, [they seem to use dual keyboards](https://www.smartling.com/blog/welcome-every-translators-nightmare-dual-keyboard-layouts/).

> ... the fact that markdown uses them really a lot.

I will revisit the Russian keyboard issue and see if there is any simple snippets to workaround it. And summarize the solution in the homepage.

**Comment by tajmone** [comment]
Thanks for the prcious info @felixhao28 , I haven't the slightest clue about Chinese and Japanese alphabets and how they are handled by keyboards, and these references can turn out very handy when considering i18n support in software development.

> I wonder if it's profitable to start a company selling keyboard extensions to non-US keyboard users.

... probably the future of keyboards is going to be touch-screen technology. Unicode is to ample to allow for a truely full-unicode hardware keyboard — not just for the amount of minimum keys it would require, but for the actaul symbols to display on keys. Tablets offer nice touch-screen virtual keyboards that can be anything you want. Surely, typing on touch screen is not like typing on a real keyboard, but maybe someone will come up with a keyboard that has a small display on each key, so that the actual letters/symbols shown on the keys can change according to the chosen locale.

>  Luckily there is a Japanese IME that converts Latin pronunciation into Japanese characters, e.g. "konichiwa" into "こんにちわ". This is not the native way of typing and it's slow and error-prone, but it worked for me.

I've seen something similar for Arabic, based on a widespread Arabic "slang" that is used to represent Arabic letters with latin characters, so that any chat application can be used to write in Arabic. 

This only works if you don't use vowels — originally vowels where never written in Arabic (or Hebrew), the reader will supply them by his knowledge of the language, but in modern Arabic some vowels need to be written (above or below the consonants). This optionality of vowels is often a huge problem when writing Arabic text parsers.

From what I've seen, standardization of international languages tends to cut-down languages features to accomodate the needs and limits of technology. For Arabic, this meant reducing considerably the elegance of the actual "calligraphy" (Arabic is cursive-only): in hand-written Arabic there are more than 400 glyphs to represent how consonants merge into each other elegantly (in some calligraphies even more than 600); in computer representations of Arabic these have been cut down to their bare minimum basic shapes (less than a 100) to fit in Unicode. A couple of these modern glyphs are considered syntactically wrong by some linguists, and special softwares have been created to allow using the natural Arabic alphabet (six separate fonts files to represent the full set of glyphs).

Standardizing languages is not an easy task, because languages are a "living thing", and usually no standard will make everyone happy. I guess Arabic is a particularly difficoult case, especially since there still hasn't even been reached an agreement on the actual number of letters in its alphabet: 28 or 29? — for centuries Arabic linguists have disputed over a certain glyph, wehter it's a consonant or not, if it belongs to the letters, vowels or is something else (and there good reasons for this dispute). Of course, keyboards have a key for it, and people know how and when to use this glyph. Wikipedia will firmly state there are 28 letters in the Arabic alphabet, but any classical grammar text or thesaurus will open with a warning note about this unsolved dispute.

I believe that something similar as happened with other languages too, I often see references to "modern Chinese" in software documentation.

**Comment by felixhao28** [comment]
Yes I have seen Arabic calligraphy a lot, on blankets, on the wall of a Muslim restaurant, and on the front door of a mosque. I thought such calligraphy is just for aesthetic/theological value, not something you write in markdown, or even family letters.



> standardization of international languages tends to cut-down languages features to accomodate the needs and limits of technology

As a text editor plugin, we can only achieve within the limitations of technology. Reaching beyond that is not our goal. Thanks for sharing the information.



> I believe that something similar as happened with other languages too, I often see references to "modern Chinese" in software documentation.

It is very true. Just like ancient English, ancient Chinese contains characters now practically deprecated. In total, there are nearly 100,000 characters while only thousands of them (<10%) are seen in today's daily life. To reduce the cost of building fonts, most rare characters are not included. And [Unicode only contains some of them](https://en.wikipedia.org/wiki/CJK_Unified_Ideographs). This constantly causes trouble for computer systems when, for example, someone's name contains rare characters.
