### ISSUE TITLE
Use new embed rule on latest dev builds

### ISSUE THREAD

**Issue by djspiewak** [SublimeText-Markdown/MarkdownEditing#484]
Dev build 3153 introduced a new construct, `embed`, which allows for considerably more robust embedding of nested modes.  Use of this construct would make MarkdownEditing behave considerably better in the context of partially-valid stateful embeddings.  For example:

~~~markdown
```scala
type Foo =
```

I'm still a code block!
~~~

The ` ``` ` terminator is not captured by MarkdownEditing *today* because of the extra context pushed onto the stack by the `=` token inside the Scala mode.  `embed` fixes this issue.

**Comment by felixhao28** [comment]
This is wonderful! I tried it and it works perfectly in markdown fenced code blocks. I will certainly update fenced code parsing with the new `embed` action once Build 3153 is rolled out on production channel.

**Comment by theSouthSea** [comment]
version 2.27.There is still this problem. How to deal with it?

**Comment by felixhao28** [comment]
![image](https://user-images.githubusercontent.com/2417391/45147606-e281dc80-b1f7-11e8-932a-313a8a4ef58a.png)

I don't see anything wrong.
