### ISSUE TITLE
Windows 10 Fall Creators Update Breaks Key Bindings?

### ISSUE THREAD

**Issue by tajmone** [SublimeText-Markdown/MarkdownEditing#488]
After the Windows 10 Fall Creators Update (**1709**) the following key bindings stopped working in MarkdownEditing:

<kbd>Ctrl</kbd><kbd>Win</kbd><kbd>V</kbd> — Creates or pastes the contents of the clipboard as an inline link on selected text.

Anyone else experienced this problem? Any ideas if now Win 10 has assigned these keys to some other task? or how to fix it?

**EDIT**: I've found this link which lists all Windows keyboard shortcuts:

https://support.microsoft.com/en-ph/help/12445/windows-keyboard-shortcuts

... here <kbd>Ctrl</kbd><kbd>Win</kbd><kbd>V</kbd> is listed as bound to "**Open shoulder taps**" (I'm not sure if this is a new binding introduced with Fall Creators Update or not)

Anyhow, other MarkdownEditing <kbd>Win</kbd> key bindings seem to work. Also, changing my user settings for MarkdownEditing  Key Bindings to use Shift instead of Ctrl for this (ie: <kbd>Shift</kbd><kbd>Win</kbd><kbd>V</kbd>) works:

``` json
    // run paste as link command on selected text
    { "keys": ["shift+super+v"], "command": "reference_new_inline_link", "context":
        [
            { "key": "setting.mde.keymap_disable.reference_new_inline_link", "operator": "not_equal", "operand": true },
            { "key": "selector", "operator": "equal", "operand": "text.html.markdown", "match_all": true }
        ]
    },
```

I wonder what has changed with this update.

**Comment by felixhao28** [comment]
How about changing it to `ctrl+alt+r` and `ctrl+alt+v`?

**Comment by jdhao** [comment]
I have also met with this issue. Changing `ctrl+super+v` to `ctrl+alt+v` works. For anyone interested. You can use [PackageResourceViewer](https://github.com/skuroda/PackageResourceViewer) to extract the package MarkdownEditing，then go to the directory of MarkdownEditing package，find the file named `Default (Windows).sublime-keymap`. In this file, change `ctrl+super+v`  to  `ctrl+alt+v`.
