### ISSUE TITLE
can we put the editing layout to left , not center? 

### ISSUE THREAD

**Issue by videni** [SublimeText-Markdown/MarkdownEditing#489]
![image](https://user-images.githubusercontent.com/4058341/33698574-70cef6bc-db48-11e7-8d28-0060396ab744.png)

**Comment by DmitriyK-CPKIO** [comment]
set `"draw_centered": false,` in the settings file for your markdown flavour

**Comment by videni** [comment]
@DmitriyK-CPKIO , thank you , it works
