### ISSUE TITLE
Html tags split over multiple lines and React jsx break formatting

### ISSUE THREAD

**Issue by DisasterMan78** [SublimeText-Markdown/MarkdownEditing#490]
If you have code samples that use HTML with attributes split over multiple lines, or React JSX formatting, the code is not correctly parsed.

![image](https://user-images.githubusercontent.com/2079401/33717250-228fb5f0-db51-11e7-907a-cd1feedc7ae7.png)

***src/js/components/Input.js***
```jsx
import React, { Component } from 'react';

export class Input extends Component {
  render() {
    return <input
             type="text"
           />
  }
}
```

![image](https://user-images.githubusercontent.com/2079401/33717264-2c5ee56a-db51-11e7-8541-0e6972cc2966.png)
***tests/App-test.js***
```js
describe('Input', () => {
  // it('should render', () => {
  //   ...
  // });

  it('should have an ID so labels can be paired', () => {
    const inputId = 'inputId',
          wrapper = shallow(<awe.Input inputId={inputId}/>);
    expect(
      wrapper.find('input').prop('id')
    ).to.equal(inputId);
  });
```

**Comment by felixhao28** [comment]
You need to first install `Babel` package and then disable the vanilla `JavaScript` package, as instructed on [its readme](https://github.com/babel/babel-sublime#advanced-usage). And then restart sublime text.

Another solution is #484 . But that will come after Build 3153 rolls out.
