### ISSUE TITLE
Removing Package Breaks Color Scheme

### ISSUE THREAD

**Issue by Kautenja** [SublimeText-Markdown/MarkdownEditing#493]
Hey I seem to be having an odd problem using this on my Mac. I wasn't a big fan of the display style and removed this package, but now I cant seem to edit any Markdown files and get bombarded with this error every time i try to save the file:

```
Error loading colour scheme Packages/MarkdownEditing/MarkdownEditor-ArcDark.tmTheme: Unable to open Packages/MarkdownEditing/MarkdownEditor-ArcDark.tmTheme
```

I am unable to change color schemes or even use SublimeText with Markdown until I reinstall MarkdownEditing. I've checked and the default Markdown package is no longer "disabled" when I remove MarkdownEditing, but something seems to not get restored when I remove the package.

**Comment by Kautenja** [comment]
Update, it seems to corrupt the default `Markdown` syntax selected from `View > Syntax > Markdown`. I can use other markdown syntax like MultiMarkdown and Markdown Extended, but returning to the default Markdown syntax raises the error message referenced above.

**Comment by lhoff** [comment]
+1

**Comment by lixplor** [comment]
+1 
Same issue.
After removing MarkdownEditing I got this error, too.

```
Error loading colour scheme Packages/MarkdownEditing/MarkdownEditor-Dark.tmTheme: Unable to open Packages/MarkdownEditing/MarkdownEditor-Dark.tmTheme
```

Using `set syntax multimarkdown` can fix the current md file, but not for all md files. This is not the good way to solve it

**Comment by felixhao28** [comment]
Huh this is actually problematic. The only clean solution I can see is to rename the language name in this package from `Markdown` to a custom name like `Markdown (GFM)`. But by doing so the update will break most people's syntax highlight (because they need to select the syntax manually).

For a short term solution, try removing `%APPDAT%\Sublime Text 3\Packages\User\Markdown.sublime-settings`.

**Comment by DanielSmedegaardBuus** [comment]
Thanks, @lixplor ! This worked for me, only I had to check all nested settings in the `Markdown Editing` preferences menu. I had three user preference files with the MarkdownEditing dark theme being used 😃.

# 🎄

**Comment by hmgqzx** [comment]
> Huh this is actually problematic. The only clean solution I can see is to rename the language name in this package from `Markdown` to a custom name like `Markdown (GFM)`. But by doing so the update will break most people's syntax highlight (because they need to select the syntax manually).
> 
> For a short term solution, try removing `%APPDAT%\Sublime Text 3\Packages\User\Markdown.sublime-settings`.

On Mac: 
`$ cd ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/`
`$ cat Markdown.sublime-settings`
```
{
	"color_scheme": "Packages/MarkdownEditing/MarkdownEditor-Dark.tmTheme"
}
```

**Comment by trss** [comment]
I'm using ST3 on Mac.

On removing, my color scheme for Markdown (and MultiMarkdown) has got stuck with Monokai. This is even though I have a custom color scheme set in my preferences.

And I don't find any Markdown.sublime-settings file.
Setting the Markdown specific color scheme to the custom color scheme doesn't help either.
