### ISSUE TITLE
color scheme documentation

### ISSUE THREAD

**Issue by icf20** [SublimeText-Markdown/MarkdownEditing#496]
from the documentation

> In order to activate the dark or the yellow theme, put one of these lines to your user settings file of the flavor (Packages/User/[flavor].sublime-settings):

> "color_scheme": "Packages/MarkdownEditing/MarkdownEditor-Dark.tmTheme",

placing that in the config file gives a error

**Comment by felixhao28** [comment]
sublime-settings file is a JSON. You need to write like this:

```JSON
{
	"color_scheme": "Packages/MarkdownEditing/MarkdownEditor-ArcDark.tmTheme"
}
```

A more recommended way is to (while having a MD file open) open command palette and `MarkdownEditing: Change color schemes...`
