### ISSUE TITLE
Linter does not ignore YAML front matter

### ISSUE THREAD

**Issue by truemoid** [SublimeText-Markdown/MarkdownEditing#498]
[markdownlint ](https://github.com/markdownlint/markdownlint) has option to ignore YAML front matter. This doesn't seem to work in the MarkdownEditing linter or is not implemented. The linter  thinks `---` on line 1 is a setex header, giving error code md002 and then additional errors throughout the document (e.g., md025 multiple top level headers).

**Comment by felixhao28** [comment]
I am thinking of deprecating this DIY linting script and use a more developed 3rd-party linter instead (e.g. markdownlint).
