### ISSUE TITLE
Tons of blank space when using "Word Wrap". When not, caret starts off at middle

### ISSUE THREAD

**Issue by r3faat1** [SublimeText-Markdown/MarkdownEditing#501]
When using "Word Wrap", the caret automatically indents like 6 - 8 spaces. Please see the picture below:
![image](https://user-images.githubusercontent.com/33644294/36065759-8990fe60-0e5c-11e8-9fe3-5873967a8aed.png)

When turning off Word wrap, the caret starts off in the middle:
![image](https://user-images.githubusercontent.com/33644294/36065768-b3c77fb0-0e5c-11e8-8be9-09c40c25ce74.png)

I am using Sublime Text 3.0 B:3143

**Comment by kulack** [comment]
Same version of Sublime text here. Similar behavior. The indent when word wrap is huge, and scales much larger as horizontal size grows.
However, when I turn off word wrap, everything is normal.

![image](https://user-images.githubusercontent.com/516613/36314493-a704742a-12fa-11e8-9077-a9528870a895.png)

**Comment by kulack** [comment]
FYI, On further testing, changing word wrap column to automatic fixes the problem. Not sure why a specific column was set anyway. Automatic is fine. Thanks!

**Comment by RefX32** [comment]
Same. Changing it to "automatic" fixes the problem for me. However, once I open the document again, it goes back to 80. Does anyone know a setting where I can set it to automatic by default?

**Comment by nadieenespecial** [comment]
Same problem, I just installed it

![screenshot from 2018-10-31 09-21-37](https://user-images.githubusercontent.com/43034851/47787695-6afb9580-dcee-11e8-9d05-ce53c35e449e.png)

**Comment by greyxray** [comment]
> Same problem, I just installed it
> 
> ![screenshot from 2018-10-31 09-21-37](https://user-images.githubusercontent.com/43034851/47787695-6afb9580-dcee-11e8-9d05-ce53c35e449e.png)

I see exactly the same with sublime 3.1.1 Built 3176, changing the wrap_width doesn't help

**Comment by FedericoStra** [comment]
You have to change the option `"draw_centered": false`. I really don't know why this package decided to mess so much with the user interface. That is just a terrible idea

**Comment by FedericoStra** [comment]
What I did to revert the awful overrides that this package introduces is add the following to my `Markdown.sublime-settings`:
```json
{
	"color_scheme": "Packages/Color Scheme - Default/Monokai.sublime-color-scheme",

	"tab_size": 4,
	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": false,
	"auto_match_enabled": true,

	// Layout
	"draw_centered": false,
	"word_wrap": "auto",
	"wrap_width": 0,
	"rulers": [],

	// Line
	"line_numbers": true,
	"highlight_line": false,
	"line_padding_top": 0,
	"line_padding_bottom": 0,

	// Caret
	"caret_style": "smooth",
	"caret_extra_top": 2,
	"caret_extra_bottom": 2,
}
```

This reverts the settings back to the original, default, standard, sane ones.

**Comment by kulack** [comment]
I'll take that. Thanks!

**Comment by greyxray** [comment]
@FedericoStra you mean the `Sublime Text 3/Packages/User/Markdown.sublime-settings` file? In my case the `Markdown GFM` syntax looks good but the `Markdown` doesn't - is this expected?
