### ISSUE TITLE
Feature Request: Smart Wrapping

### ISSUE THREAD

**Issue by tajmone** [SublimeText-Markdown/MarkdownEditing#503]
It would be really cool if MarkdownEditing could handly smartly ST's "Wrap Paragraph at Ruler/n characters" function in lists and blockquotes.

For example, let's take this long blockquote:

```markdown
> Lorem ipsum dolor sit amet, ea pro accommodare consectetuer, an autem scripta epicuri nec.
```

After using "Wrap paragraph at 72 characters", it becomes

```markdown
> Lorem ipsum dolor sit amet, ea pro accommodare consectetuer, an autem
scripta epicuri nec.
```

... which is ok (lazy syntax), but it would be preferable — for the sake of human readibility of the plain source document — a smarter formatting of the wrapped praragraph:

```markdown
> Lorem ipsum dolor sit amet, ea pro accommodare consectetuer, an autem
> scripta epicuri nec.
```

... preserving the `> ` at the beginning of lines.

Similarly, wrapping lists (both numbered and ordered):

```markdown
1. Lorem ipsum dolor sit amet, ea pro accommodare consectetuer, an autem scripta epicuri nec.
10. Lorem ipsum dolor sit amet, ea pro accommodare consectetuer, an autem scripta epicuri nec.
```

... currently produces:

```markdown
1.  Lorem ipsum dolor sit amet, ea pro accommodare consectetuer, an
autem scripta epicuri nec. 10. Lorem ipsum dolor sit amet, ea pro
accommodare consectetuer, an autem scripta epicuri nec.
```

... where the two list items are merged into one due to lack of markdown awareness of the text block being actually a list. So, currently, the elements in the list would have to be spaced:

```markdown
1. Lorem ipsum dolor sit amet, ea pro accommodare consectetuer, an autem scripta epicuri nec.

10. Lorem ipsum dolor sit amet, ea pro accommodare consectetuer, an autem scripta epicuri nec.
```

After wrapping them at 72 (using a single selection that embraces them all):

```markdown
1. Lorem ipsum dolor sit amet, ea pro accommodare consectetuer, an autem
scripta epicuri nec.

10. Lorem ipsum dolor sit amet, ea pro accommodare consectetuer, an
autem scripta epicuri nec.
```

... where a more human readable output would have been:

```markdown
1.  Lorem ipsum dolor sit amet, ea pro accommodare consectetuer, an autem
    scripta epicuri nec.

10. Lorem ipsum dolor sit amet, ea pro accommodare consectetuer, an
    autem scripta epicuri nec.
```

> __NOTE__ — I've intentionally used `1.` and `10.` in the above example, to remind the necessity of smart indenting in long lists. Besides, some markdown flavours support using specific numbers in lists, and if they don't they'll just treat all numbers alike.

Possibly, there are other cases where smart wrapping long blocks applies. These examples illustrate that if MarkdownEditing could implement smart wrapping in markdown documents it would allow to work nicely with markdown source docs — especially when converting from other formats — and produce a highly human readable source file.

For example, if you use pandoc to convert a document from markdown to markdown, what you get is cleaned up markdown document (even though you loose some things, like reference links, which are "flattened out" in the conversion process). If you invoke pandoc with the wrap option, you can see that it does a pretty smart job when it comes to wrapping lists and blockquotes — of course, pandoc is a full parser and benefits from an AST, which is not the case here. Nevertheless, I'm mentioning it since it represents a good example of what most users might expect in terms of human readable markdown source as a result of text manipulation done by MarkdownEditing.

**Comment by felixhao28** [comment]
Very cool suggestion. It will take some efforts though. Let's see if some passionate contributor is willing to implement it or I will find time some day.

**Comment by deathaxe** [comment]
Related with #301

**Comment by deathaxe** [comment]
Functionality available via [Wrap Plus](https://packagecontrol.io/packages/Wrap%20Plus) package.

**Comment by tajmone** [comment]
works like a charm!
