### ISSUE TITLE
Completely disable the light theme

### ISSUE THREAD

**Issue by revolter** [SublimeText-Markdown/MarkdownEditing#504]
For some reason, using this along [GhostText](https://github.com/GhostText/GhostText) causes the opened tab to use the light theme, even if I have currently set the dark one.

Is this caused by `GhostText` instead? As opening `.md` files correctly loads the dark theme.

**Comment by felixhao28** [comment]
A theme is set in settings. Unless GhostText changes the theme in settings, I cannot think of any reason that  it will not work.

Maybe because GhostText opens a tab in "Markdown" syntax instead of "Markdown GFM" where you actually set the theme? Just a wild guess.

**Comment by revolter** [comment]
Yep, it was opening it in "MultiMarkdown" syntax. Though changing the default syntax is broken, as described in https://github.com/GhostText/GhostText/issues/97.
