### ISSUE TITLE
Toggle commenting

### ISSUE THREAD

**Issue by JonasLTU** [SublimeText-Markdown/MarkdownEditing#505]
Hello,
And recommendations how to make Toggle comment function?
Also, maybe it is possible to have a custom comment tag, so that it adds/remove a maker in front of every line?

**Comment by JonasLTU** [comment]
There is a command now to add blockquote (selecting text and clicking ">"). It would be nice that it would work the same as toggle)comment function, so that you can add and remove with the same key,

**Comment by felixhao28** [comment]
> And recommendations how to make Toggle comment function?

Try `Ctrl + /`

> It would be nice that it (blockquote) would work the same as toggle

I don't think it is a commonly requested feature. Even so, please open another issue so other people can track by title.
