### ISSUE TITLE
Incorrect highlighting for code snippets with dynamic keyword

### ISSUE THREAD

**Issue by evil-shrike** [SublimeText-Markdown/MarkdownEditing#510]
If markdown markup contains a code snippet with csharp where `dynamic` keyword is used as return type all file highlighting is broken:

![image](https://user-images.githubusercontent.com/1203230/37108410-12809786-2248-11e8-95cf-cd690af47f3c.png)

Code:
```
\```cs
    public interface IObjectRepository
    {
        bool CanGetObjects(IGetObjectsRequest request);
        dynamic GetObjects(IGetObjectsRequest request);
    }
\```
```

**Comment by felixhao28** [comment]
Looks like a bug in the official C# syntax package. Please report to https://github.com/sublimehq/Packages/issues instead.
