### ISSUE TITLE
JavaScript syntax editing isn't correct when missing semicolons

### ISSUE THREAD

**Issue by zellwk** [SublimeText-Markdown/MarkdownEditing#514]
Hello, I write JavaScript without semicolons (Using Standard). 

The syntax highlighter used to work fine, but seems to be broken now: 

Before: 
![screen shot 2018-04-03 at 12 36 06 pm](https://user-images.githubusercontent.com/3607637/38229555-e7419148-373b-11e8-9993-1f7315346dc6.png)

How it should look like (but without the semicolon)
![screen shot 2018-04-03 at 12 36 13 pm](https://user-images.githubusercontent.com/3607637/38229567-f15932e4-373b-11e8-899a-d84ec39e1da6.png)

Can you point me in the right direction to fix this? Thanks! 

Using Sublime Build 3160.

**Comment by SCdF** [comment]
There is something pretty fundamentally broken with JS / JSON support with Markdown GFM right now:

![image](https://user-images.githubusercontent.com/583851/38308773-0fc2890e-3810-11e8-8913-c0999b325f8b.png)

**Comment by zellwk** [comment]
I reverted back to Sumlime 3143 and it worked fine. Hopefully waiting for a fix soon.

**Comment by benfrain** [comment]
Also seeing this issue in latest Sublime Dev build 3162

**Comment by felixhao28** [comment]
Well there is a risk when using the development build. I am arbitrarily assuming it is a regression on Sublime Text's side. Feel free to reopen this issue if any evidence is found otherwise.
