### ISSUE TITLE
Code Blocks in Comments: Broken Preview

### ISSUE THREAD

**Issue by tajmone** [SublimeText-Markdown/MarkdownEditing#517]
I've noticed that recently MarkdownEditing stopped showing properly code blocks inside blockquotes (as far as I can remember, it used to show them fine).

Example:

~~~~~ markdown
> Some code:
>
> ```php
> $foo = new Foo;
> ```
~~~~~

The PHP block isn't previewed as a code block — no darker background, no syntax highlighting, etc.

It looks like something has broken with a ST update.

**Comment by deathaxe** [comment]
While scoping it markup.raw might be possible syntax highlighting is nearly impossible due to the `>` markers.

**Comment by tajmone** [comment]
Scoping it should be enough, at least it stands out. I agree, syntax highlight would be hard, if indeed possible at all, due to the dependency on native syntaxes. I can't think of a way to strip out every leading `> ` from a line on the code block being fed to the other syntaxes.
