### ISSUE TITLE
Feature Request: Select a url and press < to make <> wrapping the url

### ISSUE THREAD

**Issue by Kotsuha** [SublimeText-Markdown/MarkdownEditing#518]
Currently if I select some words
```
foo bar baz
```
and press \`, it will wrap the words into
```
`foo bar baz`
```
It would be nice to have the same feature when pressing < on a selected url
```
http://www.example.com/
```
to make it into
```
<http://www.example.com/>
```

**Comment by ttscoff** [comment]
Ooh, +1
