### ISSUE TITLE
Broken highlighting after code fences

### ISSUE THREAD

**Issue by evil-shrike** [SublimeText-Markdown/MarkdownEditing#521]
There're cases when code highlighting is broken for some reason. 
It could be legit cases (code really isn't correct) or non legit - for example for `json` language I'm having:

![image](https://user-images.githubusercontent.com/1203230/39883966-04d4341e-5491-11e8-8b19-94239126532d.png)

Currently the only workaround is to remove language name from code block. But it's not ideal as the language can be used in other context where there's such issues with parsing. 

I'd suggest that closing fences `\`\`\`` should terminate code fence anyway.

Slightly related to #510. 
See discussion in https://github.com/sublimehq/Packages/issues/1534

**Comment by aeracode** [comment]
Can confirm

This breaks.

    ```js
    {  

    }
    ```

Found that additional quotes at the end of _code_ "fix" issue:

    ```js
    {  

    }``
    ```

**Comment by felixhao28** [comment]
Such issues are already fixed in 7c3ac548443fe4eb3935fb082cfbc707427690b7. It will require the latest ST3 release version to work. I am simply waiting for one or two weeks because the [update](https://www.sublimetext.com/blog/articles/sublime-text-3-point-1) is just released not long ago.
