### ISSUE TITLE
Code Brackets ended by sudo usage

### ISSUE THREAD

**Issue by UltimateSky** [SublimeText-Markdown/MarkdownEditing#522]
When using code brackets for bash, something like

```bash
sudo vi test.txt
```

will not be coded appropriately and will show such as this
![image](https://user-images.githubusercontent.com/13856563/40242278-d244fcfc-5a82-11e8-852f-59e978365f64.png)
Where the bracketing is ended after the word sudo for whatever reason.

![image](https://user-images.githubusercontent.com/13856563/40242359-16596130-5a83-11e8-840e-cfe11034ec03.png)
Standard commands work as indended, but sudo messes up the code for some reason.

It also appears that the sudo ends the blocking but keeps the highlighting going throughout the document as shown here:
![image](https://user-images.githubusercontent.com/13856563/40242425-44ec1fba-5a83-11e8-86ae-2e66d1a30565.png)

**Comment by felixhao28** [comment]
This has been fixed in this: 7c3ac54

The update will roll out this week.
