### ISSUE TITLE
Theme List Markup

### ISSUE THREAD

**Issue by mjknght** [SublimeText-Markdown/MarkdownEditing#523]
Hi there,

I have been attempting to make the bullets/numbers in lists bold, etc. Using `punctuation.definition.list_item.markdown` in the theme, I can affect the first bullet of each list, but I want to affect all bullets! Is this currently possible? If so, any help gratefully received.

Thanks in advance,

Mark

**Comment by felixhao28** [comment]
Works for me

![image](https://user-images.githubusercontent.com/2417391/40478407-8c6aede2-5f7b-11e8-936b-3104754d8f48.png)
