### ISSUE TITLE
Rename indent_list_item command to something else

### ISSUE THREAD

**Issue by dufferzafar** [SublimeText-Markdown/MarkdownEditing#530]
When creating lists, pressing `Tab` used to indent (`indent_list_item` command.) 

But that feature has stopped working for me.

I now need to select the line and press `Tab` (`indent_list_multiitem` command) to have it indented properly.

**Comment by felixhao28** [comment]
`indent_list_item` is only triggered when you press 'tab' on an empty list item, with the bullet and a space before caret and nothing after, like this:

```
* |
```

I don't remember there was another trigger.

**Comment by dufferzafar** [comment]
@felixhao28 Yes, that is exactly how I'm triggering it.

And I know that the command is being triggered because I have `sublime.log_commands(True)` in the sublime console. 

But, the list item is **not** being indented!

**Comment by felixhao28** [comment]
Hmm, sounds like a bug but will you share more information so I can reproduce it? Information includes:

1. Surrounding text
2. Sublime Text version
3. MarkdownEditing plugin version
4. OS

Or if you know python, you can mess around with [the source code](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/master/indent_list_item.py) and see where went wrong.

**Comment by dufferzafar** [comment]
1. Surrounding text: Nothing, really. I can open a new blank file - type `*` and press Tab. The command gets triggered, but the line doesn't indent.

2. Sublime Version: 3.1.1 Build 3176. But I remember this issue has been bugging me for a month or so (I just wasn't free to create a report.) 

3. MarkdownEditing Version: 2.2.7

4. OS: Manjaro, KDE. But I was on Kubuntu before and this was there too.

Yeah, I know Python and I'll look into the source now.

**Comment by dufferzafar** [comment]
Woah, this is a weird one.

~~So, I used [PackageResourceViewer](https://github.com/skuroda/PackageResourceViewer) to edit the `indent_list_item.py` file that you linked, and as soon as I open the file and save it _without even making any changes_, the bug disappears!~~ 

So, when I launch sublime text, and all the plugins get loaded for the first time. Then this bug occurs. As in, `indent_list_item` gets triggered but doesn't indent.

If I so much as save the file - triggering a reload of the plugin - the bug disappears. 

So the issue isn't with this code, per se. But somewhere else?

I'd like to point here, that `indent_list_multiitem` which is triggered when you have some text selected is working just fine, in all cases.

**Comment by dufferzafar** [comment]
@felixhao28 Any thoughts on why this could be occurring? and how I can fix it?

Most of my sublime text config is here: https://github.com/dufferzafar/sublime-text-3

**Comment by dufferzafar** [comment]
With great help from folks (OdatNurd & keith) at the Sublime Discord channel I was able to nail this down. 

OdatNurd suggested:

> Perhaps there is another plugin defining a command with the same name as the one from the plugin and it loads later, so it doesn't do what you want, but reloading that package file manually replaces the replacement

So I looked into Sublime's console log and found the culprit: [Restructured Text (RST) Snippets](https://github.com/mgaitan/sublime-rst-completion) also has an `indent_list_item` which overrides the one from this package.

Essentially, these two packages are incompatible as they implement commands with the same name.

Would you be willing to change the name of this command to something else?

RST Snippets was last updated many years ago. So I don't think there's any point in making an issue there. For the time being I'll look into editing the source myself. Will post the diff here later.

**Comment by felixhao28** [comment]
I see. It's the first time MDE's command conflicts with ones from another plugin. I will consider adding a prefix to all command names.

**Comment by felixhao28** [comment]
Honestly I thought Sublime Text would limit command namespace to one package so such issues should not happen.

**Comment by dufferzafar** [comment]
Yeah. So did I. This is why I was a bit surprised by this.

But I guess until this gets into Sublime core, the best way would be to
just prepend all commands with a package identifier of sorts, right?

**Comment by felixhao28** [comment]
Yes, but changing command name will very likely break user-defined hotkeys and snippets. I need to think of a more elegant solution.

**Comment by dufferzafar** [comment]
Oh, right. Well, this is certainly tricky then. For now, I've just disabled
that package.
