### ISSUE TITLE
install error by hand

### ISSUE THREAD

**Issue by WilliamShoww** [SublimeText-Markdown/MarkdownEditing#531]
I am download this zip and unzip it ,then copy it under packages and restart sublime,open one .m file , sublime tick a error  `error: Error loading colour scheme Packages/MarkdownEditing/MarkdownEditor.tmTheme: Unable to open Packages/MarkdownEditing/MarkdownEditor.tmTheme`, my sublime is sublime text3 and my system is win10. How to resolve the error

**Comment by WilliamShoww** [comment]
Yes,it showed by console.

**Comment by felixhao28** [comment]
Did you download the master branch?

**Comment by WilliamShoww** [comment]
I'm download from the Redme document Recommend

**Comment by deathaxe** [comment]
MDE 3.x no longer uses `*tmTheme` format. Hence closing.
