### ISSUE TITLE
Strikethrough text no longer dimmed

### ISSUE THREAD

**Issue by YRG999** [SublimeText-Markdown/MarkdownEditing#534]
Hi,
Love your product. For some reason, strikethrough text no longer shows up as dimmed. I can't remember in which version this changed, but it was recent. I'm using GitHub Flavored Markdown (GFM).

**Comment by shriramks** [comment]
- Facing the same issue (across all markdown flavours)
- The actual strikethrough syntax `~~` appears dimmed but text strikethrough does not happen
- Keystrokes from console:
```
hr evt: ~ (0x7e)
chr evt: ~ (0x7e)
chr evt: t (0x74)
chr evt: e (0x65)
chr evt: x (0x78)
chr evt: t (0x74)
chr evt: ~ (0x7e)
chr evt: ~ (0x7e)
```

Using "Sublime Text 3" on "MacOS High Sierra 10.13.3"

**Comment by felixhao28** [comment]
![image](https://user-images.githubusercontent.com/2417391/45750525-f3900c00-bc41-11e8-9276-564f1762520c.png)

Is there a more specific repro case?

**Comment by YRG999** [comment]
The text does not appear strike through as in your example. Here's an image:
<img width="395" alt="screen shot 2018-09-19 at 9 01 49 am" src="https://user-images.githubusercontent.com/16637430/45754879-dbd96900-bbea-11e8-8d70-11b7d2339e51.png">

**Comment by shriramks** [comment]
> ![image](https://user-images.githubusercontent.com/2417391/45750525-f3900c00-bc41-11e8-9276-564f1762520c.png)
> 
> Is there a more specific repro case?

@felixhao28  Not sure what you are looking for but will include where all I have been able to reproduce so far,
- all flavours
- all MDEditing colour schemes
- below is the custom settings I am using for GFM flavour
```
{
	"auto_match_enabled": true,
	"color_scheme": "Packages/MarkdownEditing/MarkdownEditor-ArcDark.tmTheme",
	"draw_centered": true,
	"extensions":
	[
		"md",
		"mdown",
		"txt",
		"md"
	],
	"highlight_line": false,
	"line_numbers": false,
	"line_padding_bottom": 2,
	"line_padding_top": 2,
	"mde.auto_increment_ordered_list_number": true,
	"mde.distraction_free_mode":
	{
		"mde.keep_centered": true
	},
	"mde.keep_centered": false,
	"mde.keymap_disable.fold_section": false,
	"mde.keymap_disable.goto_next_heading": true,
	"mde.keymap_disable.goto_previous_heading": true,
	"mde.keymap_disable.list_back_links": true,
	"mde.keymap_disable.make_page_reference": true,
	"mde.keymap_disable.open_home_page": true,
	"mde.keymap_disable.open_journal": true,
	"mde.keymap_disable.open_page": false,
	"mde.keymap_disable.reference_jump": true,
	"mde.keymap_disable.reference_new_inline_image": true,
	"mde.keymap_disable.reference_new_reference": true,
	"mde.list_indent_auto_switch_bullet": true,
	"mde.list_indent_bullets":
	[
		"-",
	],
	"mde.match_header_hashes": false,
	"mde.wikilinks.markdown_extension": ".md",
	"rulers":
	[
	],
	"word_wrap": true,
	"wrap_width": 120,
	"ignored_packages":
	[],    
    "trim_trailing_white_space_on_save": true,
    "draw_indent_guides": false,
}
```
Will anything in ^ clash with the strikethrough formatting?

**Comment by andrealati** [comment]
In case this is still open or anyone wonders. This worked for me: use the accent ` **and** the double tilde ~~: `~~foo~~`.

**Comment by YRG999** [comment]
@deathaxe thank you!
