### ISSUE TITLE
Code highlighting for typescript doesn't work

### ISSUE THREAD

**Issue by nguyendv** [SublimeText-Markdown/MarkdownEditing#541]
Environment:
- OS: Mac OSX 10.13.6
- SublimeText Version 3.1.1

Problem: Fenced code highlighting doesn't work for Typescript while it's working fine for other languages like C++ for Java.

![Screen shot](https://i.imgur.com/b5QWTNp.png)

**Comment by felixhao28** [comment]
Do you have typescript syntax package installed?

![image](https://user-images.githubusercontent.com/2417391/45992427-5c510b80-c0bc-11e8-92b5-1c1f22ddc4ef.png)

**Comment by nguyendv** [comment]
I've installed the TypeScript Syntax package, and it's beautiful now. Thank you very much.

One more question: would that be the case for other languages as well?

**Comment by felixhao28** [comment]
MDE does not contain any syntax definition for any language other than Markdown. It either uses the built-in syntax or syntax from third-party packages. Typescript does not come with Sublime Text itself, so you have to install a third-party syntax definition.
