### ISSUE TITLE
Error loading syntax file

### ISSUE THREAD

**Issue by cryarchy** [SublimeText-Markdown/MarkdownEditing#542]
I just installed MarkdownEditing on my Sublime Text editor **Version 3.1.1, Build 3176** and I get the error:
```
Error loading syntax file "Packages/Markdown/Markdown.sublime-syntax": Unable to read Packages/Markdown/Markdown.sublime-syntax
```
Kindly advice on how to resolve this.

**Comment by fxbenard** [comment]
Same issue

**Comment by felixhao28** [comment]
Close it as a duplicate of #485
