### ISSUE TITLE
Erro loading syntax file Markdown.sublime-syntax

### ISSUE THREAD

**Issue by jingyuexing** [SublimeText-Markdown/MarkdownEditing#546]

**Comment by jingyuexing** [comment]
error: Error loading syntax file "Packages/MarkdownEditing/Markdown.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit
Packages/MarkdownEditing/Markdown (Standard).tmLanguage: embed scope:source.css#rule-list-body could not be found
Packages/MarkdownEditing/MarkdownEditor.tmTheme
sublime:dev 3157

**Comment by jingyuexing** [comment]
![image](https://user-images.githubusercontent.com/19589872/48532768-b7dd8f80-e8dc-11e8-94e2-e0d10b14117c.png)

**Comment by jingyuexing** [comment]
this is error log：
Error loading scope:source.scheme: Unable to find syntax file for scope source.scheme in Packages/MarkdownEditing/Markdown.sublime-syntax
Error loading scope:source.swift: Unable to find syntax file for scope source.swift in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
Error loading scope:source.coffee: Unable to find syntax file for scope source.coffee in Packages/MarkdownEditing/Markdown.sublime-syntax
Error loading scope:source.less: Unable to find syntax file for scope source.less in Packages/MarkdownEditing/Markdown.sublime-syntax
Error loading scope:source.reason: Unable to find syntax file for scope source.reason in Packages/MarkdownEditing/Markdown.sublime-syntax
Error loading scope:source.Kotlin: Unable to find syntax file for scope source.Kotlin in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
no such context scope:source.c#preprocessor-practical-workarounds at line 1353 column 16 in Packages/MarkdownEditing/Markdown.sublime-syntax
error: Error loading syntax file "Packages/MarkdownEditing/Markdown.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit

**Comment by diimdeep** [comment]
```
Error loading scope:source.coffee: Unable to find syntax file for scope source.coffee in Packages/MarkdownEditing/MultiMarkdown.tmLanguage
```

**Comment by jeevank** [comment]
I have also started getting this error message today after using with no problem for months ("Error loading syntax file "Packages/MarkdownEditing/MultiMarkdown.sublime-syntax ... 25000 context sanity limit hit"). =

Have tried closing all markdown files and also reinstalling MarkdownEditing but it didn't help.

**Comment by jingyuexing** [comment]
I now know how to fix this Error,you can remove JavaScript-next package,this package syntax file conflict with other syntax files

**Comment by halfnibble** [comment]
For anyone coming to this for help, remove the JavaScript-Next package and go with a maintained alternative, like Babel JS.

**Comment by k7faq** [comment]
Please offer directions on removing this JavaScript-Next package. I did not find it installed in my fresh install of SublimeText3 and am not able to install this package.
