### ISSUE TITLE
Shift+tab folds instead of unindenting list even though fold is disabled

### ISSUE THREAD

**Issue by davidjosefson** [SublimeText-Markdown/MarkdownEditing#552]
## What is wrong
When disabling fold_section by adding `"mde.keymap_disable.fold_section": false` in the "Markdown.sublime-settings - User"-file Shift+Tab will still fold a section when trying to unindent a list item if the list has a subtitle-row without Markddown-#.

## How to reproduce
1. Create a .md-file
2. Add the following text:
```
# Title

Subtitle without hash
- List item 1
- List item 2
    + Indented list item 1
```
3. Put cursor after the `+ ` and before ´Indented list item 1´
4. Press Shift+Tab

### Expected behavior
Unindent the `+ Indented list item 1`-row, no folding.

### Actual behaviour
Folds the text to the first row (`# Title`)

### Workaround
Removing the `Subtitle without hash`-row or adding one or more `#` at the beginning (making it a proper subtitle) will make it work as expected.

## System info
MarkdownEditing v2.2.7
Sublime v3.1.1 Build 3176
MacOS v10.14.2

**Comment by MitchAllain** [comment]
For me this was an issue with my default markdown syntax, which was `Markdown Extended` from https://github.com/jonschlinkert/sublime-markdown-extended. To get this setting to load properly with that syntax, I added `"mde.keymap_disable.fold_section": false` to my `Preferences -> Settings (Syntax Specific)` file.

**Comment by revolter** [comment]
When will this be fixed?

**Comment by birla** [comment]
This suddenly started happening for me and its been severely impacting my productivity with MDE.

**Comment by felixhao28** [comment]
@birla @revolter Does MitchAllain's workaround work for you?

**Comment by deathaxe** [comment]
> "mde.keymap_disable.fold_section": false

Did nobody see **disable** in the name? The setting would need to be set `true` in order to disable that binding.

I am not very happy with `shift+tab` being used for folding at all.

Working on a fix to give unindent precedence.

**Comment by felixhao28** [comment]
> Did nobody see **disable** in the name?

Ah, this is the kind of thing that never gets noticed unless someone points it out.
