### ISSUE TITLE
Problem about bold/italic highlighting when using CJK

### ISSUE THREAD

**Issue by xjtu-blacksmith** [SublimeText-Markdown/MarkdownEditing#553]
Hello! I think I'm new to `markdown`, so I don't know what causes the problem shown in the screen-shot below. Is that a **syntax** mistake (*caused by myself*) or an **issue** of the plugin? CJK languages don't have spaces among each characters, and that's the problem.

I have browsed the issues before and haven't found the solution.

![my problem](http://images.cnblogs.com/cnblogs_com/xjtu-blacksmith/1391007/o_test_md.jpg)

MarkdownEditing: v.2.2.7, Sublime Text: v3.1.1, build 3176

**Comment by tomhundt** [comment]
**Image is unreadable/missing**.  Can't see what the problem is.

**Comment by xjtu-blacksmith** [comment]
I've reproduced the problem with latest version of MarkdownEditing under Linux.

![](https://img.xjtu-blacksmith.cn/20210403105817.png)

Note that "内容" is not bold here.
