### ISSUE TITLE
Bug I don't understand :(

### ISSUE THREAD

**Issue by kud** [SublimeText-Markdown/MarkdownEditing#554]
<img width="532" alt="image" src="https://user-images.githubusercontent.com/655838/53498462-ae9cbb00-3aa6-11e9-9a74-4320b60296fa.png">

**Comment by kud** [comment]
https://github.com/borela/naomi

**Comment by janiosarmento** [comment]
I don't use Naomi, and right now I'm facing the very same error.

**Comment by felixhao28** [comment]
Closing as a duplicate of #533
