### ISSUE TITLE
how to add new color theme

### ISSUE THREAD

**Issue by craigcosmo** [SublimeText-Markdown/MarkdownEditing#563]
I know how to switch markdown color theme, but how about adding new one

<img width="652" alt="Screen Shot 2019-06-20 at 8 58 02 PM" src="https://user-images.githubusercontent.com/538657/59854979-354f0e00-939e-11e9-9dc6-0e93ec635505.png">
<img width="570" alt="Screen Shot 2019-06-20 at 8 58 14 PM" src="https://user-images.githubusercontent.com/538657/59854983-36803b00-939e-11e9-937c-d52952db5d79.png">
I've got 6 themes in there, how would you add more?

**Comment by berxtjkl** [comment]
Thanks friend, I learned how to set another theme from your answer.
Hope you will find your answer as well.

**Comment by deathaxe** [comment]
Next release will come with a change which keeps global color scheme by default and suggests those builtins optionally only.

Additionally the color scheme selector will look for _MarkdownEditor-*.sublime-color-scheme_ files in all Packages, so adding new ones requires to put any such file in any _Package_ (3rd-party package) or your _User_ directory.
