### ISSUE TITLE
Markdown Lint rule MD028 is triggered incorrectly

### ISSUE THREAD

**Issue by morph626** [SublimeText-Markdown/MarkdownEditing#564]
If a document contains more than one block quote, MD028 is always triggered for all Markdown dialects unless text is placed in the line immediately after the preceding block quote.

This triggers MD028 no matter the Markdown dialect:
```
# 1 #

> quote 1

test

> quote 2
```

This does _not_ trigger MD028, that is no space between quote 1 and "test":
```
# 1 #

> quote 1
test

> quote 2
```

**Comment by GiovanH** [comment]
Have you confirmed that this is specifically an issue with MarkdownEditing and not (more likely) an issue with the linter https://github.com/DavidAnson/markdownlint?

**Comment by morph626** [comment]
Wow, I completely forgot I posted this. I do not have that installed (nor do I have https://github.com/jonlabelle/SublimeLinter-contrib-markdownlint installed, it seems to be the official way to use that linter in Sublime). This occurs when I use the command Markdown Lint from this package. From the documentation for MarkdownEditing I can't see that it is using David Anson's markdownlint, so that is why I think it is MarkdownEditing's own linter.
