### ISSUE TITLE
Support for R language?

### ISSUE THREAD

**Issue by JanaJarecki** [SublimeText-Markdown/MarkdownEditing#569]
Hi,

I read that MarkdownEditing reads the syntax specs from the language-specific specifications.

I have the R-IDE installed, which provides support for the prominent statistical language R (https://github.com/REditorSupport/sublime-ide-r), but in MarkdownEditing, unfortunately, the R language is not highlighted.

Is there anything I can do or am I lacking another configuration?

![image](https://user-images.githubusercontent.com/9809311/64921661-10fca500-d7c6-11e9-9c38-e4d60d14f2f7.png)

**Comment by deathaxe** [comment]
It's in the milestone branch and will be part of the next release.
