### ISSUE TITLE
#hashtag is rendered as a <h1>. It should require a space.

### ISSUE THREAD

**Issue by meta-meta** [SublimeText-Markdown/MarkdownEditing#572]
I am using #hashtags in my notes as I run them through a script to organize them. I also write them in markdown but when building using MarkdownEdit, `#hashtag` turns into  into `<h1>hashtag</h1>`.

See this related issue for markedjs: https://github.com/markedjs/marked/issues/201
and https://daringfireball.net/projects/markdown/syntax#header

**Comment by deathaxe** [comment]
MarkdownEditing doesn't provide a build script. Maybe you are using MarkdownPreview?

**Comment by meta-meta** [comment]
> MarkdownEditing doesn't provide a build script. Maybe you are using MarkdownPreview?

Oh, you're totally right. And it looks like the formatting is now fixed in MarkdownEditing's syntax highlighting (it does that at least, right?) It's also resolved in MarkdownPreview.

**Comment by meta-meta** [comment]
Hmm, actually I take that back, it's still trying to parse it as a header. The `#` is grey on the first tag of a line. These are underlined as well. I'm not sure what that means.
![image](https://user-images.githubusercontent.com/2626819/118201908-3ec44200-b41e-11eb-9995-907cc1af47c5.png)

Markdown lint:
```
line 3: MD018 - No space after hash on atx style header, no space
line 3: MD025 - Multiple top level headers in the same document, 2 found
```

**Comment by meta-meta** [comment]
And for posterity, now that I understand that these are separate packages, MarkdownPreview renders `<h1 id="tag-taggy-taggy2">tag #taggy #taggy2<a class="headerlink" href="#tag-taggy-taggy2" title="Permanent link"></a></h1>` when using vanilla markdown, which is totally off the wall IMO.

When using github or gitlab flavors, I get a result that looks more correct `<p>#tag #taggy #taggy2</p>`

**Comment by deathaxe** [comment]
My hunch is that the "required space" is something which was added "recently". ST's default syntax renders headers without space, too. The syntax definition of this package is IMHO even more out of date and breaks with dozens of markdown details.

Fixing all those syntax bugs is somewhat larger task. My goal is to try to improve ST's core syntax and extend it via this package to add more fenced code blocks, but this will take a while and will be compatible with ST4 only.
