### ISSUE TITLE
How to apply MarkdownEditing syntax to files with no file extension?

### ISSUE THREAD

**Issue by marcovirtual** [SublimeText-Markdown/MarkdownEditing#581]
I am trying to automatically apply MarkdownEditing syntax to all files with no file extension at all.

I have tried the following options:

1) Clicking the `Plaintext` button on the right corner of Sublime Text and choosing `Open all with current extension as...` , but the options for MarkdownEditing are disabled.

2) Changing the extensions of my `Markdown.sublime-settings` file to also include blank extensions, but this did not work either.

```
    "extensions":
    [
        "md",
        "mdown",
        "txt",
        ""
    ],
```

Is there any way to apply the MarkdownEditing syntax without having to do it manually?

Thanks in advance!

**Comment by tomhundt** [comment]
Notice the syntaxes are *all* disabled.  **This is a general Sublime question**, not one specific to this plugin: <https://duckduckgo.com/?q=sublime+set+default+syntax>

See, for example:  <https://stackoverflow.com/questions/40222760/how-to-change-the-default-syntax-highlighting-for-new-files-in-sublime-text>
