### ISSUE TITLE
Feature request: allow sublists level 4, and 5

### ISSUE THREAD

**Issue by Kshitiz-Sharma** [SublimeText-Markdown/MarkdownEditing#582]
Quite often I make use of sublists in my documents that go up to level 4 or 5.

```
- Level 1
  + Level 2
      > Level 3
          # Level 4
              * Level 5

```
By default, markdown editing only supports 3 levels. So it does not automatically add the next entry on pressing enter and does not indent/un-indent properly with Tab/Shift+Tab.

I tried to configure this by adding following to plugin configuration:
```
"mde.list_indent_bullets": ["-", "+", ">", "#", "*"]
```

However, it does not work. It seems the levels are hardcoded to 3 in the code.

Please consider removing the hardcoded value and taking the max indentation level from the size of the `mde.list_indent_bullets`

This should not break compatibility with [markdown standard](https://www.markdownguide.org/basic-syntax/#lists), as it does not assign different symbols to list entries of different levels.
```
 - Third item
    - Indented item
    - Indented item
```

Even if it does, perhaps it could be allowed in the editor for user flexibility, and could fail in the linter.

**Comment by Kshitiz-Sharma** [comment]
On second thoughts, not a good idea. 

Using `-`, `+` and `*` is the convention and using other symbols breaks in a lot of places. For instance, the markdown preview plugin would not render the list properly.

Just using `-` as level 4.

**Comment by stpn** [comment]
Is there a way to patch the package directly to add this? I would really like to add this functionality, but going into the settings/syntax and swapping all instances of *-+ to -+>#* (or in my case "-", "+", "●","○","■","□") didn't help
Thank you for any pointers to where that logic is.

**Comment by deathaxe** [comment]
Many key bindings and most macros and plugin modules depend on `*`, `+`, `-` to detect lists correctly. You'd need to patch all related bindings, macros and patterns in plugins. 

I doubt you want to do that.
