### ISSUE TITLE
Does this plugin automatically hard-wrap blockquotes?

### ISSUE THREAD

**Issue by reagle** [SublimeText-Markdown/MarkdownEditing#587]
I've never *seen* it happen -- I wish I did -- but my markdown files often have their blockquotes wrapped, meaning a long line is wrapped and each new line is prefixed with `>`. I prefer my markdown to be soft/dynamically wrapped by the editor and my other lines remain this way. Is this something this plugin would do? I checked my configuration settings and the issues but can't figure out why this is happening.

**Comment by deathaxe** [comment]
Haven't seen any code doing something like that.

**Comment by reagle** [comment]
I ended writing a stand-alone as well as a plugin to handle this. https://gist.github.com/reagle/dad4e59df7b73ba935556ac9638c1703

**Comment by deathaxe** [comment]
Thanks for sharing. I put hard wrapping quotes and joining lines on my todo list. I am sure, your code will help much.

**Comment by reagle** [comment]
If you're working on an ST specific plugin, the same (clumsy) regex appears in [this ST plugin](https://gist.github.com/reagle/3457fb5ef94e898f47777cb4065aa1f1). Whatever you do, I hope you'll share the results! 😄

**Comment by reagle** [comment]
Just an update, I'm working on a new draft and at some point I notice that my quotes are still being wrapped. Going from the first to the second:

```
> Pushshift has dealt with this problem by allowing users to request having their content removed from that service. However, users may be

> Pushshift has dealt with this problem by allowing users to request
> having their content removed from that service. However, users may be
```

**Comment by deathaxe** [comment]
Hitting `enter` would automatically prepend the second line with `> `, but MDE doesn't provide any other hard wrapping feature for block quotes.

**Comment by reagle** [comment]
Okay, must be something else then, not sure what. I'll close here.
