### ISSUE TITLE
Error loading syntax file

### ISSUE THREAD

**Issue by KaKi87** [SublimeText-Markdown/MarkdownEditing#591]
> Error loading syntax file "Packages/MarkdownEditing/Markdown.sublime-syntax": must specify escape with embed at line 604 column 7

Thanks

**Comment by ShijianXu** [comment]
Same error today. What happened?

**Comment by felixhao28** [comment]
Probably caused by the new update. I am reverting.

**Comment by felixhao28** [comment]
I have just reverted the code back to 2.2.7 (the reverted version will be displayed as 2.2.9). It will take some time for package control to pick up the update. Let's see if this fixes it.

**Comment by anebz** [comment]
Seems like it's fixed @felixhao28 thank you!

**Comment by deathaxe** [comment]
I've recently noticed that issue. It is fixed by https://github.com/SublimeText-Markdown/MarkdownEditing/pull/603

**Comment by Amparose** [comment]
Nup, this isn't fixed. At least in ST4 (4107).

**Comment by deathaxe** [comment]
Mensioned PR is not released yet. It's part of #607. Need to finish some migration docs as several commands have been renamed etc.
