### ISSUE TITLE
Bold Text is inconsistent 

### ISSUE THREAD

**Issue by suraj95** [SublimeText-Markdown/MarkdownEditing#594]
It is known that to the syntax to make a block of text bold is to wrap it around ** **.

**This is a bold text**

<img width="1108" alt="Screenshot 2021-02-10 at 4 24 48 PM" src="https://user-images.githubusercontent.com/18563739/107500754-8daed100-6bbc-11eb-9bb4-f89d34e02449.png">

It worked fine till now but for some reason, it is not working in one particular case. After pushing the file to Github, the text appears bold as expected, but not in the SublimeText editor. Even re-installing the MarkdownEditing package does not work.

<img width="1108" alt="Screenshot 2021-02-10 at 4 18 18 PM" src="https://user-images.githubusercontent.com/18563739/107500619-622be680-6bbc-11eb-8c6b-8ff0913ef00a.png">

**Comment by tomhundt** [comment]
**You have a blank space at the beginning of the line** (line 3) -- [see raw file](https://raw.githubusercontent.com/suraj95/Scala-Practice/main/README.md).  This, for whatever reason, causes the MultiMarkdown syntax to stop formatting things on that line.  Having spurious leading blanks [is a no-no](https://www.markdownguide.org/basic-syntax#paragraph-best-practices), and you should stick to having either zero of them (a normal paragraph) or four of them (a code block).

Also: if you are editing text to be displayed on GitHub, I recommend you use syntax MarkdownEditing > Markdown GFM and not MultiMarkdown.

**Comment by deathaxe** [comment]
It appears to be a general issue of all syntaxes in this package.
