### ISSUE TITLE
Feature request: Newline highlighting

### ISSUE THREAD

**Issue by GiovanH** [SublimeText-Markdown/MarkdownEditing#598]
In markdown, two spaces followed by a newline indicates a line break without a paragraph break. This is hard to see in editors, and some sort of visual highlight in these cases would be much appreciated.

**Comment by deathaxe** [comment]
ST4 can draw those via

```
	"draw_white_space":
	[
		"trailing"
	],
```

**Comment by GiovanH** [comment]
> ST4 can draw those via
> 
> ```
> 	"draw_white_space":
> 	[
> 		"trailing"
> 	],
> ```

This is a step in the right direction, but for markdown it's exactly two trailing spaces that need special highlighting, not just "any trailing whitespace".

**Comment by deathaxe** [comment]
Duplicate of #470
