### ISSUE TITLE
Sublime Text 4 misspelling underlying invisible on active line

### ISSUE THREAD

**Issue by reagle** [SublimeText-Markdown/MarkdownEditing#599]
When I move the cursor to a line to fix misspellings, the misspellings no longer have a red squiggly line underneath. I'm using ST 4102 on MacOS 11.2.3; this only happens when MarkdownEditing is installed and only with markdown files.

![STmd](https://user-images.githubusercontent.com/596814/115787211-d4286500-a38f-11eb-819b-ce31a5c1482f.gif)

**Comment by reagle** [comment]
BTW: This problem does not exist when I install and use ST 3211.

**Comment by reagle** [comment]
@OdatNurd suggested the following content for `User/MarkdownEditor-ArcDark.tmTheme`, which makes the highlights easier to see.

```
{
    "globals":
    {
        "line_highlight": "color(#2d3036 a(0.7))",
    }
}
```

**Comment by deathaxe** [comment]
ST should render line highlighting behind spell checking markers. That's a core regression.
