### ISSUE TITLE
Open settings side-by-side with one command instead of separately in two commands

### ISSUE THREAD

**Issue by mariohuq** [SublimeText-Markdown/MarkdownEditing#609]
See, how internal Settings open. There is one menu item:

![settings menu](https://user-images.githubusercontent.com/15021607/119297947-56fa5380-bc9f-11eb-8a31-0456cc21e430.png)

And it opens default settings and user-specified:

![image](https://user-images.githubusercontent.com/15021607/119298096-af315580-bc9f-11eb-94f9-e161522fa0f8.png)

This is done with `edit_settings` command (in `.sublime-menu` file):

```json
{
	"command": "edit_settings",
	"args": { "base_file": "${packages}/.../....sublime-settings" },
	"caption": "Settings"
}
```

This can be implemented for MarkdownEditing too!

**Comment by mariohuq** [comment]
Oh, I see, that is fixed in [this commit](https://github.com/SublimeText-Markdown/MarkdownEditing/commit/ea6d14ea1214c763bcbf1d90f91e70a9c157e754)

**Comment by deathaxe** [comment]
This is planned and already available in https://github.com/SublimeText-Markdown/MarkdownEditing/pull/607

**Comment by 0xdevalias** [comment]
Just in case anyone is looking for the commit in future, I found that it seemed to actually be introduced in this commit:

- https://github.com/SublimeText-Markdown/MarkdownEditing/commit/e7e9628dc408aa06e99a695d05efd650055a9b24
