### ISSUE TITLE
Allow styling of code fences

### ISSUE THREAD

**Issue by tomhundt** [SublimeText-Markdown/MarkdownEditing#612]
**Code fences have scope `text.html.markdown.gfm` which makes them un-styleable.  Please give them a unique scope.**  Other Markdown punctuation has its own scope.

## Background and Motivation

Code fences are three backquotes in a row, on their own line, optionally followed by a language specifier for the starting fence.  The language specifier tells the parser how to interpret the code between the fences.  For example, `py` for Python code, or `sh` for shell scripts.  Those then can get styled appropriately for the language.

I wish to style code fences themselves grey, so they fade into the background, as I do all of the markdown "punctuation" -- things like the `###` heading markers, brackets around links, and single backquote fences around inline code.  I've been able to do that with all of these _except the triple-backquote fences_.   This would be helpful since I read Markdown mostly in source form, i.e., in Sublime Text.

Here's an example of what I mean.  Notice your eye just skips over the grey stuff and you can read the text easily:
<img width="483" alt="larger example showing grey punctuation" src="https://user-images.githubusercontent.com/12475662/126344727-14746ea8-4f43-4d1c-ac03-9e0dfc93294b.png">

But I can't make triple-backquotes grey, because presently, these code fences are marked either just with scope `text.html.markdown.gfm` (the same as regular surrounding text) or `text.html.markdown.gfm markup.raw.block.markdown markup.raw.block.fenced.markdown` (the same as the enclosed code).    

In contrast, single-backquote (inline) code fences are marked with a "punctuation" scope (`text.html.markdown.gfm meta.paragraph.markdown markup.raw.inline.markdown punctuation.definition.raw.markdown`) and headings are `text.html.markdown.gfm meta.block-level.markdown markup.heading.markdown punctuation.definition.heading.markdown`.  

Here's an example (I've done `Tools > Developer > Show scope name` to display the scope in a little popup box, below the example):
<img width="489" alt="code fence w scope" src="https://user-images.githubusercontent.com/12475662/126343042-9f34e0fc-c69b-4b57-8f80-83e902980b7b.png">
(Notice the fences are white, just like regular text.)

Here's a second example, where the scope of the fence is the same as the scope of the fenced code (and as a result, the fences are green, like the code text):

<img width="477" alt="larger example showing green fence" src="https://user-images.githubusercontent.com/12475662/126348239-3230d6f4-d4c0-4d56-8f31-5ff992a106a9.png">

So, my request is to please add a "punctuation" scope for the 3-backquote code fences.  I've looked at the syntax file and... it's complicated.  

Thanks

**Comment by deathaxe** [comment]
MarkdownEditing's syntax definitions have fallen behind quite far compared to builtin syntaxes, while still having some unique features (3rd-party syntaxes in fenced codeblocks).

_While improving punctuation is not a big deal, long term goal is to inherite from builtin Markdown to get best results and just do extensions in this package which can't be done in core syntax. This long term goal still needs some preparations in core syntax and will be available for ST4 only._
