### ISSUE TITLE
Upgrade kills color scheming 

### ISSUE THREAD

**Issue by vongoh** [SublimeText-Markdown/MarkdownEditing#613]
Hi,  MarkdownEditing updated tonite and the grey background I've been using for years disappeared.  

The option to "Change color scheme" in package control settings is also completely gone....it doesn't appear on the menu.   Sublime Text 2 build 4113,  thanks.

**Comment by Alalalalaki** [comment]
Same here.

**Comment by marcomarice** [comment]
Same here too... 
Sublime Text 3 build 4113

**Comment by stevenxxiu** [comment]
I think you're all referring to *Sublime Text **4*** build 4113.

**Comment by vongoh** [comment]
> I think you're all referring to _Sublime Text **4**_ build 4113.
> 
> This can be changed in `Preferences` -> `Package Settings` -> `Markdown Editing` -> `Select Color Scheme` -> `MarkdownEditor`.

'Select color scheme' is also gone from the menu.   

My bad,  I'm on ST3.  I never upgraded to 4.

**Comment by tajmone** [comment]
It's as @vongoh said, you  need to re-associate the color scheme for markdown files because the package has now switched from the old TextMate schemes to the newer Sublime format.

### Need to Also Close and Reopen Markdown Files!

Also, fixing the associated scheme and restarting ST4 is not enough for the color schemes to show properly! You'll also have to close every markdown file and reopen it for the changes to take effect — a well known horrible problem with ST.

So, to recap:

- Until you change the assigned markdown color scheme to the the new (renamed) schemes that ship with the package you'll be getting the error pop-up dialog complaining that it can't find the colour scheme file.
- Once you've fixed the markdown colour scheme settings, you won't see the error any more, but all markdown docs opened _before_ the change will still show up without the colour scheme — you must close and reopen these docs.
  
My understanding is that this is due to the way ST caches settings info and projects status, which on the one hand makes starting up ST blazing fast, but on the other can drive you crazy when a scheme or syntax is renamed — especially syntaxes, which cause lot's of problems.

**Comment by deathaxe** [comment]
> It's as @vongoh said, you need to re-associate the color scheme for markdown files because the package has now switched from the old TextMate schemes to the newer Sublime format.

This should happen automatically for all open files, but for some reason it seems plugins don't load for some users. 

Reason unclear. Need infos. I've tested upgrade from 2.10 to 3.0.0 internally on ST3176 and ST4113 on Windows without noting any issues.

Not sure what's going wrong.

**Comment by deathaxe** [comment]
> The option to "Change color scheme" in package control settings is also completely gone....it doesn't appear on the menu.

Interestingly I had to call it from command palette once after upgrade to get the menu item back. Should be present after restart of ST, at least.

**Comment by alexwforsythe** [comment]
> I think you're all referring to _Sublime Text **4**_ build 4113.

> ### Need to Also Close and Reopen Markdown Files!

> This should happen automatically for all open files, but for some reason it seems plugins don't load for some users.

I lost my syntax highlighting and color theme on this build. After following the [migration guide](https://sublimetext-markdown.github.io/MarkdownEditing/troubleshooting/#300-migration-guide) and manually setting my color theme, the plugin still wasn't working. I finally realized I was working with unsaved files -- it was easily fixed by copying the unsaved content to a new file and setting the syntax to Markdown.

**Comment by vongoh** [comment]
> After following the [migration guide](https://sublimetext-markdown.github.io/MarkdownEditing/troubleshooting/#300->migration-guide) and manually setting my color theme, ...

I opened ' Preferences: Settings - Syntax Specific' and input the code:
```
{
    "color_scheme": "Packages/MarkdownEditing/MarkdownEditor.tmTheme",

    "tab_size": 4,
    "translate_tabs_to_spaces": true,
    "trim_trailing_white_space_on_save": false,
    "auto_match_enabled": true,

    // Layout
    "draw_centered": true,
    "word_wrap": true,
    "wrap_width": 80,
    "rulers": [],

    // Line
    "line_numbers": false,
    "highlight_line": false,
    "line_padding_top": 2,
    "line_padding_bottom": 2,

    // Caret
    "caret_style": "wide",
    "caret_extra_top": 3,
    "caret_extra_bottom": 3,
}
```

- grey background re-appears
- no markdown formatting shown at all.  its all raw text, with line numbers to the left
- ST gives me this popup error:

"Error loading color scheme. Packages/MarkdownEditing/MarkdownEditor.tmTheme:
Unable to open
Packages/MarkdownEditing/MarkdownEditor.tmTheme"

I do small business branding and web design, haven't done much coding in ST and haven't dug through these files in years.  Where do I go now? thanks....

**Comment by tajmone** [comment]
> "Error loading color scheme. Packages/MarkdownEditing/MarkdownEditor.tmTheme:
> Unable to open Packages/MarkdownEditing/MarkdownEditor.tmTheme"

With v3.0.0 all schemes use the new ST format, so their extension is now `.sublime-color-scheme` instead of `.tmTheme`, as you can see in the `schemes/` folder:

https://github.com/SublimeText-Markdown/MarkdownEditing/tree/master/schemes

**Comment by loikein** [comment]
@vongoh Based on your code and @tajmone's answer below, I tried the following code and it works after close and reopen any Markdown file:

```
{
    "color_scheme": "Packages/MarkdownEditing/MarkdownEditor.sublime-color-scheme",

    "tab_size": 4,
    "translate_tabs_to_spaces": true,
    "trim_trailing_white_space_on_save": false,
    "auto_match_enabled": true,

    // Layout
    "draw_centered": true,
    "word_wrap": true,
    "wrap_width": 80,
    "rulers": [],

    // Line
    "line_numbers": false,
    "highlight_line": false,
    "line_padding_top": 2,
    "line_padding_bottom": 2,

    // Caret
    "caret_style": "wide",
    "caret_extra_top": 3,
    "caret_extra_bottom": 3,
}

```

**Comment by MattDemers** [comment]
> > After following the [migration guide](https://sublimetext-markdown.github.io/MarkdownEditing/troubleshooting/#300-%3Emigration-guide) and manually setting my color theme, ...
> 
> I opened ' Preferences: Settings - Syntax Specific' and input the code:
> 
> ```
> {
>     "color_scheme": "Packages/MarkdownEditing/MarkdownEditor.tmTheme",
> 
>     "tab_size": 4,
>     "translate_tabs_to_spaces": true,
>     "trim_trailing_white_space_on_save": false,
>     "auto_match_enabled": true,
> 
>     // Layout
>     "draw_centered": true,
>     "word_wrap": true,
>     "wrap_width": 80,
>     "rulers": [],
> 
>     // Line
>     "line_numbers": false,
>     "highlight_line": false,
>     "line_padding_top": 2,
>     "line_padding_bottom": 2,
> 
>     // Caret
>     "caret_style": "wide",
>     "caret_extra_top": 3,
>     "caret_extra_bottom": 3,
> }
> ```
> 
> * grey background re-appears
> * no markdown formatting shown at all.  its all raw text, with line numbers to the left
> * ST gives me this popup error:
> 
> "Error loading color scheme. Packages/MarkdownEditing/MarkdownEditor.tmTheme:
> Unable to open
> Packages/MarkdownEditing/MarkdownEditor.tmTheme"
> 
> I do small business branding and web design now, haven't done much coding in ST and haven't dug through these files in years and use it for writiing....basically everything. Where do I go now? thanks....

I had the same issue as you, and changed `color_scheme": "Packages/MarkdownEditing/MarkdownEditor.tmTheme` in the first line to `color_scheme": "Packages/MarkdownEditing/MarkdownEditor.sublime-color-scheme` and it worked.

**Comment by deathaxe** [comment]
You can omit the path when using sublime-color-scheme .

`"color_scheme": "MarkdownEditor.sublime-color-scheme` is enough.

**Comment by deathaxe** [comment]
Notes about syntax specific settings related to visuals have been updated in https://sublimetext-markdown.github.io/MarkdownEditing/troubleshooting

Mensioned issues about "Select Color Scheme" not being available should have been resolved by one of the recent bugfix releases.
