### ISSUE TITLE
Missing GFM

### ISSUE THREAD

**Issue by plakhin** [SublimeText-Markdown/MarkdownEditing#614]
After one of the recent updates `Github flavoured Markdown` option is missing from syntax highlighting list, I can see only these 2:

![image](https://user-images.githubusercontent.com/25561058/133014512-0fde7f1c-34db-4f2e-94bf-9c177058adbb.png)

**Comment by FrankSpierings** [comment]
I have the exact same issue, and it is rather annoying.

**Comment by drdachmann** [comment]
same thing here

**Comment by deathaxe** [comment]
`Markdown` supports GFM extensions. It's just the old default Markdown which has been removed and thus the GFM was renamed.

**Comment by FrankSpierings** [comment]
The GFM looked different in my editing view than the standard `Markdown` option. I'm currently unable to return to that view. One annoyance is the look of code-blocks. In the `Markdown` view, its background does not change color.  Any way to restore the look and feel of `Markdown` to the previous GFM look?

**Comment by deathaxe** [comment]
What exactly does `background does not change color` mean`?

These are raw and python highlighted code blocks with MarkdownEditor.sublime-color-scheme. The background is slightly dimmed.

![grafik](https://user-images.githubusercontent.com/16542113/133128313-f3dc0cbd-a246-426c-80d5-439c1927bee4.png)

**Comment by FrankSpierings** [comment]
No background color change in `Monokai Extended`.

![image](https://user-images.githubusercontent.com/2954929/133128844-68f2baff-7922-4c97-ae09-df868ceeec42.png)

**Comment by deathaxe** [comment]
MarkdownEditing's syntax now uses the same scope names as the default Markdown syntax, shipped with ST.

This color scheme wouldn't dimm code blocks for default Markdown syntax, too, then.

The content of all fenced code blocks is scoped `markup.raw.code-fence` Depending on whether you want to also dimm the fences' background a rule for `meta.code-fence.definition` would need to be added to your color scheme.

**Comment by FrankSpierings** [comment]
Thanks for the help. For anyone how to fix it for themselves, I made the following changes.

__Packages/User/Monokai Extended.sublime-color-scheme:__
```json
// Documentation at https://www.sublimetext.com/docs/color_schemes.html
{
    "variables":
    {},
    "globals":
    {},
    "rules": [
    {
        "name": "Markdown - Code block outline",
        "scope": "meta.code-fence.definition",
        "background": "rgb(40, 40, 40)"
    },
    {
        "name": "Markdown - Code block inside",
        "scope": "markup.raw.code-fence",
        "background": "rgb(51, 51, 51)"
    }]
}
```

Reference: https://github.com/jonschlinkert/sublime-monokai-extended

**Comment by ckfishh** [comment]
All of my settings have been wiped out with this change

**Comment by revolter** [comment]
The GFM syntax was not colored at all. It only used different tints of white. How do I change back to that?
