### ISSUE TITLE
Text is left-centered

### ISSUE THREAD

**Issue by fullstackplus** [SublimeText-Markdown/MarkdownEditing#617]
Prior to the last update, text was showing in a neat centered column, alá the Reader View in Firefox — which was great for readability. Now the lines go across the entire editor window with no margins.

**Comment by stevenxxiu** [comment]
I fixed this by restoring the settings in https://sublimetext-markdown.github.io/MarkdownEditing/troubleshooting/#300-migration-guide to my `Markdown.sublime-settings`:

```json
{
    "color_scheme": "MarkdownEditor.sublime-color-scheme",

    "tab_size": 4,
    "translate_tabs_to_spaces": true,
    "trim_trailing_white_space_on_save": false,
    "auto_match_enabled": true,

    // Layout
    "draw_centered": true,
    "word_wrap": true,
    "wrap_width": 80,
    "rulers": [],

    // Line
    "line_numbers": false,
    "highlight_line": false,
    "line_padding_top": 2,
    "line_padding_bottom": 2,

    // Caret
    "caret_style": "wide",
    "caret_extra_top": 2,
    "caret_extra_bottom": 3,
}
```

But yes I find this to be very strange. I'm thinking these should be default settings, and unsure why this part of the file was removed.

**Comment by deathaxe** [comment]
MarkdownEditing overriding global user settings to mess around with visual setting was many complained issue and hard to fix on end users side and thus have been removed by intend. Text being displayed via `draw_centered` was even filed as bug many times.

I personally found that the most awkward part of MarkdownEditing, too.

It's easier and more consistent to add those settings to syntax specific user preferences than trying to override them.

Each syntax comes with its own needs about `wrap_with`, `trim_trailing_white_space_on_save` and such settings, all of them highly depending on project needs or user tastes.

The way to go is to add those as @stevenxxiu correctly noted.

Markdown specific color scheme can still be adjusted via `MarkdownEditing: Select Color Scheme`.

**Comment by deathaxe** [comment]
Another way to get centered text without line numbers etc. is to use ST's "Distraction Free Mode".

**Comment by fullstackplus** [comment]
Thanks for the comments, everyone. Seems like restoring the removed settings manually is the way to go. I'll go ahead and close this issue because it's technically not a software bug. Cheers.
