### ISSUE TITLE
Command to unfold single level

### ISSUE THREAD

**Issue by Kshitiz-Sharma** [SublimeText-Markdown/MarkdownEditing#620]
Before the update I'd use `Tab` to drill down into a markdown document. The use case is this: start with all sections folded. Navigate to a 1st level heading, press `Tab` to reveal 2nd level headings, navigate to a specific heading ... and so on.

After the update `Tab` no longer works. Not sure why, as the hotkeys should be targeted to the most frequent tasks, which for headings would be fold/collapse, rather than anything else.

Anyway, I've tried to fix this by adding this in the keybindings:
`{ "keys": ["tab"], "command": "mde_fold_section"}`

The problem is that it recursively expands everything and not just the next level headings. Note that I'm not talking about expanding a specific heading level, but current heading level + 1.

This used to work in the previous version, what is the equivalent command under the new version.

Thanks

**Comment by Kshitiz-Sharma** [comment]
Reviewing the default keybindings I couldn't find a command for this. From a usability perspective, it doesn't make sense to expand everything. I often have markdown documents with 100s of headings and extensive nesting. Recursive expansion should be a separate command really. 

Until this is resolved, I'm looking to rollback to previous version. Currently trying to figure out how.

**Comment by maliayas** [comment]
> I'd use Tab to drill down into a markdown document.

Not related to the original bug... Did you know that you can navigate through a document via Ctrl+R?

**Comment by Kshitiz-Sharma** [comment]
> 
> 
> > I'd use Tab to drill down into a markdown document.
> 
> Not related to the original bug... Did you know that you can navigate through a document via Ctrl+R?

That's the symbol search menu. Doesn't work well as it doesn't allow drill down. All headings are visible in a small menu. I have a document with 100s of headings and extensive nesting, drill down is very much needed.

Do you know if the behavior of this command has changed in the new version. I might have to read the code to figure it out but I'm pretty sure it used to work in the older version.

**Comment by maliayas** [comment]
Ah, I see.

Unfortunately I'm using a pretty old version and couldn't find some spare time yet in order to review new versions. So, don't know the answer.

**Comment by deathaxe** [comment]
Headings are expanded and collapsed via <kbd>shift+tab</kbd>, which was the default in 2.x as well.

The desired functionality is even covered by various unittests (see https://github.com/SublimeText-Markdown/MarkdownEditing/blob/master/tests/test_folding.py).

What you probably want is to 

1. collapse all level 1 headings via <kbd>ctrl+k, alt+1</kbd> (ST's global default binding to collapse/expand by level in all syntaxes)
2. hit <kbd>shift+tab</kbd> to expand any heading one by one.

or 

1. collapse all sections to get an outline (all headings visible) via <kbd>ctrl+k, alt+9</kbd>
2. hit <kbd>shift+tab</kbd> to expand a heading's section up to the very next sibling or child heading.


![Animation](https://user-images.githubusercontent.com/16542113/133117927-7e860a2a-b05a-48fc-8837-b8e821185393.png)


Note:

Without pre-setting a desired folding level via <kbd>ctrl+k, alt+[1-9]</kbd>, which is the same a hitting <kbd>ctrl+k, alt+0</kbd>, the `mde_fold_section` command always folds and unfolds the whole section of a heading up to the next heading of same level. But this has also been the case in 2.x

The main change here is a more consistent behavior between the fold-by-level commands and the shift+tab behavior as well as the outline mode via <kbd>ctrl+k, alt+9</kbd>.

**Comment by Kshitiz-Sharma** [comment]
Hi @deathaxe,

Thanks for keeping this plugin alive, and continuing it's development. It's a big part of my note taking workflow. If you have a donations link, I'd love to support its active development.

Regarding this issue, perhaps I shouldn't have mentioned `tab`. That is my custom key binding to `mde_fold_section`.

I do not use level based hotkeys, as I don't want to do the mental arithmetic of which level I'm at and fold/expand that way. Instead - as you described - I'd fold everything (using global_fold) and then drill down to the heading I want to edit by successively tabbing (mapped to mde_fold_section) at each level.

So yes, what I need is what's demonstrated in your GIF. When you did an expand on the 1st level heading, it only showed 2nd level headings. And expanding a specific 2nd level shows it's 3rd level heading (or the text content), and so on.

However, this doesn't seem to be working in my setup. Regardless of whether I use fold all, or individually fold each heading, it always expands back all the levels. Here's a GIF:
![KDQezskwB3](https://user-images.githubusercontent.com/6263572/133140477-f760dd3c-4ad9-4406-9afa-a101aaa8d299.gif)

I'm using the latest build 4113 and latest plugin installed using package manager.

My keybindings are:
{ "keys": ["tab"], "command": "mde_fold_section"},
{ "keys": ["alt+`"], "command": "global_folding"}

Can you tell me which commit this was changed in? I'll do a fork and a manual installation, as I'm very much reliant on this functionality in my workflow. Or perhaps add a config switch to toggle the old/new behavior.

Thanks

**Comment by deathaxe** [comment]
What's `global_folding`? You may want to try `mde_fold_all_sections` instead. It's the one called by `ctrl+k, ctrl+1`. It's crucial to fold with that command as `mde_fold_section` relies on a folding level setting, written by it.

**Comment by Kshitiz-Sharma** [comment]
> What's `global_folding`? You may want to try `mde_fold_all_sections` instead. It's the one called by `ctrl+k, ctrl+1`. It's crucial to fold with that command as `mde_fold_section` relies on a folding level setting, written by it.

Ah! Finally it makes sense. 😀 `global_folding` is from another plugin called `SmartMarkdown`. I've mixed the two up. The solution is to either:

1. Switch fold current section hotkey to `smart_folding` (SmartMarkdown's fold current section)
2. Or switch global folding hotkey to `mde_fold_all_sections`

Both work. 

Now scratching my head. The way it's configured it should never have worked. But I've been using this for years.

Oh well. All's well that ends well.

**Comment by Kshitiz-Sharma** [comment]
@deathaxe thanks for your help

**Comment by luispuerto** [comment]
Thanks for pointing this up, because I had a similar problem related to the SmartMarkdown package.
