### ISSUE TITLE
disable/toggle auto-folding? (on 3.0.0)

### ISSUE THREAD

**Issue by reagle** [SublimeText-Markdown/MarkdownEditing#623]
I *think* I like the auto-folding of link URLs, but sometimes I want to see all my URLs (e.g., to see if I'm using `https` instead of `http` or use [ACE jump](https://packagecontrol.io/packages/AceJump) to go to a URL.) I think there should be a toggle command.

**Comment by deathaxe** [comment]
You might want to try `MarkdownEditing: Auto Fold Link URLs`? aka. `mde_fold_links` which temporarily toggles it for the current view.

To permanently enable/disable it, you might add the following to _Preferences.sublime-settings_

```jsonc
	// MarkdownEditing (Folding):
	// Enable automatic folding of url parts of inline references or images
	"mde.auto_fold_link.enabled": false,
```

**Comment by reagle** [comment]
Ah, thank you. Mind putting "toggle" in the command description so I can easily find it in the command palette, amidst "Toggle Centered Line" and "Toggle Folding Current Section"? 🙂
