### ISSUE TITLE
bug in url auto folding (3.0.0)

### ISSUE THREAD

**Issue by reagle** [SublimeText-Markdown/MarkdownEditing#624]
I've noticed the auto-folding can be flakey. For example, here is some source auto-folded:

<img width="633" alt="Screen Shot 2021-09-13 at 17 00 44" src="https://user-images.githubusercontent.com/596814/133155980-767ca10f-50f4-41e5-9154-286ef8c8b304.png">

and expanded:

<img width="761" alt="Screen Shot 2021-09-13 at 17 01 17" src="https://user-images.githubusercontent.com/596814/133155996-2d64f2a5-3ecd-463c-addf-d1354bc5f9d9.png">

For some reason, the auto-fold consumed `- [Critical` as two entities to fold.

**Comment by deathaxe** [comment]
When does it happen? Normal writing, pasting texts. Any hint's what was going on when that happend?

**Comment by ianpaul** [comment]
This happens to me too (v.3.0.2 on Windows 10) when I try to insert a second URL link. I create the first link by highlighting the chosen text, inserting square brackets by hitting the open square bracket key and Sublime autocompletes. Then I hit _Shift + 9_ for the parentheses (also auto-completed) and paste in my URL. 

So far so good. 

Then I get to the second URL. I follow the same process. I highlight my text, insert brackets, and then as soon as I hit the first parentheses key, _Shift + 9_, it looks like this. 

I think it has something to do with the proximity to the period when creating that second link. If I move the period at the top and then create the link (so a space between the closing parentheses and the period) this doesn't happen, but proximity to the period is not an issue for the first link that I created. 

Also, when I turn off auto-fold the second link is highlighted in a green color like the quote in parentheses seen here whereas the first link is just the regular text color.

![Markdown](https://user-images.githubusercontent.com/1427586/133394038-01876705-eb12-4cdd-80d5-6bd877091048.png)

**Comment by reagle** [comment]
My bug appeared on editing a static markdown file, though I can't reproduce it with a static minimal example right now -- the file has since changed.

The dynamic issue, though, would be even harder. As the user is typing a link within the parentheses, but before they close the terminating parenthesis, this plugin is matching and folding lots of subsequent content.

**Comment by deathaxe** [comment]
It happens because the syntax scopes everything up to the next closing parenthesis as link url part, if the closing parenthesis is missing while typing the link url.

I've never noticed that as I have `auto_match_enabled` set `true` which alwas adds balanced parens and brackets.

Once closing paren is added the rest of the folded text is no longer part of the url (per syntax definition) and thus ignored by the auto-folder.

**Comment by reagle** [comment]
Ah, I have `"auto_match_enabled": false`. I think the problem is that once I type the closing paren, autofold doesn't then unfold the now erroneous matches?

**Comment by deathaxe** [comment]
Yes, as it doesn't have any reference to them. Fixing that issue requires some larger changes in syntax definition. This will take some time to get done right.
