### ISSUE TITLE
Wiki functionality missing

### ISSUE THREAD

**Issue by jonasferry** [SublimeText-Markdown/MarkdownEditing#626]
I have used the wiki functionality extensively to build a text base knowledge base. In the 3.0.0 and then 3.0.1 updates I can no longer use the wiki.

I created wiki links by surrounding words with double brackets, for example [[testLink]], then right clicking on the link and selecting the option to go to the page. After the updates, I no longer get that option.  Right clicking to jump between my knowledge base topics was really quick and I'd like it back.

Here's the right click menu outside of the wiki link:

<img width="469" alt="right-click-outside2" src="https://user-images.githubusercontent.com/209482/133244674-c305d239-6e71-42e7-b59c-ca3df2fb136e.png">

Here's the right click menu inside of the link:

<img width="516" alt="right-click-inside-link2" src="https://user-images.githubusercontent.com/209482/133244703-d35f2981-cf6d-4887-9887-25a5dfbd25e9.png">

Here's my Preferences file:

<img width="454" alt="preferences" src="https://user-images.githubusercontent.com/209482/133243855-d8bbbb06-60ac-4aa5-ad43-4343e788ffb1.png">

I had some issues after the update to adapt to the new preference system, but I seem to have sorted that out and have gotten back my color scheme. I added the "mde.keymap_disable_ABC=false" lines to test if they were blocking the wiki options, but nothing changed.

I can use both the right click menu option and keyboard shortcut to open the wiki home page and today's journal, but not regular wiki pages. Also, when searching through the command palette, I don't see any option to create or open an existing wiki page.

I also noticed that the [May 25 version](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/4c2edea18bb82f7e53e129f7523542ebf27ac766/README.md) of the README file has a section called Wiki Features, but in the [July 1 version](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/0fe893f2b93af7fdc4c937e9c9670b02c95e2c80/README.md) with the new page structure, no wiki functionality is mentioned. I hope that it hasn't been deprecated.

Has wiki functionality been removed, is this a bug, or am I just missing a setting somewhere?

**Comment by deathaxe** [comment]
Wiki feature hasn't been touched by this release.

Scope name of wiki links has changed, which is not respected by related plugins. Will fix it in next realease.

Most parts of the readme have been moved to User Guide to get a hopefully better structure.
