### ISSUE TITLE
URL autofolding non-URL parentheses

### ISSUE THREAD

**Issue by reagle** [SublimeText-Markdown/MarkdownEditing#631]
autofold URL misrecognizes the material in parenthesis as a link when it is parenthetical prose. (The linter also mistakes it.)

```
- [QICs] (Question, Insight, **and/or** Connection)

[QICs]: https://en.wikipedia.org/wiki/User_Talk:Reagle/QICs

```

<img width="332" alt="Screen Shot 2021-09-15 at 11 02 16" src="https://user-images.githubusercontent.com/596814/133458996-1c991bce-5a2d-4c47-8bd3-1ff332b41dc2.png">

**Comment by deathaxe** [comment]
That's actually a syntax definition issue as it expects the parens after brackets to be the link part. You can see that by the red `invalid` scope in between.

**Comment by reagle** [comment]
I see the [syntax definition says](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/518e97e5bc24578ed07e595b8e1e1d8204248093/syntaxes/Markdown.sublime-syntax#L993) "spaces not allowed before the open paren, but we check for it anyway to mark it as invalid". I'm sure this is a mistake some people make, but it is valid commonmark and has valid uses, such as my own parenthetical after a link reference.

**Comment by deathaxe** [comment]
This behavior needs to be changed. In ST4 we can mimic commonmark more adequately by not scoping the whole construct as link if anything goes wrong, but the plan is to reach a stable milestone which works for ST3, too, first.

**Comment by deathaxe** [comment]
This should at least be improved in 3.0.3

**Comment by reagle** [comment]
I just got the 3.0.7 update and remembered to check this and my specific case that prompted this issue seems fixed. Thanks!
