### ISSUE TITLE
Illegible elements with default Mariana color scheme

### ISSUE THREAD

**Issue by reagle** [SublimeText-Markdown/MarkdownEditing#633]
After my install was upgraded to 3.0.0 my markdown color scheme was broken so I trashed the scheme/theme configurations and decided to use the ST default Mariana scheme. I figure that will be the most stable and it's not so bad. However, there are some odd renderings and colors.

First, backticks are illegible.

<img width="214" alt="Screen Shot 2021-09-15 at 15 46 16" src="https://user-images.githubusercontent.com/596814/133503870-d8271854-0ae3-4ac7-bdf9-3928cb317c68.png">

Especially when the line is not highlighted, it looks like extra spaces.

<img width="198" alt="Screen Shot 2021-09-15 at 15 46 25" src="https://user-images.githubusercontent.com/596814/133503933-703977b9-0e82-44c0-bd0f-d44a7c58ec87.png">

Also, I seem to have (hard to see) pencils and spiders in my gutter. These files aren't in Git, and these are lines I've changed recently so what do they mean?

<img width="187" alt="Screen Shot 2021-09-15 at 15 50 04" src="https://user-images.githubusercontent.com/596814/133504020-7d208303-ab5d-4642-aa12-876716e5df90.png">

**Comment by deathaxe** [comment]
I've never seen such pencils or something like that.

It being tinted black may be caused by missing color definitions for the scope this plugin uses for the related region being added via `view.add_region()` API.

The only part of MDE adding regions is the footnote module. Not sure what it does in detail, haven't touched it so far.

**Comment by reagle** [comment]
I discovered the pencil and mouse icons are from [SublimeWritingStyle](https://github.com/thedataking/SublimeWritingStyle), and I can disable them or change them to be lighter when using a dark theme. I disabled them.

The outstanding and larger concern is black backticks when using the default Mariana style.

**Comment by reagle** [comment]
I've concluded this isn't a MarkdownEditing issue.
