### ISSUE TITLE
v3 ctrl+alt+1..6 bindings prevent typing characters in many keyboard layouts

### ISSUE THREAD

**Issue by nbud** [SublimeText-Markdown/MarkdownEditing#634]
Many keyboard layouts rely on the ``ctrl+alt`` combo (or AltGr key) to enter characters. See https://en.wikipedia.org/wiki/AltGr_key

The new bindings for setting the markdown heading (``ctrl+alt+1``, ..., ``ctrl+alt+6``) take precedence, preventing the user to enter a character.

For example, using a French AZERTY layout, the left square bracket ``[`` is entered using ctrl+alt+5, however when using Markdown Editing this sets a level 5 heading (``#####``).

Is there a way to disable these key bindings?

**Comment by ilpssun** [comment]
I strongly second that.  [This is also stated in the SublimeText documentation](https://docs.sublimetext.io/reference/key_bindings.html#bindable-keys):
> If you're developing a package, keep this in mind: <kbd>Ctrl+Alt+*alphanum*</kbd> should never be used in any Windows key bindings.

It seems that there is no way to *clear* a key binding.  You can *overwrite* them in your keymap, e.g.:

     { "keys": ["alt+ctrl+5"], "command": "insert", "args": {"characters": "["} }

but that takes away some of the autocomplete magic (e.g. auto-closing brackets).

**Comment by TheWiseMan** [comment]
Got the same problem, this is the reason I recently (and I hope temporarily) stopped using this package.

**Comment by kevin-stuart** [comment]
For some other keys with AltGr and numbers larger than 6 (e.g. 0), I also have problems. Is this related to this problem? Or is this a separate bug?

**Comment by deathaxe** [comment]
It's the same. 1-6, 9, 0 are bound to this combination.

**Comment by ilpssun** [comment]
Great, thanks for the timely fix, @deathaxe!  Good work on the update, by the way!

**Comment by nbud** [comment]
Great work @deathaxe, thank you!

**Comment by TheWiseMan** [comment]
Thank you !
