### ISSUE TITLE
Bold/italic toggle and GFM task lists in 3.0.2

### ISSUE THREAD

**Issue by keatingw** [SublimeText-Markdown/MarkdownEditing#636]
Thanks so much for the update - broadly it's performing really well. Just had a couple of reports that may or may not be intended behaviour:

**Bold/italic autotoggle:**

For bold, this now resets the cursor to the beginning of the word, so if we begin with:
![image](https://user-images.githubusercontent.com/54231777/133729857-7e57174d-f94f-4b87-b583-c91224b6d3dd.png)
and press alt+B, we get 
![image](https://user-images.githubusercontent.com/54231777/133729904-bf7a1380-979e-4cbd-ace0-1a6d9636f583.png)
(i.e. the cursor before the text rather than after it) - this is most notable because reversing the change with another alt+B removes the bolding but leaves the cursor at the beginning.

With italics, the problem is a little different. Again starting with the cursor at the end of the word 'The', pressing alt+I gives:
![image](https://user-images.githubusercontent.com/54231777/133730097-fbc8a929-5f25-495a-a9ec-7f218ba991e3.png)
(i.e. the cursor before both the text _and_ the underscores). Pressing alt+I again from this point now opens the 'Find' context menu, presumably because the new cursor position is at the italic begin scope rather than just italic.

**GFM task lists:**

This is an awesome addition, with the only issue being that the insertion using alt+T does not respect the list indent bullets setting. I typically use `-` as my first level list marker, while alt+T still inserts asterisks. This is a very minor concern so feel free to ignore if it's intended.

**Comment by deathaxe** [comment]
Basically I don't like the caret moving at all, while changing formatting. The issue just is those functions being implemented as `sublime-macro`s whose functionality is quite limited. This release addresses some former bugs with regards to those functions, while maintaining the macros.

The issue with underscores is, they belong to a word. Thus moving caret by word has the shown result. Not doing anything will always end up in caret after bold/italic markers, like `**The**|`. It prevents toggling back quickly.

Fixing that behaviour means to rewrite those as python plugins, which might take a while.

**Comment by keatingw** [comment]
That makes sense - it's obviously a very minor point so understandable if changes aren't a priority.

Would you recommend for now using asterisks for italics as well, so that the toggling reverse works there too? This could be used as default as a workaround (noting that it would be opposite to e.g. Github convention).

**Comment by deathaxe** [comment]
I am thinking about just dropping the caret movement so it will always be placed after formattings. Would be quite easy fix and may be a bit more natural with regards to writing workflow.

**Comment by deathaxe** [comment]
> This is an awesome addition, with the only issue being that the insertion using alt+T does not respect the list indent bullets setting.

It would be easy to implement a function, which uses the first bullet of `mde.list_indent_bullets`. Automatically choosing the correct one based on indentation level is a bit more tricky.

**Comment by keatingw** [comment]
> I am thinking about just dropping the caret movement so it will always be placed after formattings. Would be quite easy fix and may be a bit more natural with regards to writing workflow.

This would probably align with my typical expectation, and definitely makes the italicize/bold and keep typing workflow easy.

> It would be easy to implement a function, which uses the first bullet of `mde.list_indent_bullets`. Automatically choosing the correct one based on indentation level is a bit more tricky.

Using the first bullet level was my only thought here, but happy to defer to your preference given it's not onerous to enter a bullet list and then follow up with alt+T to convert it. I can understand the thinking for choosing the correct one based on indentation level, but I'd think using alt+T to create nested lists is rare enough that it's probably not worth the effort to work that part in.
