### ISSUE TITLE
Change strikethrough begin back to a double tilde

### ISSUE THREAD

**Issue by eugenesvk** [SublimeText-Markdown/MarkdownEditing#637]
In the new version 3 of your plugin I can't seem to be able to use non-paired (single) tilde `~` characters as e.g. a sign of approximation due to the fact that the new syntax rule for strikethroughs expects a closing tilde according to this rule:

https://github.com/SublimeText-Markdown/MarkdownEditing/blob/518e97e5bc24578ed07e595b8e1e1d8204248093/syntaxes/Markdown.sublime-syntax#L910

and shows an error if I don't close it (and also highlights all the text after the first tilde)

The comment `any number of ~` suggests that this is intentional, yet I don't understand why that is, shouldn't 
~~strikethroughs~~(`~~strikethroughs~~`) only parse the double tildes and ignore ~single tilde (`~single`) or ~single pair~ (`~single pair~`) just like your recommended plugin [MarkdownPreview](https://github.com/facelessuser/MarkdownPreview) does?
According to [GitHub's spec](https://github.github.com/gfm/#strikethrough-extension-), GitHub is also supposed to only strikethrough on two tildes

> Strikethrough text is any text wrapped in two tildes (~).

but I see that the ~single tilde wrap~ also enables it in this comment.
If you meant to replicate this behavior, then may I ask to add an option to enforce only a two-tilde wrapping as the strikethrough marker and continue to ignore single tilde wrap (and, by extension, not show any errors if a tilde is not paired)? Single tilde is too useful a mark to remove it in favor of an already easy-to-insert double tilde wrap (your plugin already auto-adds double tildes on text selection-> inserting `~`)

P.S.
Changing the rule to add two tildes at the start seems to fix my issue, but I'm not sure whether this creates some other issues with the critic markers or what else as I haven't done any tests
`    - match: (?:~~(?!~}|>|\s))+  # any number of ~ above two up to ~> or ~~} critic markers`

**Comment by deathaxe** [comment]
The syntax respects Github's way of supporting strikethrough parsing, which allows words or phrases wrapped into single tildes.

`~test~` => ~test~

`~~test~~` => ~~test~~

A striked phrase might easily span multiple lines, such as:

```
~This is
striked multiline~
```

ST3 can't see, whether a closing tilde exists, if it is not on the same line. Thus any tilde is always assumed the beginning of a striked word or phrase. This kind of issue exists in many situations. You would see the same with `*` or `_`, which start bold or italic regions the same way.

The way to go is to escape the leading tilde `\~word` as you would need to do for asterisk (`\*word`) or underscore (`\_word`) with the current syntax.

ST4's syntax engine allows us to solve this issue, but it requires a general overhaul of all related contexts - may end in a general rewrite of the syntax. This will happen not before a ST3 compatible stable state is reached as I can't and don't want to maintain two types of syntax definitions.

**Comment by eugenesvk** [comment]
Thanks for your prompt response!

> The syntax respects Github's way of supporting strikethrough parsing, which allows words or phrases wrapped into single tildes

Ok, so once again a spec loses to reality :) — here is some extra info on why this legacy error persists on GitHub despite not being included in the spec https://github.com/markedjs/marked/issues/1561#issuecomment-548844317

However, would it make more sense for these type of unwelcome legacy issues to be confined to a markdown-GFM syntax (there was a such third syntax in the previous version) while making the default Markdown syntax more "commonly" specced?
Otherwise we're in a rather ~~interesting~~ confusing situation where the most common markdown plugins are in conflict — MarkdownEditing syntax is different vs the default offline build output of the MarkdownPreview.

> You would see the same with `*` or `_`, which start bold or italic regions the same way.

Never seen this as that's not a common way to use a single `*word`/`_word` in plain text (not fenced), while `~` is much more common

> The way to go is to escape the leading tilde `\~word` as you would need to do for asterisk (`\*word`) or underscore (`\_word`) with the current syntax.

Thanks for the suggestion, didn't know about it, though for now I'll use the manual syntax regex override mentioned above as it's way more convenient than having to remember to escape a tilde every time

> ST4's syntax engine allows us to solve this issue, but it requires a general overhaul of all related contexts - may end in a general rewrite of the syntax. This will happen not before a ST3 compatible stable state is reached as I can't and don't want to maintain two types of syntax definitions.

Totally understandable if this depends on such a a general overhaul

**Comment by deathaxe** [comment]
I don't think I will start maintaining multiple flavors of markdown as basically any online and offline tool comes with its own flaws, bugs and specific behaviors. There's not only python markdown (which is no CommonMark nor GFM compatible) parser at all, but also those from Go (aka Gohugo), MultiMarkdown and probably numerous more from all the hundreds of thousands of evolving scripting languages which all claim to do things better than others.

**Comment by eugenesvk** [comment]
> I don't think I will start maintaining multiple flavors

But there already was a 3rd GFM flavor maintained (in addition to Markdown and Multimarkdown) in the previous version 2, which basically got removed as a separate one in v3 (so now there are only Markdown and Multimarkdown)?

Anyway, what about a config option, is it feasible to adjust some rules in a syntax file based on user configuration, or is it only possible to have a separate `.sublime-syntax` file with different regex/scoping/etc. options?

**Comment by deathaxe** [comment]
The orignal Markdown basically was a heavily outdated and totally bugged TextMate syntax, which has been added at some point 10 or more years ago, but never was maintained. It saw its last fixes in 2013 or so. It didn't comply with CommonMark and was heavily limited due to TextMate `tmLanguage` format.

MultiMarkdown syntax was and is nothing else than Markdown GFM with its special key value syntax instead of frontmatter. No special rules with regards to markdown content itself.

So the only somehow maintained syntax was "Markdown GFM", which was and still is the `Markdown.sublime-syntax`.

So, no there have barely been 3 flavors before.

When reworking the syntax for ST4, I'll have inheritance in mind, so hopefully many aspects can be easily tweaked for different flavors, but I won't try out all those tools to write a syntax for each, which will comply with their detailed behavior.

Maybe there will be a base CommonMark syntax which is extended to add GFM features, but this will take a significant amount of time to mature.

**Comment by eugenesvk** [comment]
> So, no there have barely been 3 flavors before

Oh, ok, so that was just an illusion :) Thanks for the clarification

> When reworking the syntax for ST4, I'll have inheritance in mind, so hopefully many aspects can be easily tweaked for different flavors

Inheritance would be cool as it would allow (if I understand it correctly) a `/User/` markdown syntax file to add and **override** some specific rules without having to modify your plugin's syntaxes, right?

**Comment by deathaxe** [comment]
Yes, you understood inheritance correct. It requires thoroughly designed syntax structure though, which means to rewrite large parts of the syntax. But this will happen for ST4 only after stabilizing what we have in a ST3 compatible way.

**Comment by tomhundt** [comment]
@deathaxe **Thank you** for working on this package!!  I use it more all the time.

Re singleton tildes, I'm in the camp that says "do as GitHub say, not as they do" (spec over parser) since I'd more likely be copying text _from_ Sublime _to_ Github READMEs or whatever, and often use single tildes as number punctuation (`~100 bottles of beer on the wall`) and use only double tildes to write strikeouts.  So, it wouldn't bother me if Sublime were more strict than GitHub.  (Perhaps this will end up being a configuration option.)

Having a way to override things with a "user" file would be useful: like some others I know, I've gotten in the habit of using `[_]` as an empty checkbox (because `[ ]` doesn't look very boxy in proportionally-spaced fonts), plus `[-]` as a cancelled/won't-do item.  GFM specifies only `[ ]`, `[x]` and `[X]`.

**Comment by eugenesvk** [comment]
> But this will happen for ST4 only after stabilizing what we have in a ST3 compatible way.

But isn't this already possible right now in ST4? I've recently stumbled upon this new ST4 syntax extension feature:
> extends 4075
A string of a base syntax this syntax should inherit from. The base syntax must be specified using its package path, e.g. Packages/JavaScript/JavaScript.sublime-syntax. See Inheritance for an overview of syntax inheritance.

http://www.sublimetext.com/docs/syntax.html


...and it seems to be working exactly like I'd like — (if I place the file pasted below in my ST4's user config) I can replace a specific scope within your syntax without having to copy&modify the whole syntax file (and be on the hook for tracking any upstream changes and updating my local file).

I'd still suggest to change it in the original syntax and not permeate the legacy GitHub mistakes (so concur with @tomhundt's comment above re. the use case), but with such an easy fix I don't really mind much.

https://gist.github.com/eugenesvk/676d3033c67fdd3bab5c87f3d17faf05

`.../User/Markdown.sublime-syntax`:
```yaml
%YAML 1.2
---
name: Markdown # extends MarkdownEditing's Markdown syntax to replace ~ with ~~ as a strikethrough marker
file_extensions:
  - md
  - mdown
  - markdown
  - markdn
scope: text.html.markdown
extends: Packages/MarkdownEditing/syntaxes/Markdown.sublime-syntax

contexts:

  strikethrough:
    #-match: (?:~(?!~}|>|\s))+   # any number   of ~ up to ~> or ~~} critic markers
    - match: (?:~~(?!~}|>|\s))+  # any number>2 of ~ up to ~> or ~~} critic markers
      scope: punctuation.definition.strikethrough.begin.markdown
      push: strikethrough-content

  strikethrough-content:
    - meta_scope: markup.strikethrough.markdown-gfm
    #-match: (?:~(?!~}|>))+      # any number   of ~ up to ~> or ~~} critic markers
    - match: (?:~~(?!~}|>))+     # any number>2 of ~ up to ~> or ~~} critic markers
      scope: punctuation.definition.strikethrough.end.markdown
      pop: true
    - include: format-common
    - include: bold
    - include: italic
```

**Comment by deathaxe** [comment]
> But isn't this already possible right now in ST4? I've recently stumbled upon this new ST4 syntax extension feature:

Sure I have been using all new ST4 features since day one of their release during internal dev cycle.

But I still want to keep changes ST3 compatible for those who don't want to upgrade.

**Comment by GiovanH** [comment]
I'm having this same 

> > But this will happen for ST4 only after stabilizing what we have in a ST3 compatible way.
> 
> But isn't this already possible right now in ST4? I've recently stumbled upon this new ST4 syntax extension feature:
> 
> > extends 4075
> > A string of a base syntax this syntax should inherit from. The base syntax must be specified using its package path, e.g. Packages/JavaScript/JavaScript.sublime-syntax. See Inheritance for an overview of syntax inheritance.
> 
> http://www.sublimetext.com/docs/syntax.html
> 
> ...and it seems to be working exactly like I'd like — (if I place the file pasted below in my ST4's user config) I can replace a specific scope within your syntax without having to copy&modify the whole syntax file (and be on the hook for tracking any upstream changes and updating my local file).
> 
> I'd still suggest to change it in the original syntax and not permeate the legacy GitHub mistakes (so concur with @tomhundt's comment above re. the use case), but with such an easy fix I don't really mind much.
> 
> https://gist.github.com/eugenesvk/676d3033c67fdd3bab5c87f3d17faf05
> 
> `.../User/Markdown.sublime-syntax`:
> 
> ```yaml
> %YAML 1.2
> ---
> name: Markdown # extends MarkdownEditing's Markdown syntax to replace ~ with ~~ as a strikethrough marker
> file_extensions:
>   - md
>   - mdown
>   - markdown
>   - markdn
> scope: text.html.markdown
> extends: Packages/MarkdownEditing/syntaxes/Markdown.sublime-syntax
> 
> contexts:
> 
>   strikethrough:
>     #-match: (?:~(?!~}|>|\s))+   # any number   of ~ up to ~> or ~~} critic markers
>     - match: (?:~~(?!~}|>|\s))+  # any number>2 of ~ up to ~> or ~~} critic markers
>       scope: punctuation.definition.strikethrough.begin.markdown
>       push: strikethrough-content
> 
>   strikethrough-content:
>     - meta_scope: markup.strikethrough.markdown-gfm
>     #-match: (?:~(?!~}|>))+      # any number   of ~ up to ~> or ~~} critic markers
>     - match: (?:~~(?!~}|>))+     # any number>2 of ~ up to ~> or ~~} critic markers
>       scope: punctuation.definition.strikethrough.end.markdown
>       pop: true
>     - include: format-common
>     - include: bold
>     - include: italic
> ```

This fix is the correct answer, and it should probably be automatically supported by non-GFM syntaxes like MultiMarkdown (where `\~` doesn't escape the symbol, and renders both characters separately).

**Comment by deathaxe** [comment]
This issue is already addressed by #676. Github updated their official specs and based them on CommonMark. So there's no need to distinguish CommonMark and GFM anymore.

**Comment by stdedos** [comment]
Isn't it _technically_ a superset? i.e. inherits CM with their own changes/plugins?

**Comment by deathaxe** [comment]
According to https://github.github.com/gfm/ GFM is just an extension to CM. None of the additional rules conflict with CM. And so MDE's syntax is implemented. It implements CommonMark and adds further contexts to support strikethrough, GFM tasks, tables and GFM style autolinks.

The only reason I see to split CommonMark and GFM was to provide a more simple syntax not supporting any syntax highlighting within fenced code blocks. But this will be implemented in a ST4-only branch later, because this CommnMark syntax would then be inherited by a GFM syntax.
