### ISSUE TITLE
Headings Key-bindings Conflicts on Windows 

### ISSUE THREAD

**Issue by tajmone** [SublimeText-Markdown/MarkdownEditing#641]
The new Headings keybinding <kbd>alt</kbd><kbd>k</kbd>, <kbd>alt</kbd><kbd>0..6</kbd> won't work under Windows OS because <kbd>alt</kbd><kbd>0..6</kbd> are bind by default in ST to selecting Tabs.

I suggest changing them to <kbd>ctrl</kbd><kbd>k</kbd>, <kbd>ctrl</kbd><kbd>0..6</kbd> (hoping those won't conflict), although the original system of using just <kbd>ctrl</kbd><kbd>0..6</kbd> seemed more practical to me (since these are often used keystrokes while writing).

**Comment by deathaxe** [comment]
`ctrl+k, ctrl+0..6` is the default binding for folding and can't be used.

The main issue is just, me having forgotten to add `settings.` to the contexts.
