### ISSUE TITLE
Link definitions overwhelm Goto Symbol

### ISSUE THREAD

**Issue by reagle** [SublimeText-Markdown/MarkdownEditing#645]
I use "goto symbol" (`super+r`) to quickly navigate between the headings of my markdown documents. Now I'm noticing that link definitions (e.g., `[foo]: https://...`) appear in and overwhelm my goto panel. Where are such things defined such that I can exclude them? Or, is there a way, when using "goto symbol," that I can type something first and limit the type of symbol searched for? Or, perhaps, the goto symbol command accept parameters, which I could limit to heading and bind to a key?

**Comment by deathaxe** [comment]
Reference definitions are controlled via https://github.com/SublimeText-Markdown/MarkdownEditing/blob/master/syntaxes/Symbol%20List%20-%20Reference%20Link.tmPreferences

In order to be able to filter headings those symbols would need some special markers. (e.g.: not stripping leading hashes).

**Comment by reagle** [comment]
Thank you, I was able to disable link definitions from Goto Symbol by duplicating that file in my `User` directory and toggle the following from `1` to `0`.

    <key>showInSymbolList</key>
    <integer>0</integer>
