### ISSUE TITLE
Feature Request: Document outline

### ISSUE THREAD

**Issue by Kshitiz-Sharma** [SublimeText-Markdown/MarkdownEditing#646]
There is an [Outline](https://packagecontrol.io/packages/Outline) package for ST. It shows a pane with headings in the document.

![image](https://user-images.githubusercontent.com/6263572/134343207-824422b5-1227-48e6-8975-8171449964b0.png)

However, it hasn't been updated in 3 years and is missing some features such as:

1. Navigating to a section when a heading is clicked in the outline view
2. Scrolling the outline pane to stay in sync with the cursor position in the document

I wondering if this functionality can be absorbed in MarkdownEditing.

**Comment by deathaxe** [comment]
TBH, I am not a big fan of all those text based extra pane using features, which need to mess around with layouts/groups.

You could simply hit `ctrl+k, ctrl+9` to collapse all sections but keep all headings visible. This would display the document's outline already. From there you could `shift+tab` to only expand the section(s) of interest.

**Comment by Kshitiz-Sharma** [comment]
I do use collapse and fold extensively. However, Outline allows viewing the document structure without leaving your current editing position.

Another advantage is that it helps with multi-monitor setups (I have 4). You can pop out the outline pane and put it on another monitor.

Most of the code could be borrowed from [here](https://github.com/warmdev/SublimeOutline).

Just an idea.

**Comment by maegul** [comment]
I feel like the need for outlines as a separate window/buffer is getting to the point where being a core feature is making more sense.  

I'm thinking something a little like what Sublime Merge has, where there are multiple navigation "views" on the left.  Sublime Text could have a directory/file navigator and an outline navigator.  The Ctrl+R `Goto Symbol` feature basically creates this view already.  A permanent rendering is really all such a feature would be.

Popping it out into a separate window might be a bigger deal though 🤷
