### ISSUE TITLE
Version 3.0.3 breaks indentation for code blocks

### ISSUE THREAD

**Issue by Kshitiz-Sharma** [SublimeText-Markdown/MarkdownEditing#648]
In version 3.0.2 you could select a code block and press tab to indent it.

With 3.0.3 this no longer works. It seems to be related to the other [issue ](https://github.com/SublimeText-Markdown/MarkdownEditing/issues/647) I reported.

If the syntax file has simply been overwritten, there's no saying how many things it could break. Images and code blocks are the two examples we have.

**Comment by deathaxe** [comment]
Working fine here.
