### ISSUE TITLE
Auto Wrapping / Line Length?

### ISSUE THREAD

**Issue by cmod** [SublimeText-Markdown/MarkdownEditing#652]
First: Love the package. Thank you for making it.

Second: I guess my package auto-updated the other day; when I restarted Sublime today I noticed none of my markdown files were auto-line wrapping. Did I hallucinate that? I seem to remember that .md files, used in conjunction with MarkdownEditing, would center and wrap themselves, giving them a distinctly unique and useful visual differentiator compared to all the other code and text files lying about. 

Is there a way to turn this centered auto-wrap back on?

**Comment by deathaxe** [comment]
MarkdownEditing no longer manipulates visual settings in syntax specific settings as it is hard to revert/override.

see: https://sublimetext-markdown.github.io/MarkdownEditing/troubleshooting/#preferences-need-manual-update

Also discussed in https://github.com/SublimeText-Markdown/MarkdownEditing/issues/613

**Comment by cmod** [comment]
Ah, sorry I totally missed that in the thread. 

For those a bit technically befuddled and finding this thread instead, the trick is to put into Settings > Syntax Specific for .md files the following:

`// Layout
    "draw_centered": true,
    "word_wrap": true,
    "wrap_width": 80,
    "rulers": [],

    // Line
    "line_numbers": false,
    "highlight_line": false,
    "line_padding_top": 2,
    "line_padding_bottom": 0,

    // Caret
    "caret_style": "wide",
    "caret_extra_top": 3,
    "caret_extra_bottom": 3,`
