### ISSUE TITLE
Hitting enter after writing a title (v3.0.5)

### ISSUE THREAD

**Issue by stevenxxiu** [SublimeText-Markdown/MarkdownEditing#653]
When I write a title like

```
# Title
```

And hit `Enter` after typing it, it becomes:

```
# Titl
e
```

**Comment by deathaxe** [comment]
Can't reproduce neither with ST 3176 nor ST 4116 on Windows.

Which OS are you using?

Hitting enter calls

**Comment by deathaxe** [comment]
Got it! The issue is triggered if new title is added to the end of a document.
