### ISSUE TITLE
Ctrl+Alt+Period is bound to a command, prevents entering special character

### ISSUE THREAD

**Issue by ilpssun** [SublimeText-Markdown/MarkdownEditing#654]
Following up on #634, I found another keybinding with <kbd>Ctrl</kbd>+<kbd>Alt</kbd> that prevents me from inserting a special character:

<kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>.</kbd> (Period) is bound to some command and is thus overriding my entering the ellipsis character (…) with <kbd>AltGr</kbd>+<kbd>.</kbd> on Windows.

Please remove this keybinding.

**Comment by deathaxe** [comment]
Those key bindings can be disabled, if incompatible.

see: https://github.com/SublimeText-Markdown/MarkdownEditing/blob/b064a371d5abcdae22cb29f041d87744d86857c2/Preferences.sublime-settings#L131

**Comment by ilpssun** [comment]
Thanks for the hint!  That's a sufficient workaround for me.
