### ISSUE TITLE
Nested list indented content incorrectly classified as code

### ISSUE THREAD

**Issue by azriel91** [SublimeText-Markdown/MarkdownEditing#663]
Heya, I think this is a MarkdownEditing issue.

In nested lists, double indented text is classified as code; it should be considered to be regular text, because it's indented "once" relative to the nested list level.

![markdown_code_screenshot](https://user-images.githubusercontent.com/2993230/140270257-6d0aa8a2-02db-44df-bef7-d891e7b34143.png)

The `this should not be code` is highlighted as code, presumably because it's parsed as indented relative to "list item"

MarkdownEditing version: 3.0.7

---

If it's not a MarkdownEditing issue, please let me know where to forward it to, thanks!

**Comment by deathaxe** [comment]
This is an issue which can barely be solved with ST's current syntax engine capabilities. Context's can't track indentation depending on nesting level.
