### ISSUE TITLE
Color Scheme disambiguations

### ISSUE THREAD

**Issue by stdedos** [SublimeText-Markdown/MarkdownEditing#666]
According to the page https://sublimetext-markdown.github.io/MarkdownEditing/config/#change-color-scheme:

- monokaiC by @avivace is listed a "Color Scheme", but it is a theme (i.e. applies Sublime-Text-wide)
- Blackboard theme by @mdesantis, is dead

**Comment by deathaxe** [comment]
> monokaiC by @avivace is listed a "Color Scheme", but it is a theme (i.e. applies Sublime-Text-wide)

[ME-MonokaiC.tmTheme](https://github.com/avivace/MonokaiC/blob/master/themes/ME-MonokaiC.tmTheme) looks like a TextMate color scheme to me.

> Blackboard theme by @mdesantis, is dead

Missed to add the reference definition, thanks.

The link is: https://github.com/mdesantis/MarkdownEditing/blob/blackboard-theme/MarkdownEditor-Blackboard.tmTheme

**Comment by stdedos** [comment]
> > monokaiC by @avivace is listed a "Color Scheme", but it is a theme (i.e. applies Sublime-Text-wide)
> 
> [ME-MonokaiC.tmTheme](https://github.com/avivace/MonokaiC/blob/master/themes/ME-MonokaiC.tmTheme?rgh-link-date=2021-12-01T18%3A12%3A49Z) looks like a TextMate color scheme to me.
> 

Could be, but does not seem to work in conjunction with the aforementioned configuration option (i.e. `MarkdownEditing: Select Color Scheme`)
![image](https://user-images.githubusercontent.com/133706/144293964-1b046348-5821-4b09-a2b2-8be6601f3a9d.png)

(ofc I can download it and apply it globally, I guess - but I thought the plugin gave a specific-to-itself configuration option.)

**Comment by deathaxe** [comment]
`MarkdownEditing: Select Color Scheme` looks for `*.sublime-color-scheme` files starting with `MarkdownEditor` only.

**Comment by stdedos** [comment]
Yeah - that's what I mean. From my perspective, it's a little confusing 😕
If you are mentioning it there, then there's "some reason/connection".

It seems bizarre that you are "advertising a theme".

**Comment by deathaxe** [comment]
I just copied over those links from the old README. A fix to also look for `MarkdownEditing*.tmTheme` files has been added locally, but I don't think I'll change the naming scheme.

Also note: MarkdownEditing 2.x only displayed the color schemes shipped with this package! It didn't display any of those "advertised" 3rd-party schemes as well, while MDE 3.x displays all color schemes from any other package.

You might ask the author of MonokaiC to rename it accordingly, so it can be displayed.

**Comment by stdedos** [comment]
> Also note: MarkdownEditing 2.x only displayed the color schemes shipped with this package! It didn't display any of those "advertised" 3rd-party schemes as well, while MDE 3.x displays all color schemes from any other package.

Kewl! :-D

One of the more minor things that kept me from switching from the https://packagecontrol.io/packages/MarkdownLight, was also the themes being ... not to my liking. Good that support was added (and I figured out how to convert them).
Being MIT, I guess I can do it (even legally, right?)

> You might ask the author of MonokaiC to rename it accordingly, so it can be displayed.

Nah, I am not gonna. I spend ~30mins and figured out how to display the theme globally/"locally", and I didn't like it in any case.

**Comment by deathaxe** [comment]
Being MIT, I guess I can do it (even legally, right?)

Yes.

**Comment by mdesantis** [comment]
Hello! I've just noticed I've been mentioned in this issue. It seems you don't need my help, I just want to point out that if you do, I'm here.

**Comment by stdedos** [comment]
> Hello! I've just noticed I've been mentioned in this issue. It seems you don't need my help, I just want to point out that if you do, I'm here.

My bad, apologies for the "shortsighted copy-paste"🙂
