### ISSUE TITLE
Inserting line break in lists messes up the syntax

### ISSUE THREAD

**Issue by stevenxxiu** [SublimeText-Markdown/MarkdownEditing#669]
The following is *Markdown* which produces a line break in the middle of the list. The syntax highlighting fails however, as the `3` isn't highlighted as italics.

```
- 1
    - 2  
    <br/>
    - *3*
```

**Comment by deathaxe** [comment]
According to CommonMark (see: https://spec.commonmark.org/0.30/#html-blocks) `<br/>` starts a type 7 html block, which requires an empty line to be terminated.

As the following example shows, Github doesn't render the `*3*` italic.

- 1
    - 2  
    <br/>
    - *3*

Gitlab's Markdown renderer behaves the same way:

![grafik](https://user-images.githubusercontent.com/16542113/146232462-29b0b410-1e62-44b3-9ed9-2fba37766729.png)


Hence I'd call this working as expected.

**Comment by stevenxxiu** [comment]
Hmm ok I guess this and https://github.com/Python-Markdown/markdown that https://facelessuser.github.io/MarkdownPreview/ uses, appear to display the items differently.

Not much I can do now except to just use `---` and style that.
