### ISSUE TITLE
Uncolored link elements in 4107-3.1.0

### ISSUE THREAD

**Issue by GiovanH** [SublimeText-Markdown/MarkdownEditing#670]
Not sure if this is a bug or an intentional change. If it's an intentional change I would appreciate some guidance in how to manually revert the colors to their previous scheme.

Expected colors in 76342e69b4747839a772c547d39008d68073998a

![image](https://user-images.githubusercontent.com/6759280/146319227-adcde754-aceb-4c6d-ba3e-dbc9dea94ddb.png)

Unexpected colors in ec66bbee7396a3fec10a29cfc0fa30ec073a4e91

![image](https://user-images.githubusercontent.com/6759280/146319059-b4c66c7b-74cc-4405-b0dd-23791df5d572.png)

**Comment by deathaxe** [comment]
The `string` scopes have been removed from link/image descriptions for three reasons:

1. core Markdown syntax removed them long ago
2. link descriptions may contain images/html and other markup. Scoping them `string` is not correct.
3. `string` scope is something more common to source code. Everything in a Markdown document is basically text aka a string. So it doesn't make much sense to use it there.

You'd need to tweak your color scheme to get the colors back.

Example:

```
{
	"scope": "meta.image.inline.description.markdown, meta.image.reference.description.markdown, meta.link.inline.description.markdown, meta.link.reference.description.markdown, meta.link.reference.literal.description.markdown, meta.link.reference.wiki.description.markdown",
	"foreground": "var(--yellowish)"
},

```
