### ISSUE TITLE
Tilde in links break syntax highlighting

### ISSUE THREAD

**Issue by stevenxxiu** [SublimeText-Markdown/MarkdownEditing#677]
The following valid *Markdown* isn't highlighted correctly. *MarkdownEditing* thinks there's a strikethrough:

    [filenames - Make pwd result in terms of "~"? - Unix & Linux Stack Exchange](https://unix.stackexchange.com/questions/207210/make-pwd-result-in-terms-of/207214#207214)

**Comment by deathaxe** [comment]
More or less a duplicate of #637

**Comment by stevenxxiu** [comment]
Thanks, the comment https://github.com/SublimeText-Markdown/MarkdownEditing/issues/637#issuecomment-929835517 worked for me.
