### ISSUE TITLE
Mariana patch renders deleted text black-on-black

### ISSUE THREAD

**Issue by reagle** [SublimeText-Markdown/MarkdownEditing#678]
Full discussion on [ST Forum](https://forum.sublimetext.com/t/how-to-create-issue-for-mariana-deleted-markdown-is-dark-on-dark/62339).

> MarkdownEditing ships some patches for Monokai and Mariana to maintain old highlighting. The color for strikethrough obviously needs some tweaks. @deathaxe

**Comment by reagle** [comment]
I'm glad to see single tildas don't trigger strikeout, but is this what the new coloring is supposed to be? The current line highlighting makes the actual tildas difficult to see.

<img width="354" alt="Screen Shot 2022-01-24 at 09 34 57" src="https://user-images.githubusercontent.com/596814/150803182-f65d3e6d-9458-4e36-8ff9-ab603ca252c9.png">

**Comment by deathaxe** [comment]
Actually didn't notice that as I turned line highlighting off.

**Comment by reagle** [comment]
Should we reopen? Or should I file a separate report? As I mentioned, I'm trying to stick with defaults as much as possible, and I think line highlighting is the default.

**Comment by deathaxe** [comment]
Already fixed it locally.
