### ISSUE TITLE
Remove code fence symbols from Goto Symbol Panel

### ISSUE THREAD

**Issue by maegul** [SublimeText-Markdown/MarkdownEditing#682]
When using `Goto Symbol` with markdown files, `symbols` within code-fenced sections are also picked up (Sublime 4120).'

It would be good to be able to view only the Headings in the symbol list.

I recognise that using the cold folding is probably a good work around (`CTRL+K`, `CTRL+9`, use `CMD` on mac), but not a great one IMO.

**Comment by deathaxe** [comment]
This would require to modify all symbol list related `*.tmPreference` files of all embedded syntax packages. That's nothing MarkdownEditing can do.

**Comment by deathaxe** [comment]
Maybe you could add a `Symbol List Hide Code Symbols in Markdown.tmPreferences` in your User package to achieve something like that. Not sure it's working though. 

```xml
<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
	<key>scope</key>
	<string>text.html.markdown source</string>
	<key>settings</key>
	<dict>
		<key>showInSymbolList</key>
		<integer>0</integer>
		<key>showInIndexedSymbolList</key>
		<integer>0</integer>
	</dict>
</dict>
</plist>
```

**Comment by maegul** [comment]
> This would require to modify all symbol list related `*.tmPreference` files of all embedded syntax packages. That's nothing MarkdownEditing can do.

Well I was thinking of something that uses the API somehow, whether viable or not.

For instance, just in the console, these quick one liners show promise at getting only markdown headings as symbols:

```python
[symbol for symbol in view.symbol_regions() if symbol.syntax=='Markdown']

# or ...

[symbol for symbol in view.symbol_regions() if symbol.kind[2] == 'Navigation']
```

I personally don't know my way around the whole symbol thing though.  Still, I can see there being a specific command available in `MarkdownEditing` that provides a quick panel with only markdown headings and which the user can call with whatever keybinding they like, including as a substitute for `Goto Symbol`.

**Comment by deathaxe** [comment]
The content of ST's default Goto Symbol quick panel isn't controlled by plugins. It's only controlled by preferences files as posted above. I don't see much value in duplicating this functionality for certain types of symbols.
