### ISSUE TITLE
Slow editing large md files

### ISSUE THREAD

**Issue by davahub** [SublimeText-Markdown/MarkdownEditing#684]
I am getting lag when typing text and the document is about 5000 lines including many js code blocks.

Sublime Text Build: 4126
markdown: v3.2.2

**Comment by deathaxe** [comment]
I can't say something about a future release, but syntax test file of current release has about 7800 lines and takes 60ms to be parsed and highlighted on my Windows PC. A 5000 lines hand crafted sample file with headings paragraphs and js code blocks parses in just 27ms. As ST only parses small chunks of visible text while typing I don't see any obvious reason for input lags.

Any sample file available to probably find some edge cases?

Any other plugins installed which might be involved?

Input lags often means GUI being blocked by synchronous functions. Maybe `Main Menu > Tools > Developer > Profile Plugins...` reveals some culprits?

**Comment by deathaxe** [comment]
Related with https://github.com/sublimehq/sublime_text/issues/5504

**Comment by deathaxe** [comment]
Resolved by ST 4136+
