### ISSUE TITLE
Ignore spaces when collapsing links?

### ISSUE THREAD

**Issue by Jmuccigr** [SublimeText-Markdown/MarkdownEditing#687]
I'm using jekyll to create a website and spaces within link text are common. For example:

```
[Text]({% link directory/page.html %})
```
Spaces are also allowed within the link filename itself, though I try to avoid those.

mde will collapse the link text only up to the space before `link`, so everything after that appears un-collapsed.

Any way for a setting to change that and allow the space within the link and still have the entire link up to the `)` to collapse?

**Comment by deathaxe** [comment]
All ST4 users with latest MarkdownEditing 3.1.3 may be interested in [Liquid/Jekyll](https://github.com/deathaxe/sublime-liquid) to get full support for Liquid templates.

I am looking forward to get that fork merged to the official [Liquid](https://packagecontrol.io/packages/Liquid) package soon after the next ST4 dev build with latest changes from https://github.com/sublimehq/Packages is released as those are required for the package to work in case MarkdownEditing is not present.

In the meanwhile you may want to clone the repo into your _Packages_ path via

```sh
git clone --depth 1 https://github.com/deathaxe/sublime-liquid ~/.config/sublime-text/Packages Liquid
```

**Comment by deathaxe** [comment]
Official [Liquid](https://packagecontrol.io/packages/Liquid) package has been updated.

Liquid 2.0.0 requires at least ST4126.

When using ST4134 or newer _Markdown (Liquid)_ is dynamically created by extending ST's default Markdown syntax or - if present - MarkdownEditing's Markdown syntax. 

MarkdownEditing's syntax is an extension of core Markdown as well, providing support for more syntaxes in fenced code blocks.
