### ISSUE TITLE
Error in regex

### ISSUE THREAD

**Issue by AlertMouse** [SublimeText-Markdown/MarkdownEditing#705]
When I open markdown file, it prompts that error: Error loading syntax file "Packages/MarkdownEditing/syntaxes/Markdown.sublime-syntax": Error in regex: invalid backref number/name in regex ^(?!(?:\1[ ]{4}|\s*$))

**Comment by deathaxe** [comment]
Never have seen that error.

Which version of ST and MarkdownEditing?

Did you install MDE via Package Control?

Any example file it happens in?

**Comment by AlertMouse** [comment]
Sorry, this error only occurs on my office computer, I installed MDE by manual installation. I can't reproduce it on my personal PC. It may be due to the influence of the environment of my office computer or the way I manually installed it is incorrect. Tanks~

**Comment by small-cat** [comment]
I used Sublime text 3 on mac, when I install MDE manually
```shell
cd ~/Library/Application Support/Sublime Text 3/Packages
git clone https://github.com/SublimeText-Markdown/MarkdownEditing.git
```
and then, when I open Sublime, the error window pop
