### ISSUE TITLE
Steals focus on using "go to anywhere"

### ISSUE THREAD

**Issue by rchl** [SublimeText-Markdown/MarkdownEditing#710]
ctrl+p or cmd+p is interrupted and the quick panel is closed when package decides to fixup some headings.

I've noticed this happening on this repo: https://github.com/johnsoncodehk/volar when filtering for `features` in "go to anywhere".

The package removes trailing space from one header and makes the quick panel disappear automatically.

I know there is setting that could be disabled but I think that it's not an acceptable behavior by default. At the very least should be disabled by default and then documented that it can interrupt "go to anywhere" although I guess there might be a way to detect if file is being previewed. Not sure.

https://github.com/SublimeText-Markdown/MarkdownEditing/blob/a2a58e3cf380a78929ed7ccc73dbfc9e631b5016/plugins/headings/style.py#L90-L91

**Comment by rchl** [comment]
Note also how this setting references `mde.auto_detect_match_heading_hashes` which does not exist.

https://github.com/SublimeText-Markdown/MarkdownEditing/blob/a2a58e3cf380a78929ed7ccc73dbfc9e631b5016/Preferences.sublime-settings#L35-L36

**Comment by deathaxe** [comment]
I think we should just disable the function for transient and semi-transient views.
