### ISSUE TITLE
Duplicate Markdown syntaxes

### ISSUE THREAD

**Issue by rchl** [SublimeText-Markdown/MarkdownEditing#717]
With this package enabled the `Markdown` and `MultiMarkdown` syntaxes appear twice in the list. Is that expected?

![Screenshot 2023-01-04 at 09 43 33](https://user-images.githubusercontent.com/153197/210516775-4a88a404-14fc-426a-9023-9135745cbd9b.png)

If the expectation is that the user disables built-in `Markdown` package then it would be good to mention this in `install.txt` message file and also documentation.

**Comment by deathaxe** [comment]
That's more or less unavoidable.

Disabling default Markdown will break Rails syntax and probably others, while a dedicated syntax is required to add all the 3rd-party syntaxes for fenced code blocks.

The only option I see, is to rename it to something like `Markdown (MDE)`.

**Comment by rchl** [comment]
Think it would make sense to rename those. Especially if there is difference between this and default one since otherwise I don't know which one I'm selecting in the Command Palette.

**Comment by rchl** [comment]
Kinda weird that `MultiMarkdown` syntax appears twice though? There is no default one like that so where does the duplication come from?
