### ISSUE TITLE
Hotkeys for folding/unfolding don't work

### ISSUE THREAD

**Issue by glow12121** [SublimeText-Markdown/MarkdownEditing#719]
It seems that the default keys to fold or unfold a section do nothing. I tried other combinations, too, but to no result.

```
{ "keys": ["ctrl+shift+["], "command": "fold" },
{ "keys": ["ctrl+shift+]"], "command": "unfold" },
```

**Comment by deathaxe** [comment]
Sections are primarily folded by level via custom plugin commands. Folding/unfolding single sections via `mde_fold_section` is currently bound to `shift+tab` for historic reasons _(probably not ideal though)_.

`fold` and `unfold` are ST core commands which can fold sections by indentation level or via syntax rules (as of ST4143).

As paragraphs are not indented and no syntax based folding rules have ben designed and implemented, those core commands are more or less useless for Markdown at the moment.

MarkdownEditing ships with basic rules to enable syntax based folding of sections. Folding via `ctrl+shift+[` works fine on ST4143 (Win11), even though ST currently selects the whole folded region (see: https://github.com/sublimehq/sublime_text/issues/5797).

To unfold a section via `ctrl+shift+]`, the caret must be located directly in front or after the folding marker. It is not enough for it to be somewhere in the heading line. A somewhat related enhancement request to improve this scenario is filed as https://github.com/sublimehq/sublime_text/issues/5798.

**Comment by glow12121** [comment]
Thank you for explaining! I've just added this key-binding and now I can fold/unfold with this combination:

`{ "keys": ["ctrl+["], "command": "mde_fold_section" },`

A have a split keyboard on which tab and shift are right next to each other :)

**Comment by deathaxe** [comment]
Folding/Unfolding sections works using default key bindings instead of <kbd>shift+tab</kbd> as of MDE 3.1.9
