### ISSUE TITLE
Undesired folding

### ISSUE THREAD

**Issue by glow12121** [SublimeText-Markdown/MarkdownEditing#720]
After the plugin was installed, a lot of undesidered things started to be getting folded.

For example, in this line  `anchor` and the second `image` are automatically replaced with three dots. As I click on the dots, the text unfolds. I click on something else - it folds again.

```[![image alt text](image url link)](anchor link)```

In this line, the web address is folded and replaced with three yellow dots.

```[Author](https://www.amazon.com/long-address)```

How can I only make the plugin fold headlines - and only manually, on my command?

**Comment by deathaxe** [comment]
https://github.com/SublimeText-Markdown/MarkdownEditing/blob/bff21d04770a287cdd3ac6dc210ccf783d125ae0/Preferences.sublime-settings#L117-L122

**Comment by glow12121** [comment]
Many thanks, @deathaxe !
