### ISSUE TITLE
"Select color scheme" is wrong to "show home page"

### ISSUE THREAD

**Issue by pencilheart** [SublimeText-Markdown/MarkdownEditing#723]
The version is 3.1.9.

**Comment by deathaxe** [comment]
What exactly is the issue?

Nothing has changed with regards to "Select Color Scheme" command.

**Comment by pencilheart** [comment]
See here please, I don't know what's wrong.

![Kapture 2023-01-21 at 11 46 24](https://user-images.githubusercontent.com/61617063/213877538-44818323-905e-4599-ab1d-e9a73e791b57.gif)

**Comment by deathaxe** [comment]
Do you see any error messages in ST's concole?

**Comment by pencilheart** [comment]
Show `TypeError: show_quick_panel() got an unexpected keyword argument 'on_select'` in console.

**Comment by deathaxe** [comment]
This error indicates something to be wrong with your ST setup or you using quite outdated ST4 dev build.

Some ST4 dev builds shipped an API, which renamed `on_select` to `on_done` by accident. Current stable release however uses `on_select` again.

That's not an issue MarkdownEditing could fix.

**Comment by pencilheart** [comment]
Yes, you're definitely right. It's a dev version. Thanks for your help. Issue will be closed.
