### ISSUE TITLE
Toggle Folding Current Section key bindings overriding standard macOS tab switching

### ISSUE THREAD

**Issue by adrianh** [SublimeText-Markdown/MarkdownEditing#724]
This change in the latest release:

---

Replace "Toggle Folding Current Section" via shift+tab by

"Fold Current Section" via ctrl+shift+[
"Unfold Current Section" via ctrl+shift+]

---

seems to be overriding the standard macos cmd-shift-[ and cmd-shift-] to switch tabs. 

Glancing at the key bindings file it looks like "super+shift+[" etc. should be "ctrl-shift+[" etc. ?

**Comment by deathaxe** [comment]
The intention is to override ST's default fold/unfold binding, which seems to be `suber+alt+[` vs. `super+alt+]`.
