### ISSUE TITLE
Problems with folding

### ISSUE THREAD

**Issue by glow12121** [SublimeText-Markdown/MarkdownEditing#727]
I am observing several problems with folding markdown sections.

This is the source text:

![image](https://user-images.githubusercontent.com/29035180/218330890-db5ea78f-d3b5-440e-aee1-dd4dce554dd2.png)

Then I fold the `###` sections using this hoykey: `{ "keys": ["ctrl+shift+["], "command": "fold" },`

This is the outcome:

![image](https://user-images.githubusercontent.com/29035180/218330978-08b0a390-ba9d-48d6-9efb-e1da7393964c.png)

I believe the following are flaws here:

* In the folded condition, there is no empty line in-between `###` sections, which makes them hard to read.
* Folding eats up the `--------` dividing line, even though it may be used as an additional division in-between sections.
* There are no little arrows or smth. like this, to fold/unfold with a mouseclick.

**Comment by deathaxe** [comment]
> In the folded condition, there is no empty line in-between ### sections

Maybe a question of taste, but this is the style MarkdownEditing has always used to fold headings/sections. Should be easy to tweak, but I don't want to add settings for that and most (all other) users seem to be fine with current state.

> Folding eats up the `--------` dividing line, ...

Both syntax based folding rules and plugin based folding feature are designed to fold regions between headings. So this is working as expected.

> There are no little arrows or smth. like this, to fold/unfold with a mouseclick.

MarkdownEditing ships basic syntax based folding rules, which should enable ST to draw fold buttons next to headings.

![grafik](https://user-images.githubusercontent.com/16542113/218333559-a862b945-05ca-46e5-b998-88d8ee719ad3.png)

> **Note**
>
> Fold buttons are displayed only, if ST detects foldable regions via indentation levels or via folding rules. The latter one and thus fold buttons next to headings are enabled only if `"fold_style"` is set to `"auto"` or `"scope_only"`.

Beyond that MarkdownEditing has shipped plugin based folding features for ages. Started with long before syntax based folding was added to ST's set of core features. As there's no API to announce foldable reagions or to interact with fold buttons, key bindings are all plugins can use. ST doesn't display fold buttons until a folded region is detected, if it hasn't found foldable regions on its own.

MarkdownEditing overrides default fold/unfold key bindings to provide an as consistent as possible UX compared to ST's default behavior. 

Current state of ST's syntax based folding engine is insufficient to replace plugin code, completely.

> **Note**
>
> Syntax based folding (via buttons) and plugin based folding (via key bindings) may behave a little bit different for historic reasons and because of different philosophy with regards how sections between headings are intendet to be folded. Syntax based folding is to naive to support all features, plugin can do.

**Comment by glow12121** [comment]
> Maybe a question of taste, but this is the style MarkdownEditing has always used to fold headings/sections. Should be easy to tweak, but I don't want to add settings for that and most (all other) users seem to be fine with current state.

Thanks for the reply.

Folding is literally the main thing I need from the plugin and this style of folding seems very counter-intuitive. In markdown, empty lines are what creates separate paragraphs. Are there ways for me to tweak this?

**Comment by deathaxe** [comment]
Folding doesn't work "per paragraph" and there's no way to tweak it.

**Comment by glow12121** [comment]
I didn't ask about folding per paragraph -- but about keeping empty lines in-between folded sections.

The questions about the little mysterious triangles remains, too.

**Comment by deathaxe** [comment]
To enable fold buttons, set "fold_style" to "auto" or "scope_only" in Preferences - assuming ST 4145+. 

Otherwise, I can't say something about it. Basic syntax specific folding rules are provided, so folding buttons should appear in ST 4143+. If not, maybe a core issue.

**Comment by glow12121** [comment]
A. Oh well, in ST 4143 on Linux, these little triangles are seemingly not there.

B. If it is somehow possible to keep a distance in-between the folded headlines, please let me know.

![image](https://user-images.githubusercontent.com/29035180/218551650-dccd66d5-e500-4da0-82bf-4aaae0c0fdef.png)

**Comment by glow12121** [comment]
In the case of the little arrows on the left margin, I have figured out what was the problem. I had `"gutter": false,` which, naturally, made it impossible for the little arrows to be displayed.

**Comment by glow12121** [comment]
Why I think there should be an empty line in-between folded headlines by default -- because in Markdown an empty line is what creates a paragraph. No empty line is counter-intuitive. It looks out of tune too.
