### ISSUE TITLE
M.E. interferes with default color schemes

### ISSUE THREAD

**Issue by glow12121** [SublimeText-Markdown/MarkdownEditing#730]
Hi,

It seems that the plugin interferes with default color schemes and makes, for example, the `>` symbol invisible in block quotes, when in Monokai and Mariana schemes, as well as in all specific M.E. schemes.

The issue was described here:

https://github.com/sublimehq/sublime_text/issues/5947

**Comment by deathaxe** [comment]
MardownEditing does so by intent.

**Comment by deathaxe** [comment]
Duplicate of #659
