### ISSUE TITLE
Support for TOML frontmatter?

### ISSUE THREAD

**Issue by loikein** [SublimeText-Markdown/MarkdownEditing#736]
Hi, I was just wondering whether there is plan to support TOML frontmatter (surrounded by `+++` instead of `---` for YAML)? Thanks a lot!

Maybe related: [Support TOML frontmatter syntax highlighting in markdown files · Issue #41650 · microsoft/vscode](https://github.com/microsoft/vscode/issues/41650)

**Comment by loikein** [comment]
Wow, thank you so much for your quick response. I will look forward to the new version!

**Comment by deathaxe** [comment]
I normally collect a reasonable amount of changes. Your request was just 1 hour late for the last release, which was hanging around for months.

**Comment by loikein** [comment]
No worries at all.
