### ISSUE TITLE
Uninstalling problem

### ISSUE THREAD

**Issue by zambala** [SublimeText-Markdown/MarkdownEditing#739]
I am using Sublime Text 4 + windows 10 + package control

I am having a problem after uninstallation, 
I just installed for evaluation and very soon removed package,

now, the .md files are refusing to accept back the previous or any other Color Scheme, and whenever I focus on this tab I am getting at least 2 popup warnings:  unable to find MarkdownEditor, unable to load Markdown editor, etc...

I tried even restart the Sublime, it is still  the same issue...

upd.

I found the problem:

in AppData\Roaming\Sublime Text\Packages\User
it didn't remove a file Markdown.sublime.settings

I had to manually delete this

**Comment by deathaxe** [comment]
User files are not touched by intent, when removing packages, as it could easily lead to data loss.

Markdown.sublime-settings is a syntax specific setting file, which is also valid for built-in Markdown package. Thus removing it would easily break other things.

MarkdownEditing actually already tries to remove syntax specific color scheme settings, when being uninstalled. It relies on Package Controls event mechanism to detect being uninstalled.

**Comment by zambala** [comment]
It doesn't uninstall properly, just telling.

The markdown tab is completely screwed with error messages & impossibility to change color scheme;

If you don't like my suggestion, you are welcome to find another solution.
