### ISSUE TITLE
Use pygments for syntax highlighting in code block

### ISSUE THREAD

**Issue by ncarboni** [SublimeText-Markdown/MarkdownEditing#740]
While the list of supported languages for code blocks is quite long, some are still missing (ex: SPARQL). 
I was wondering it if it is possible to use [pygments](https://pygments.org/) as syntax highlighter instead (or other ones).

Alternatively, as the syntax of some of the language I used [are already available for ST](https://github.com/blake-regalia/linked-data.syntaxes/tree/d8ba9f81c6233cf5f041ba4561b8c0576bbdba37/src/syntax), do any know of any guide on how to add them to MarkdownEditing? I would love to use them in code blocks.

**Comment by deathaxe** [comment]
Highlighting text/source fully relies on ST's syntax engine. It is not possible to use pygments, tree-sitter or any other highlighting engine.

What is needed to highlight fenced code blocks, is:

1. a syntax definition that ST understands (e.g.: `<Name>.sublime-syntax`)
2. a context in Markdown.sublime-syntax which `embed`s that syntax.
   
   e.g.: https://github.com/SublimeText-Markdown/MarkdownEditing/blob/38bb41157433808ff265d5298edfd40f202804a1/syntaxes/Markdown.sublime-syntax#L1846C1-L1866

**Comment by ncarboni** [comment]
Thank you! I will make some tests and, If I manage to make something work, I will do a pull request
