### ISSUE TITLE
Allow blockquote visual style changes to be disabled so I can have my `>`'s back

### ISSUE THREAD

**Issue by 0xdevalias** [SublimeText-Markdown/MarkdownEditing#741]
Currently `MarkdownEditing` seems to visually change the leading `>`'s of a blockquote into a grey quote bar:

![image](https://github.com/SublimeText-Markdown/MarkdownEditing/assets/753891/2f48c2e6-0348-41b0-aeae-bb86268f6f7f)

But I don't want my `>`'s replaced.. I want it to look like plaintext still:

![image](https://github.com/SublimeText-Markdown/MarkdownEditing/assets/753891/939e9d00-c383-4781-9613-57bcad2db9f3)

While this is fine for something rendering markdown, it's absolutely not what I want while editing it; though I realise that others opinions on this will differ.

Since it's changing a default expectation people tend to have when editing a plaintext format like markdown; at the very least there should be an option that allows it to be disabled/overridden.

---

This doesn't seem to change between the colour schemes.

---

I tried to look through the code and figure out where/how to change this so I could contribute a fix, but I wasn't sure what part is even making this happen in the first place, so was unable to.

**Comment by deathaxe** [comment]
Duplicat of #659.

This behavior can be adjusted by customizing color scheme.
