### ISSUE TITLE
Changing `mde.auto_fold_link.enabled` from `true` to `false` while document open leaves UI broken

### ISSUE THREAD

**Issue by 0xdevalias** [SublimeText-Markdown/MarkdownEditing#742]
## Overview

There seems to be a bug when changing `mde.auto_fold_link.enabled` from `true` to `false` while a document is open.

## To Reproduce

With a document open (tested on an unsaved file, unsure if it applies to both saved/unsaved) that will have it's links collapsed:

```markdown
- [Foo](#foo)
- [Bar](#bar)
- [Baz](#baz)
```

With `mde.auto_fold_link.enabled` set to `true`, the links are collapsed as expected:

![image](https://github.com/SublimeText-Markdown/MarkdownEditing/assets/753891/0faed3ef-c0ad-49fa-adfe-a311b34b7f67)

And reveal again when we click on the link section:

![image](https://github.com/SublimeText-Markdown/MarkdownEditing/assets/753891/95778bce-47ae-4a5f-a86e-332aa37aca04)

Leaving that file open, if we now set `mde.auto_fold_link.enabled` to `false`, the 'collapsed links' are still present:

![image](https://github.com/SublimeText-Markdown/MarkdownEditing/assets/753891/1d097ba2-58e2-49b2-842f-325fa342f901)

And we can't even click on them to make them visible anymore:

![image](https://github.com/SublimeText-Markdown/MarkdownEditing/assets/753891/6dc2bf39-4734-4458-aad4-05d4bd46c37e)

## Proposed Solution

I'm not sure of the exact mechanics of implementing a fix for this, but my expectation as a user would be that when I disable a setting like that, that any open documents would first have that setting 'unapplied' on them as part of disabling it. (It seems that changing it from `false` to `true` does update open documents; so it's even weirder to me as a user that it doesn't work in reverse)

**Comment by deathaxe** [comment]
A fix requires tracking settings for changes and call unfold once setting value changes to `false`.
