### ISSUE TITLE
Update Github Markdown blockquotes snippets

### ISSUE THREAD

**Issue by Krow10** [SublimeText-Markdown/MarkdownEditing#743]
The current snippets `ghnote` and `ghwarn` are using a [deprecated syntax](https://github.com/orgs/community/discussions/16925) for rendering blockquotes information.

From the link above (update 14 Nov 2023):
> The initial syntax using e.g. **Note** isn't supported any longer.

The new snippets format should be (e.g. for `ghnote`):
```diff
@@ -1,6 +1,5 @@
 <snippet>
-	<content><![CDATA[> **Note**
->
+	<content><![CDATA[> [!NOTE]
 > ${0:enter text}
 ]]></content>
 	<tabTrigger>ghnote</tabTrigger>
	<scope>text.html.markdown - meta.frontmatter - meta.disable-markdown - meta.code-fence - markup.raw</scope>
	<description>Markdown Admonition</description>
</snippet>
```
Additionally, support for `ghtip`, `ghimportant` and `ghcaution` can be added.

I can try to work on a PR based on the [CONTRIBUTING.md](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/master/CONTRIBUTING.md) guidelines when I have some time later.

**Comment by deathaxe** [comment]
I'll update them when integrating https://github.com/sublimehq/Packages/pull/3892
