### ISSUE TITLE
List indentation symbol alternation

### ISSUE THREAD

**Issue by willrowe** [SublimeText-Markdown/MarkdownEditing#748]
I'm not sure if this is a bug or if this was changed intentionally, but when adding a list item I used to be able to tab or shift + tab and the symbol would alternate between `-`, `+`, and `*`. Now it uses the same symbol that the list was created with.

**Comment by deathaxe** [comment]
This behavior is controlled by

https://github.com/SublimeText-Markdown/MarkdownEditing/blob/bcf8d0be998eb29109377fa29c3cb149ace2a262/Preferences.sublime-settings#L47-L49

The default value was changed to `false` as most documents found on web seem to use `- ` only.

**Comment by willrowe** [comment]
@deathaxe thanks for pointing that out! Do you intentionally change `mde.list_indent_auto_switch_bullet` from `true` to `false`?

**Comment by deathaxe** [comment]
> The default value was changed to `false` as most documents found on web seem to use `- ` only.

**Comment by willrowe** [comment]
Sorry, missed that, blended in with the code preview. Thanks again!
