### ISSUE TITLE
Extra backtick left in code blocks

### ISSUE THREAD

**Issue by ditek** [SublimeText-Markdown/MarkdownEditing#749]
With the MarkdownEditing package installed, an extra backtick is left when creating a code block as seen here:

https://github.com/SublimeText-Markdown/MarkdownEditing/assets/10835824/824464ff-fe2a-423a-8a98-d6cacce7185c

Without the package, the native behaviour is to remove the closing backtick when more than two are inserted:

https://github.com/SublimeText-Markdown/MarkdownEditing/assets/10835824/6b086140-3cc4-4232-93a7-fef83fac6a16

I would argue that the native behaviour is the expected/preferred one.

**Comment by ditek** [comment]
Hi @deathaxe . I noticed that you added the `C: key bindings` tag to the issue. This is not specific to C. It's the same for any language or with no language at all. Using C was just to give an example.

**Comment by deathaxe** [comment]
`C:` stands for `Category:` No need to judge me on how I use my labels.

**Comment by ditek** [comment]
Sorry if that came out aggressive, but that's not what I meant. I just thought you misunderstood my report. I appreciate what you do.
