### ISSUE TITLE
Add Highlight Syntax Highlighting to MarkdownEditing

### ISSUE THREAD

**Issue by mmerline** [SublimeText-Markdown/MarkdownEditing#764]
If possible, please add [Highlight syntax](https://www.markdownguide.org/extended-syntax/#highlight) to MarkdownEditing.

In apps like iA Writer, “You can [use double equals signs to highlight text](https://ia.net/writer/support/basics/markdown-guide#formatting)”. Two equal signs (==) before and after the words highlights the text in the app and is rendered as `<mark>[highlighted text]</mark>` when exported as HTML.

![Screenshot of Highlighted Text in iA Writer](https://github.com/SublimeText-Markdown/MarkdownEditing/assets/1504420/86d582e0-6a58-461f-afe9-4959920e102f)

I recognize this is very similar to one aspect of the Critic Markup spec included in the Markdown Editing package, the `{== highlight==}{>> comment <<}` inline critic markup, but that markup renders as `<span class="critic criticcomment inline" data-comment=" comment ">[Critic Markup highlight text]</span>`. This would be complementary.

Thanks. Please let me know if you have any questions or if I missed some required information.

**Comment by deathaxe** [comment]
Note that's not a CommonMark nor Github flavoured markdown feature.

As long as no bold/italic or other content is to be supported within the highlighted region, implementation should however be rather simple.

**Comment by deathaxe** [comment]
Added by v3.1.14

**Comment by mmerline** [comment]
@deathaxe, thank you for implementing this. After updating the package it appears the standard MarkdownEditing themes aren't providing syntax highlighting for the added `==highlight==` code. Something I need to change on my end?

![Screenshot of ==highlight== Test](https://github.com/user-attachments/assets/9cd186e9-26db-4310-a4b3-3bca34518fb0)

**Comment by deathaxe** [comment]
You can customize them via `UI: Customize Color Scheme` and add your own user-defined highlighting rules, though.

```
{
	"name": "Markup: Highlight",
	"scope": "markup.highlight",
	"foreground": "black",
	"background": "yellow"
},
```

**Comment by mmerline** [comment]
> You can customize them via `UI: Customize Color Scheme` and add your own user-defined highlighting rules, though.
> 
> ```
> {
> 	"name": "Markup: Highlight",
> 	"scope": "markup.highlight",
> 	"foreground": "black",
> 	"background": "yellow"
> },
> ```

Is this the correct way to add that code to the default template?

```
// Documentation at https://www.sublimetext.com/docs/color_schemes.html
{
	"variables":
	{

	},
	"globals":
	{
		"selection_corner_style": "square",
		"brackets_options": "foreground bold glow",
	},
	"rules":
	[
		{
		"name": "Markup: Highlight",
		"scope": "markup.highlight",
		"foreground": "black",
		"background": "yellow"
		}
	]
}
```

**Comment by deathaxe** [comment]
Yeah.
