### ISSUE TITLE
fenced-terraform syntax falling back to invalid json

### ISSUE THREAD

**Issue by SamLR** [SublimeText-Markdown/MarkdownEditing#765]
I really love this package but I've noticed that the `fenced-json` syntax always embeds the `json.terraform` syntax that then resolves to `invalid.illegal.expected-mapping-key.json` for terraform attribute key/value pairs. 

The following change in [`syntaxes/Markdown.sublime-syntax:2737`](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/59c30632230837598bc257e26145ad0aa29a44ef/syntaxes/Markdown.sublime-syntax#L2737) seems to fix it but I'm unsure whether this is correct in how syntax embedding is supposed to work (I've not really messed with the `.sublime-syntax` files before)
```diff
# syntaxes/Markdown.sublime-syntax:2737
-         source.json.terraform
+         source.terraform
```

before the fix the scope looks like:
<img width="553" alt="fenced-json-terraform" src="https://github.com/user-attachments/assets/978f444c-e08b-4400-876a-e5908b5c52f4">
With the patch applied the scope becomes (and the error syntax highlighting goes away)
<img width="593" alt="fenced-terraform" src="https://github.com/user-attachments/assets/39b938a5-ef02-4d1c-acb9-631ce6e3b283">

**Comment by deathaxe** [comment]
Fixed by v3.1.14
