### ISSUE TITLE
Groovy syntax

### ISSUE THREAD

**Issue by flerpan01** [SublimeText-Markdown/MarkdownEditing#768]
Hi, love the package! Would it be possible to add syntax for [groovy](https://groovy-lang.org/syntax.html)? It's an extension of ~~javascript~~ java and used with Nextflow. 

Below the js syntax produce error for the triple quotes
<img width="1008" alt="Screenshot 2024-07-23 at 11 30 29" src="https://github.com/user-attachments/assets/7d1498b9-fa11-4e5a-b15b-752f6248ce0f">

**Comment by deathaxe** [comment]
Added by v3.1.14
