### ISSUE TITLE
Version 3.1.14 seems to have broken several features

### ISSUE THREAD

**Issue by tsimmons** [SublimeText-Markdown/MarkdownEditing#771]
Running Sublime Text Dev Channel, Build 4177. After MarkdownEditing was updated from 3.1.13 to 3.1.14 today, several auto-completion functions stopped working (automatically appending Header characters, auto-completing lists, etc.)

It also resulted in the dreaded "Cannot find the color scheme MarkdownEditing.*" over and over again for all the *.md documents I had open.

I uninstalled and reinstalled using Package Control (which is what I used originally to install it.) I see Github has 3.1.15 released but Package Control is still publishing 3.1.14. 

Perhaps 3.1.5 fixes some of these issues?

Thanks.

**Comment by deathaxe** [comment]
Those issues are likely related with an invalid utf-8 char in Markdown syntax, which is fixed by 3.1.5.

**Comment by tsimmons** [comment]
I'll wait until PC updates!

**Comment by tsimmons** [comment]
Correction on the versions (my bad): comparing 3.1.14 to 3.1.15

**Comment by tsimmons** [comment]
Wow, that was fast. 3.1.15 was released to PC and all is working now. Closing ticket.
