### ISSUE TITLE
Automatic Bullets Not Working

### ISSUE THREAD

**Issue by leadhkr** [SublimeText-Markdown/MarkdownEditing#773]
I recently installed the package via Package Control. When creating a list to a .md file, after inserting my first bullet (e.g., 1. Hello World or * Hello World) and pressing enter, it does not automatically insert a new bullet (just a blank line). Below are my list settings. What am I missing?

```
	// MarkdownEditing (Lists):
	// Align list item text at indentation level.
	// Adds <Tab> after list items instead of a single <space>.
	"mde.list_align_text": false,

	// MarkdownEditing (Lists):
	// Automatically insert or remove list item bullets while writing.
	"mde.list_auto_bullets": true,

	// MarkdownEditing (Lists):
	// Automatically switches list bullet when indenting blank list item with <Tab>.
	"mde.list_indent_auto_switch_bullet": false,

	// MarkdownEditing (Lists):
	// List bullets to be used for automatically switching. In their order.
	"mde.list_indent_bullets": ["*", "-", "+"],

	// MarkdownEditing (Lists):
	// Auto increments ordered list number. Set to false if you want always "1".
	"mde.auto_increment_ordered_list_number": true,
```

**Comment by deathaxe** [comment]
My hunch is a custom key binding for `enter` key in another package or your user bindings is overriding the required ones from MarkdownEditing.

To verify that, ...

1. open ST's console
2. call `sublime.log_commands(True)`
3. add a list item to a markdown containing view
4. hit enter after it
5. check executed command in console

It should be

```
command: insert_snippet {"contents": "${TM_CURRENT_LINE/^(?:\\s*((?:>\\s*)*)([-+*])(\\s+)).*/\n$1$2$3/}"}
```
