### ISSUE TITLE
How to render Latex Equations (i.e. MathJax)

### ISSUE THREAD

**Issue by vgoklani** [SublimeText-Markdown/MarkdownEditing#774]
For the latest MarkdownEditing release, how do we automatically render latex equations?

Following up from here:

* https://www.lucasshen.com/notes/st-md/st-md#rendering-latex-equations-permanently
* https://stackoverflow.com/questions/27972177/how-to-enable-mathjax-rendering-in-sublime-text-markdown-preview

**Comment by deathaxe** [comment]
MarkdownEditing doesn't provide any (Live-)Preview features.

There's a Markdown Images package to render images inline. Maybe a plugin like that could also create images from equations and display them.
