### ISSUE TITLE
Default behavior for `mde.list_indent_auto_switch_bullet` changed

### ISSUE THREAD

**Issue by RaytingSec** [SublimeText-Markdown/MarkdownEditing#777]
I noticed a regression in the configuration one day using ST, and after some digging I found it was due to a change in default behavior of `mde.list_indent_auto_switch_bullet` due to `Preferences.sublime-settings` being changed in a previous PR: https://github.com/SublimeText-Markdown/MarkdownEditing/commit/5e7986c1d66958c724c97253a0110ea6bda1bb48#diff-123226ec5ca72a09fb432c327f3299478e3031d2e53588b31748003451fe1ba9L64

Since the PR is to addresses the issue https://github.com/SublimeText-Markdown/MarkdownEditing/issues/744 which is about auto insertion of bullets, I wonder if the change in default behavior wasn't intentional, it definitely took me by surprise. I've forked the repo here, should I go ahead and create a PR? https://github.com/SublimeText-Markdown/MarkdownEditing/compare/master...RaytingSec:MarkdownEditing:master

**Comment by deathaxe** [comment]
I've actually disabled it, because the function bugs in various situation causing wrong bullets in wrong indentation levels. As I don't feel the drive to dig into it anytime soon the safer solution seemed to disable it by default.

It is only the default value of a setting, which was changed. It can be customized on end users end.

**Comment by RaytingSec** [comment]
I see, that makes sense to me. I've noticed the bugs but I've also thought it helpful to have enabled, I'll continue using it in user level settings. Appreciate the info!

Might be helpful to have the behavior change in the change log too, unless I missed it.
